<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Acme.Shop.Shipping</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Acme.Shop.Shipping.Contracts\Acme.Shop.Shipping.Contracts.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
