-- M001_init (sqlite): full schema baseline generated by Acta.Emit. Hand-edit only as a delta.
-- Schema placeholder `{{schema}}` is substituted by the migration runner at apply time.
-- Routine and view bodies are not baked in: the SQL object installer applies them after migrations.
-- SQLite: no schema container ({{schema}} is the attached database, normally `main`);
--         DbKind.UtcInstant -> INTEGER (epoch milliseconds); DbKind.Byte/Short/Int/Long -> integer;
--         DbKind.BinaryPayload/Bytes -> BLOB; surrogate keys use AUTOINCREMENT rowids.

-- SQLite has no schema container; tables are created in the attached database ({{schema}}).

-- JobAlert
CREATE TABLE IF NOT EXISTS {{schema}}.alerts (
    id integer PRIMARY KEY AUTOINCREMENT,
    alert_ref text NOT NULL,
    namespace_id integer NOT NULL,
    job_id integer NULL,
    job_ref text NULL,
    origin_code integer NOT NULL,
    severity_code integer NOT NULL,
    kind_code integer NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    channel_name text NOT NULL,
    dedupe_key text NULL,
    occurrence_count integer NOT NULL,
    last_projected_event_id integer NULL,
    resolved_at_utc integer NULL,
    acknowledged_at_utc integer NULL,
    delivery_status_code integer NOT NULL,
    retry_count integer NOT NULL,
    retry_after_utc integer NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_alerts_job_ref_pair CHECK ((job_id IS NULL AND job_ref IS NULL) OR (job_id IS NOT NULL AND job_ref IS NOT NULL))
    , CONSTRAINT ck_alerts_occurrence_count CHECK (occurrence_count >= 1)
    , CONSTRAINT ck_alerts_origin_code CHECK (origin_code IN (10, 20))
    , CONSTRAINT ck_alerts_severity_code CHECK (severity_code IN (10, 20, 30, 40))
    , CONSTRAINT ck_alerts_delivery_status_code CHECK (delivery_status_code IN (10, 20, 30, 100, 200))
    , CONSTRAINT ck_alerts_retry_count_byte CHECK (retry_count BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_alerts_dedupe_identity ON alerts (namespace_id, dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_alerts_delivery_due ON alerts (namespace_id, delivery_status_code, retry_after_utc, id);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_alerts_namespace_created ON alerts (namespace_id, created_at_utc DESC, id DESC);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_alerts_namespace_unresolved ON alerts (namespace_id, created_at_utc DESC, id DESC) WHERE resolved_at_utc IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_alerts_ref ON alerts (alert_ref);
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_alerts_dedupe ON alerts (namespace_id, dedupe_key) WHERE dedupe_key IS NOT NULL AND resolved_at_utc IS NULL;

-- JobDefinition
CREATE TABLE IF NOT EXISTS {{schema}}.definitions (
    id integer PRIMARY KEY AUTOINCREMENT,
    namespace_id integer NOT NULL,
    name text NOT NULL,
    status_code integer NOT NULL,
    definition_hash text NOT NULL,
    manifest_generation_at_utc integer NOT NULL,
    input_type_name text NOT NULL,
    input_format_id integer NOT NULL,
    input_format_name text NOT NULL,
    output_type_name text NULL,
    output_format_id integer NOT NULL,
    output_format_name text NOT NULL,
    tenant_requirement_code integer NOT NULL,
    priority_code integer NOT NULL,
    priority_code_override integer NULL,
    priority_code_effective integer AS (COALESCE(priority_code_override, priority_code)) STORED,
    max_attempts integer NOT NULL,
    max_attempts_override integer NULL,
    max_attempts_effective integer AS (COALESCE(max_attempts_override, max_attempts)) STORED,
    backoff text NOT NULL,
    backoff_override text NULL,
    backoff_effective text AS (COALESCE(backoff_override, backoff)) STORED,
    execution_timeout_seconds integer NOT NULL,
    execution_timeout_seconds_override integer NULL,
    execution_timeout_seconds_effective integer AS (COALESCE(execution_timeout_seconds_override, execution_timeout_seconds)) STORED,
    deadline_seconds integer NOT NULL,
    deadline_seconds_override integer NULL,
    deadline_seconds_effective integer AS (COALESCE(deadline_seconds_override, deadline_seconds)) STORED,
    deadline_behavior_code integer NOT NULL,
    deadline_behavior_code_override integer NULL,
    deadline_behavior_code_effective integer AS (COALESCE(deadline_behavior_code_override, deadline_behavior_code)) STORED,
    retention_seconds integer NOT NULL,
    retention_seconds_override integer NULL,
    retention_seconds_effective integer AS (COALESCE(retention_seconds_override, retention_seconds)) STORED,
    audit_level_code integer NOT NULL,
    audit_level_code_override integer NULL,
    audit_level_code_effective integer AS (COALESCE(audit_level_code_override, audit_level_code)) STORED,
    alert_profile_code integer NOT NULL,
    alert_profile_code_override integer NULL,
    alert_profile_code_effective integer AS (COALESCE(alert_profile_code_override, alert_profile_code)) STORED,
    alert_channel_name text NULL,
    alert_channel_name_override text NULL,
    alert_channel_name_effective text AS (COALESCE(alert_channel_name_override, alert_channel_name)) STORED,
    runbook_url text NULL,
    runbook_url_override text NULL,
    runbook_url_effective text AS (COALESCE(runbook_url_override, runbook_url)) STORED,
    display_name text NULL,
    display_name_override text NULL,
    display_name_effective text AS (COALESCE(display_name_override, display_name)) STORED,
    description text NULL,
    description_override text NULL,
    description_effective text AS (COALESCE(description_override, description)) STORED,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_definitions_max_attempts CHECK (max_attempts >= 1)
    , CONSTRAINT ck_definitions_max_attempts_override CHECK (max_attempts_override IS NULL OR max_attempts_override >= 1)
    , CONSTRAINT ck_definitions_execution_timeout CHECK (execution_timeout_seconds > 0)
    , CONSTRAINT ck_definitions_execution_timeout_override CHECK (execution_timeout_seconds_override IS NULL OR execution_timeout_seconds_override > 0)
    , CONSTRAINT ck_definitions_deadline CHECK (deadline_seconds >= 0)
    , CONSTRAINT ck_definitions_deadline_override CHECK (deadline_seconds_override IS NULL OR deadline_seconds_override >= 0)
    , CONSTRAINT ck_definitions_retention CHECK (retention_seconds >= 0)
    , CONSTRAINT ck_definitions_retention_override CHECK (retention_seconds_override IS NULL OR retention_seconds_override >= 0)
    , CONSTRAINT ck_definitions_status_code CHECK (status_code IN (10, 240))
    , CONSTRAINT ck_definitions_tenant_requirement_code CHECK (tenant_requirement_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_priority_code_override CHECK (priority_code_override IS NULL OR priority_code_override IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_deadline_behavior_code CHECK (deadline_behavior_code IN (10, 20))
    , CONSTRAINT ck_definitions_deadline_behavior_code_override CHECK (deadline_behavior_code_override IS NULL OR deadline_behavior_code_override IN (10, 20))
    , CONSTRAINT ck_definitions_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_audit_level_code_override CHECK (audit_level_code_override IS NULL OR audit_level_code_override IN (0, 10, 20))
    , CONSTRAINT ck_definitions_alert_profile_code CHECK (alert_profile_code IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_alert_profile_code_override CHECK (alert_profile_code_override IS NULL OR alert_profile_code_override IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
    , CONSTRAINT ck_definitions_output_format_id_byte CHECK (output_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_definitions_namespace_name ON definitions (namespace_id, name);

-- JobEvent
CREATE TABLE IF NOT EXISTS {{schema}}.events (
    id integer PRIMARY KEY AUTOINCREMENT,
    event_code integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    namespace_id integer NOT NULL,
    actor_code integer NOT NULL,
    actor_key text NULL,
    job_id integer NULL,
    job_ref text NULL,
    execution_number integer NULL,
    lineage_root_id integer NULL,
    definition_id integer NULL,
    tenant_id integer NULL,
    worker_id integer NULL,
    from_status_code integer NULL,
    to_status_code integer NULL,
    execution_status_code integer NULL,
    duration_ms integer NULL,
    reason_code integer NULL,
    reason_message text NULL,
    detail_format_id integer DEFAULT 0 NOT NULL,
    detail blob NULL
    , CONSTRAINT ck_events_detail_pair CHECK ((detail_format_id = 0 AND detail IS NULL) OR (detail_format_id <> 0 AND detail IS NOT NULL))
    , CONSTRAINT ck_events_actor_code CHECK (actor_code IN (10, 20, 50, 70))
    , CONSTRAINT ck_events_from_status_code CHECK (from_status_code IS NULL OR from_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_to_status_code CHECK (to_status_code IS NULL OR to_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_execution_status_code CHECK (execution_status_code IS NULL OR execution_status_code IN (50, 100, 150, 151, 152, 200, 220, 230))
    , CONSTRAINT ck_events_detail_format_id_byte CHECK (detail_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_events_lineage_timeline ON events (lineage_root_id, created_at_utc, id) WHERE lineage_root_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_events_namespace_timeline ON events (namespace_id, event_code, created_at_utc, id);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_events_job_timeline ON events (job_id, created_at_utc, id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_events_namespace_created ON events (namespace_id, created_at_utc DESC, id DESC);

-- Job
CREATE TABLE IF NOT EXISTS {{schema}}.jobs (
    id integer PRIMARY KEY AUTOINCREMENT,
    job_ref text NOT NULL,
    namespace_id integer NOT NULL,
    definition_id integer NOT NULL,
    lineage_root_id integer NULL,
    parent_id integer NULL,
    tenant_id integer NULL,
    deduplication_key text NULL,
    correlation_key text NULL,
    exclusive_key text NULL,
    input_format_id integer NOT NULL,
    input blob NULL,
    audit_level_code integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL
    , CONSTRAINT ck_jobs_input_pair CHECK ((input_format_id = 0 AND input IS NULL) OR (input_format_id <> 0 AND input IS NOT NULL))
    , CONSTRAINT ck_jobs_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_jobs_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_jobs_parent ON jobs (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_jobs_namespace_created ON jobs (namespace_id, created_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_jobs_ref ON jobs (job_ref);
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_jobs_deduplication_key_root ON jobs (namespace_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_jobs_deduplication_key_child ON jobs (parent_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NOT NULL;

-- Lock
CREATE TABLE IF NOT EXISTS {{schema}}.locks (
    lock_key text NOT NULL,
    job_id integer NOT NULL,
    expires_at_utc integer NOT NULL,
    hold_token text NOT NULL
    , CONSTRAINT pk_locks PRIMARY KEY (lock_key)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_locks_reclaim_expired ON locks (expires_at_utc);

-- JobNamespace
CREATE TABLE IF NOT EXISTS {{schema}}.namespaces (
    id integer PRIMARY KEY AUTOINCREMENT,
    name text NOT NULL,
    owner_team text NULL,
    description text NULL,
    status_code integer NOT NULL,
    catalog_hash text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_namespaces_status_code CHECK (status_code IN (10, 20))
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_namespaces_name ON namespaces (name);

-- Seed: reserved system namespace (id=1, 'sys') for cross-namespace audit events. Collation-neutral.
INSERT OR IGNORE INTO {{schema}}.namespaces (id, name, status_code, description, created_at_utc, modified_at_utc)
VALUES (1, 'sys', 10, 'Reserved system namespace for cross-namespace audit events.', CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER), CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER));

-- JobResult
CREATE TABLE IF NOT EXISTS {{schema}}.results (
    job_id integer NOT NULL,
    execution_number integer NOT NULL,
    result_format_id integer NOT NULL,
    result blob NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL
    , CONSTRAINT pk_results PRIMARY KEY (job_id, execution_number)
    , CONSTRAINT ck_results_format_not_none CHECK (result_format_id <> 0)
    , CONSTRAINT ck_results_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_results_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;

-- JobRuntime
CREATE TABLE IF NOT EXISTS {{schema}}.runtimes (
    job_id integer NOT NULL,
    namespace_id integer NOT NULL,
    status_code integer NOT NULL,
    priority_code integer NOT NULL,
    next_run_at_utc integer NULL,
    execution_number integer NOT NULL,
    failure_count integer NOT NULL,
    leased_by_worker_id integer NULL,
    lease_expires_at_utc integer NULL,
    retention_until_utc integer NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_runtimes PRIMARY KEY (job_id)
    , CONSTRAINT ck_runtimes_lease_consistency CHECK ((leased_by_worker_id IS NULL AND lease_expires_at_utc IS NULL) OR (leased_by_worker_id IS NOT NULL AND lease_expires_at_utc IS NOT NULL))
    , CONSTRAINT ck_runtimes_counters CHECK (execution_number >= 0 AND failure_count >= 0)
    , CONSTRAINT ck_runtimes_status_code CHECK (status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_runtimes_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT fk_runtimes_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_runtimes_claim_ready ON runtimes (namespace_id, priority_code DESC, next_run_at_utc, job_id) WHERE status_code = 10;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_runtimes_retention ON runtimes (namespace_id, retention_until_utc, job_id) WHERE retention_until_utc IS NOT NULL AND status_code IN (100, 200, 220);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_runtimes_worker_inflight ON runtimes (leased_by_worker_id, status_code) WHERE leased_by_worker_id IS NOT NULL AND status_code IN (40, 50);

-- JobSchedule
CREATE TABLE IF NOT EXISTS {{schema}}.schedules (
    id integer PRIMARY KEY AUTOINCREMENT,
    namespace_id integer NOT NULL,
    job_id integer NOT NULL,
    definition_id integer NOT NULL,
    name text NOT NULL,
    origin_code integer NOT NULL,
    expression text NOT NULL,
    expression_override text NULL,
    expression_effective text AS (COALESCE(expression_override, expression)) STORED,
    time_zone_id text NOT NULL,
    time_zone_id_override text NULL,
    time_zone_id_effective text AS (COALESCE(time_zone_id_override, time_zone_id)) STORED,
    expression_kind_code integer NOT NULL,
    misfire_strategy_code integer NOT NULL,
    next_run_at_utc integer NULL,
    last_occurrence_at_utc integer NULL,
    status_code integer NOT NULL,
    paused_until_utc integer NULL,
    description text NULL,
    reason_message text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_schedules_paused_pair CHECK (status_code = 30 OR paused_until_utc IS NULL)
    , CONSTRAINT ck_schedules_orphan_origin CHECK (origin_code = 40 OR status_code <> 230)
    , CONSTRAINT ck_schedules_origin_code CHECK (origin_code IN (20, 40))
    , CONSTRAINT ck_schedules_expression_kind_code CHECK (expression_kind_code IN (10, 20))
    , CONSTRAINT ck_schedules_misfire_strategy_code CHECK (misfire_strategy_code IN (10, 20))
    , CONSTRAINT ck_schedules_status_code CHECK (status_code IN (10, 30, 230))
    , CONSTRAINT fk_schedules_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
    , CONSTRAINT fk_schedules_definitions FOREIGN KEY (definition_id) REFERENCES definitions (id)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_schedules_namespace_next ON schedules (namespace_id, next_run_at_utc, id) WHERE status_code <> 230;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_schedules_job_name ON schedules (job_id, name);

-- Setting
CREATE TABLE IF NOT EXISTS {{schema}}.settings (
    id integer PRIMARY KEY AUTOINCREMENT,
    scope_code integer NOT NULL,
    scope_id integer NULL,
    name text NOT NULL,
    value_format_id integer NOT NULL,
    value blob NULL,
    description text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_settings_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_settings_scope_code CHECK (scope_code IN (10, 30, 40))
    , CONSTRAINT ck_settings_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_settings_scope_name ON settings (scope_code, scope_id, name) WHERE scope_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_settings_global_name ON settings (scope_code, name) WHERE scope_id IS NULL;

-- JobStep
CREATE TABLE IF NOT EXISTS {{schema}}.steps (
    id integer PRIMARY KEY AUTOINCREMENT,
    job_id integer NOT NULL,
    name text NOT NULL,
    status_code integer NOT NULL,
    attempt_number integer NOT NULL,
    next_retry_at_utc integer NULL,
    reason_code integer NULL,
    reason_message text NULL,
    result_format_id integer NOT NULL,
    result blob NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_steps_result_pair CHECK ((result_format_id = 0 AND result IS NULL) OR (result_format_id <> 0 AND result IS NOT NULL))
    , CONSTRAINT ck_steps_attempt_number CHECK (attempt_number >= 1)
    , CONSTRAINT ck_steps_status_code CHECK (status_code IN (10, 100, 200, 230))
    , CONSTRAINT ck_steps_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_steps_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_steps_job_name ON steps (job_id, name);

-- Tag
CREATE TABLE IF NOT EXISTS {{schema}}.tags (
    scope_code integer NOT NULL,
    scope_id integer NOT NULL,
    namespace_id integer NULL,
    name text NOT NULL,
    value text NULL,
    value_search text NULL
    , CONSTRAINT pk_tags PRIMARY KEY (scope_code, scope_id, name)
    , CONSTRAINT ck_tags_scope_id CHECK (scope_id > 0)
    , CONSTRAINT ck_tags_namespace_id CHECK (namespace_id IS NULL OR namespace_id > 0)
    , CONSTRAINT ck_tags_scope_namespace CHECK ((scope_code = 20 AND namespace_id IS NULL) OR (scope_code = 30 AND namespace_id IS NOT NULL AND scope_id = namespace_id) OR (scope_code IN (40, 50, 60, 70, 80, 90) AND namespace_id IS NOT NULL))
    , CONSTRAINT ck_tags_value_search CHECK ((value IS NULL AND value_search IS NULL) OR (value IS NOT NULL AND value_search IS NOT NULL))
    , CONSTRAINT ck_tags_scope_code CHECK (scope_code IN (20, 30, 40, 50, 60, 70, 80, 90))
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_tags_namespace_name_value_search ON tags (namespace_id, name, value_search, scope_code, scope_id);

-- Tenant
CREATE TABLE IF NOT EXISTS {{schema}}.tenants (
    id integer PRIMARY KEY AUTOINCREMENT,
    tenant_key text NOT NULL,
    status_code integer NOT NULL,
    display_name text NULL,
    description text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_tenants_status_code CHECK (status_code IN (10, 20))
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_tenants_key ON tenants (tenant_key);

-- JobWorker
CREATE TABLE IF NOT EXISTS {{schema}}.workers (
    id integer PRIMARY KEY AUTOINCREMENT,
    worker_ref text NOT NULL,
    namespace_id integer NOT NULL,
    status_code integer NOT NULL,
    deployment_version text NOT NULL,
    host text NOT NULL,
    engine_version text NULL,
    dotnet_version text NULL,
    process_id integer NULL,
    max_concurrency integer NOT NULL,
    last_seen_at_utc integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_workers_max_concurrency CHECK (max_concurrency > 0)
    , CONSTRAINT ck_workers_status_code CHECK (status_code IN (10, 80, 100, 200))
    , CONSTRAINT fk_workers_namespaces FOREIGN KEY (namespace_id) REFERENCES namespaces (id)
) STRICT;
CREATE INDEX IF NOT EXISTS {{schema}}.ix_workers_namespace_status_last_seen ON workers (namespace_id, status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_workers_status_last_seen ON workers (status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS {{schema}}.ix_workers_namespace_last_seen ON workers (namespace_id, last_seen_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS {{schema}}.ux_workers_ref ON workers (worker_ref);

-- JobCheckpoint
CREATE TABLE IF NOT EXISTS {{schema}}.checkpoints (
    job_id integer NOT NULL,
    kind_code integer NOT NULL,
    name text NOT NULL,
    status_code integer NULL,
    due_at_utc integer NULL,
    value_format_id integer DEFAULT 0 NOT NULL,
    value blob NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_checkpoints PRIMARY KEY (job_id, kind_code, name)
    , CONSTRAINT ck_checkpoints_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_checkpoints_kind_code CHECK (kind_code IN (10, 20, 30, 40, 50))
    , CONSTRAINT ck_checkpoints_status_code CHECK (status_code IS NULL OR status_code IN (10, 20, 100))
    , CONSTRAINT ck_checkpoints_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_checkpoints_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;


INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (0, 'init-entity-refs-v1', '{{schema}}')
ON CONFLICT (version) DO NOTHING;
INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (1, 'init', '{{schema}}')
ON CONFLICT (version) DO NOTHING;
