// Concept: automatic alert escalation -- FirstFailure, ThresholdReached, and FinalFailure stages.

using Acta;
using Acta.Concepts.AlertEscalation;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = Host.CreateApplicationBuilder(args);

builder.Services.UseActa(j =>
{
    j.UseLocalDatabase(builder.Configuration);

    // AlertFailureThreshold = 2: the ThresholdReached alert fires when OccurrenceCount reaches 2.
    j.ConfigureOptions(o => o.AlertFailureThreshold = 2);

    j.Run<AlertEscalationJobs>("alert-escalation");
});

using var host = builder.Build();
await host.StartAsync();

var jobs = host.Services.GetRequiredService<IJobs>();
var queries = host.Services.GetRequiredService<IJobs>();

// MaxAttempts = 4, Backoff = "0s": four quick failures exhaust the budget.
var outcome = await jobs.EnqueueAsync(new UnstableReport("quarterly"));
Console.WriteLine($"enqueued {outcome.JobRef}");

// Wait for all 4 attempts to exhaust and the job to reach Failed.
Console.WriteLine("waiting for terminal failure...");
var jobId = outcome.JobId;
while (true)
{
    var status = await jobs.GetStatusAsync(JobLookup.ById(jobId));
    if (status == JobStatusCode.Failed)
        break;
    await Task.Delay(200);
}
Console.WriteLine("job reached Failed");

// Automatic alerts (FirstFailure, ThresholdReached, FinalFailure) are generated by the __alerts
// Cron.EveryMinute sweep -- they do not appear at failure time. Poll until FinalFailure appears.
Console.WriteLine("waiting for the __alerts sweep...");
IReadOnlyList<JobAlertListItem> alertItems = [];
while (true)
{
    var page = await queries.Alerts.ListAsync(new ListJobAlertsQuery(JobNamespace: "alert-escalation"));
    alertItems = page.Items;
    if (alertItems.Any(a => a.Kind == AlertKindCode.FinalFailure))
        break;
    Console.WriteLine("waiting for the __alerts sweep...");
    await Task.Delay(5_000);
}

Console.WriteLine($"alerts ({alertItems.Count}):");
foreach (var alert in alertItems.OrderBy(a => a.CreatedAtUtc))
{
    Console.WriteLine($"  [{alert.Severity}] {alert.Kind} x{alert.OccurrenceCount} origin={alert.Origin} channel='{alert.ChannelName}'");
}

await host.StopAsync();

namespace Acta.Concepts.AlertEscalation
{
    public sealed record UnstableReport(string Name);

    public sealed class UnstableReportJob
    {
        // AlertProfile = OnFailure (default): automatic failure alerts on every retryable failure
        // and a separate FinalFailure alert when the attempt budget is exhausted.
        [Job("unstable-report", MaxAttempts = 4, Backoff = "0s")]
        public static Task Handle(UnstableReport input, CancellationToken ct)
        {
            Console.WriteLine($"[{input.Name}] attempt failed");
            throw new InvalidOperationException($"report {input.Name} unavailable");
        }
    }
}
