using Acta.Postgres.Schema;
using Acta.Tests.Conformance.Testing;
using Npgsql;
using NpgsqlTypes;
using Xunit;

namespace Acta.Tests.Conformance.Postgres.Testing;

/// <summary>
/// PostgreSQL-backed handle to the shared <c>acta_test</c> schema. Delegates migration apply to
/// <see cref="PostgresSchemaMigrator"/> and upserts the test assembly's framework <c>namespaces</c>
/// row on first touch.
/// </summary>
/// <remarks>
/// The first successful bootstrap is cached; <see cref="DisposeAsync"/> is a no-op so rows persist for
/// inspection.
/// </remarks>
public sealed class PgIntegrationSchema : IIntegrationSchema
{
    // Unique per test run so the append-only acta_test schema gets a fresh framework namespace each run
    // rather than re-touching a fixed name.
    private static readonly string FrameworkNamespaceName = "acta-tests-" + Guid.NewGuid().ToString("N");

    // xUnit runs test classes in parallel. Serialize cold bootstrap inside this process so a missing
    // acta-test database is created/applied once; cache only success so transient Postgres startup
    // failures can retry on the next first-touch.
    private static readonly SemaphoreSlim s_bootstrapGate = new(1, 1);
    private static string? s_bootstrappedConnectionString;

    private PgIntegrationSchema(string connectionString)
    {
        ConnectionString = connectionString;
    }

    public string SchemaName => IntegrationConfig.TestSchemaName;

    public string ConnectionString { get; }

    public static async ValueTask<IIntegrationSchema> CreateAsync()
    {
        if (s_bootstrappedConnectionString is { } cached)
        {
            return new PgIntegrationSchema(cached);
        }

        await s_bootstrapGate.WaitAsync();
        try
        {
            if (s_bootstrappedConnectionString is null)
            {
                s_bootstrappedConnectionString = await BootstrapAsync();
            }

            return new PgIntegrationSchema(s_bootstrappedConnectionString);
        }
        finally
        {
            s_bootstrapGate.Release();
        }
    }

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    private static async Task<string> BootstrapAsync()
    {
        var adminConn = IntegrationConfig.PostgresConnectionString;
        if (string.IsNullOrWhiteSpace(adminConn))
        {
            Assert.Skip("Postgres integration tests require ACTA_TEST_PG.");
        }

        var adminBuilder = new NpgsqlConnectionStringBuilder(adminConn) { Timeout = 15 };

        EnsureTestTarget(adminBuilder.Database ?? string.Empty, IntegrationConfig.TestSchemaName);

        var sessionBuilder = new NpgsqlConnectionStringBuilder(adminBuilder.ConnectionString)
        {
            SearchPath = IntegrationConfig.TestSchemaName,
        };
        var connectionString = sessionBuilder.ConnectionString;

        // Ensure the test database exists (create if missing) and apply the schema, matching the SQL
        // Server fixture; docker-compose only provisions the everyday acta-dev database, not acta-test.
        await PostgresSchemaMigrator.EnsureDatabaseAndApplyAsync(
            adminBuilder.ConnectionString,
            IntegrationConfig.TestSchemaName,
            CancellationToken.None
        );

        await using (var conn = new NpgsqlConnection(adminBuilder.ConnectionString))
        {
            await conn.OpenAsync();
            await UpsertFrameworkNamespaceAsync(conn);
        }

        return connectionString;
    }

    private static async Task UpsertFrameworkNamespaceAsync(NpgsqlConnection conn)
    {
        // The namespaces.id column is GENERATED BY DEFAULT AS IDENTITY; upsert by name.
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = $"""
            INSERT INTO {IntegrationConfig.TestSchemaName}.namespaces
                (name, owner_team, description, catalog_hash, status_code, created_at_utc, modified_at_utc, version)
            VALUES (@name, NULL, NULL, NULL, 10, @now, @now, 0)
            ON CONFLICT (name) DO NOTHING;
            """;
        cmd.Parameters.Add(new NpgsqlParameter("@name", NpgsqlDbType.Varchar) { Value = FrameworkNamespaceName });
        cmd.Parameters.Add(new NpgsqlParameter("@now", NpgsqlDbType.TimestampTz) { Value = DateTime.UtcNow });
        await cmd.ExecuteNonQueryAsync();
    }

    private static void EnsureTestTarget(string databaseName, string schemaName)
    {
        if (
            databaseName.Contains("test", StringComparison.OrdinalIgnoreCase)
            || schemaName.Contains("test", StringComparison.OrdinalIgnoreCase)
        )
        {
            return;
        }

        throw new InvalidOperationException(
            $"Refusing to bootstrap tests against database '{databaseName}' / schema '{schemaName}': "
                + "either the database name or the schema name must contain 'test'."
        );
    }
}
