// <auto-generated />
// Written by tools/Acta.Emit (`schema add` / `schema amend`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's committed baseline migration; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The baseline generation each provider package ships, as recorded in the version-0 row of its
/// baseline migration. A database whose history carries a different value was built from another
/// generation of the schema and is refused at bootstrap.
/// </summary>
internal static class BaselineStamps
{
    internal const string Mssql = "baseline-5605533bc82687ffdf1fbb8dba407507";

    internal const string Pg = "baseline-53d6247cd65f698742252a1902e0a562";

    internal const string Sqlite = "baseline-8b9f74b1c959e09d87eb4193967d0642";

    /// <summary>The stamp for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
