// <auto-generated />
// Written by tools/Acta.Emit (`schema add` / `schema amend`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's committed baseline migration; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The baseline generation each provider package ships, as recorded in the version-0 row of its
/// baseline migration. A database whose history carries a different value was built from another
/// generation of the schema and is refused at bootstrap.
/// </summary>
internal static class BaselineStamps
{
    internal const string Mssql = "baseline-2978ad1ccb8de123488c4581477c134d";

    internal const string Pg = "baseline-e1a1f3207caf5a295743ba88d8c3ca26";

    internal const string Sqlite = "baseline-ae203e66a1801dbadb6af7d799f352b6";

    /// <summary>The stamp for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
