// <auto-generated />
// Written by tools/Acta.Emit (`schema add` / `schema amend`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's committed baseline migration; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The baseline generation each provider package ships, as recorded in the version-0 row of its
/// baseline migration. A database whose history carries a different value was built from another
/// generation of the schema and is refused at bootstrap.
/// </summary>
internal static class BaselineStamps
{
    internal const string Mssql = "baseline-ed807ce13bc157e6553a82f456ccda1a";

    internal const string Pg = "baseline-2fd04b410b15532d2b053472f8a91963";

    internal const string Sqlite = "baseline-6e9cd889410c77ca1498a9666592193e";

    /// <summary>The stamp for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
