// <auto-generated />
// Written by tools/Acta.Emit (`objects record`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's installed views and routines; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The object package each provider package ships, as recorded in the sentinel row its install
/// writes. Identity only: the startup verdict reads the major and revision beside it, never this.
/// </summary>
internal static class ObjectPackageHashes
{
    internal const string Mssql = "e22cec8d66b8808220c8dda74a54fae3";

    internal const string Pg = "97658e4a64a98c152723d537df2c2a9e";

    internal const string Sqlite = "fa7744573f6ec85034943f82b43de4e6";

    /// <summary>The hash for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
