// <auto-generated />
// Written by tools/Acta.Emit (`objects record`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's installed views and routines; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The object package each provider package ships, as recorded in the sentinel row its install
/// writes. Identity only: the startup verdict reads the major and revision beside it, never this.
/// </summary>
internal static class ObjectPackageHashes
{
    internal const string Mssql = "0528bab86105195a00b3e5e74c6106f2";

    internal const string Pg = "a2d5344c4245c74a797c3408f84feb56";

    internal const string Sqlite = "eee0f6cd0cdc17a97048007f2f004bec";

    /// <summary>The hash for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
