// <auto-generated />
// Written by tools/Acta.Emit (`objects record`) and verified by `Acta.Emit check`.
// Each value is a content hash of that provider's installed views and routines; edit the SQL,
// not this file.

namespace Acta.Relational.Schema;

/// <summary>
/// The object package each provider package ships, as recorded in the sentinel row its install
/// writes. Identity only: the startup verdict reads the major and revision beside it, never this.
/// </summary>
internal static class ObjectPackageHashes
{
    internal const string Mssql = "8d3ba3a3699c6b480b36f432d9db15a7";

    internal const string Pg = "170534704a3b1a28e424155df2573736";

    internal const string Sqlite = "eee0f6cd0cdc17a97048007f2f004bec";

    /// <summary>The hash for one dialect, named by the token the provider hooks carry.</summary>
    internal static string ForDialect(string dialectToken) =>
        dialectToken switch
        {
            "mssql" => Mssql,
            "pg" => Pg,
            "sqlite" => Sqlite,
            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, "Unknown dialect token."),
        };
}
