using System.Text;

namespace Acta.Generators.Shared;

/// <summary>
/// Shared text helpers for the three Acta source generators. Kept intentionally small — only what
/// is genuinely duplicated across the schema, code, and job-manifest generators.
/// </summary>
internal static class GeneratorText
{
    /// <summary>
    /// Emit the two-line header every generated file shares: the <c>&lt;auto-generated/&gt;</c>
    /// marker (skips style analyzers / formatters) and <c>#nullable enable</c> (so generated code
    /// participates in NRT without inheriting the consumer's file-level pragma).
    /// </summary>
    public static void AutoGeneratedHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
    }
}
