using Acta.Relational.Schema;

namespace Acta.Relational.Entities;

/// <summary>
/// Service-owned execution boundary. One deployable service owns one <see cref="JobNamespace"/>; replicas
/// of that service share it (on a catalog-hash match the upsert is a no-op). Cross-service collisions fail
/// at startup with <c>JobNamespaceConflictException</c>.
/// </summary>
[DbTable("namespaces")]
[DbPrimaryKey(Name = "pk_namespaces", Columns = ["id"])]
[DbUniqueIndex(Name = "ux_namespaces_name", Columns = ["name"], Usage = "uniqueness")]
internal sealed class JobNamespace : IEntity<int>
{
    /// <summary>
    /// DB-assigned identity (<c>IDENTITY(1,1)</c> on SQL Server, <c>GENERATED BY DEFAULT AS IDENTITY</c>
    /// on Postgres). Referenced by every hot table via <c>namespace_id</c>. Callers never pick the
    /// value; the worker runtime upserts the row by <see cref="Name"/> via the
    /// <c>StartWorker</c> handler (which registers the namespace and the worker in one round trip)
    /// and reads the assigned id back.
    /// </summary>
    [DbColumn("id", DbKind.Int32)]
    public int Id { get; init; }

    /// <summary>
    /// Operator-readable namespace name. Unique. Kebab-case.
    /// </summary>
    [DbColumn("name", DbKind.AsciiString, Size = 128)]
    public string Name { get; init; } = default!;

    /// <summary>
    /// Owning team identifier surfaced on operator dashboards. Unicode-capable.
    /// </summary>
    [DbColumn("owner_team", DbKind.UnicodeString, Size = AdminTextLimits.NamespaceOwnerTeam)]
    public string? OwnerTeam { get; internal set; }

    /// <summary>
    /// Operator-readable description of what this namespace owns. Unicode-capable.
    /// </summary>
    [DbColumn("description", DbKind.UnicodeString, Size = AdminTextLimits.NamespaceDescription)]
    public string? Description { get; internal set; }

    /// <summary>
    /// Namespace lifecycle status. Supplied at INSERT by the StartWorker registration (no server-side
    /// default), mirroring the tenant convention. Enforced at enqueue: EnqueueOne/EnqueueBatch reject
    /// with a distinguishable error when the resolved namespace is not Active.
    /// </summary>
    [DbColumn("status_code")]
    public NamespaceStatusCode Status { get; internal set; }

    /// <summary>
    /// SHA-256 hex of the canonicalized assembly catalog. NULL means the namespace row was created
    /// before any catalog hash was computed (pre-registration; the hash is unwritten).
    /// </summary>
    [DbColumn("catalog_hash", DbKind.AsciiString, Size = 128)]
    public string? CatalogHash { get; internal set; }

    /// <summary>When the namespace row was first created. Set server-side.</summary>
    [DbColumn("created_at_utc", DbKind.UtcInstant, Default = DbDefault.UtcNow)]
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>When the namespace row was last updated. Set server-side on every mutation.</summary>
    [DbColumn("modified_at_utc", DbKind.UtcInstant, Default = DbDefault.UtcNow)]
    public DateTime ModifiedAtUtc { get; set; }

    /// <summary>
    /// Optimistic-concurrency token; SPs manually increment on UPDATE.
    /// </summary>
    [DbColumn("version", DbKind.Int32, Default = DbDefault.Zero)]
    [DbConcurrencyToken]
    public int Version { get; set; }
}
