-- M001_init (pg): full schema baseline generated by Acta.Emit. Hand-edit only as a delta.
-- Schema placeholder `{{schema}}` is substituted by the migration runner at apply time.
-- Routine and view bodies are not baked in: the SQL object installer applies them after migrations.
-- PostgreSQL: snake_case identifiers stay unquoted; DbKind.UtcInstant → timestamptz;
--             DbKind.Byte → smallint + CHECK 0..255; DbKind.BinaryPayload → bytea.

CREATE SCHEMA IF NOT EXISTS {{schema}};

-- JobAlert
CREATE TABLE IF NOT EXISTS {{schema}}.alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alert_ref uuid NOT NULL,
    namespace_id smallint NOT NULL,
    job_id bigint NULL,
    job_ref uuid NULL,
    origin_code smallint NOT NULL,
    severity_code smallint NOT NULL,
    kind_code smallint NOT NULL,
    title varchar(512) NOT NULL,
    message varchar(512) NOT NULL,
    channel_name varchar(128) NOT NULL,
    dedupe_key varchar(512) NULL,
    occurrence_count integer NOT NULL,
    last_projected_event_id bigint NULL,
    resolved_at_utc timestamptz NULL,
    acknowledged_at_utc timestamptz NULL,
    delivery_status_code smallint NOT NULL,
    retry_count smallint NOT NULL,
    retry_after_utc timestamptz NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_alerts PRIMARY KEY (id)
    , CONSTRAINT ck_alerts_job_ref_pair CHECK ((job_id IS NULL AND job_ref IS NULL) OR (job_id IS NOT NULL AND job_ref IS NOT NULL))
    , CONSTRAINT ck_alerts_occurrence_count CHECK (occurrence_count >= 1)
    , CONSTRAINT ck_alerts_origin_code CHECK (origin_code IN (10, 20))
    , CONSTRAINT ck_alerts_severity_code CHECK (severity_code IN (10, 20, 30, 40))
    , CONSTRAINT ck_alerts_delivery_status_code CHECK (delivery_status_code IN (10, 20, 30, 100, 200))
    , CONSTRAINT ck_alerts_retry_count_byte CHECK (retry_count BETWEEN 0 AND 255)
);
CREATE INDEX IF NOT EXISTS ix_alerts_dedupe_identity ON {{schema}}.alerts (namespace_id, dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_alerts_delivery_due ON {{schema}}.alerts (namespace_id, delivery_status_code, retry_after_utc, id);
CREATE INDEX IF NOT EXISTS ix_alerts_namespace_created ON {{schema}}.alerts (namespace_id, created_at_utc DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_alerts_namespace_unresolved ON {{schema}}.alerts (namespace_id, created_at_utc DESC, id DESC) WHERE resolved_at_utc IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_alerts_ref ON {{schema}}.alerts (alert_ref);
CREATE UNIQUE INDEX IF NOT EXISTS ux_alerts_dedupe ON {{schema}}.alerts (namespace_id, dedupe_key) WHERE dedupe_key IS NOT NULL AND resolved_at_utc IS NULL;

-- JobDefinition
CREATE TABLE IF NOT EXISTS {{schema}}.definitions (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    namespace_id smallint NOT NULL,
    name varchar(128) NOT NULL,
    status_code smallint NOT NULL,
    definition_hash varchar(128) NOT NULL,
    manifest_generation_at_utc timestamptz NOT NULL,
    input_type_name varchar(512) NOT NULL,
    input_format_id smallint NOT NULL,
    input_format_name varchar(128) NOT NULL,
    output_type_name varchar(512) NULL,
    output_format_id smallint NOT NULL,
    output_format_name varchar(128) NOT NULL,
    tenant_requirement_code smallint NOT NULL,
    priority_code smallint NOT NULL,
    priority_code_override smallint NULL,
    priority_code_effective smallint GENERATED ALWAYS AS (COALESCE(priority_code_override, priority_code)) STORED,
    max_attempts smallint NOT NULL,
    max_attempts_override smallint NULL,
    max_attempts_effective smallint GENERATED ALWAYS AS (COALESCE(max_attempts_override, max_attempts)) STORED,
    backoff varchar(64) NOT NULL,
    backoff_override varchar(64) NULL,
    backoff_effective varchar(64) GENERATED ALWAYS AS (COALESCE(backoff_override, backoff)) STORED,
    execution_timeout_seconds integer NOT NULL,
    execution_timeout_seconds_override integer NULL,
    execution_timeout_seconds_effective integer GENERATED ALWAYS AS (COALESCE(execution_timeout_seconds_override, execution_timeout_seconds)) STORED,
    deadline_seconds integer NOT NULL,
    deadline_seconds_override integer NULL,
    deadline_seconds_effective integer GENERATED ALWAYS AS (COALESCE(deadline_seconds_override, deadline_seconds)) STORED,
    deadline_behavior_code smallint NOT NULL,
    deadline_behavior_code_override smallint NULL,
    deadline_behavior_code_effective smallint GENERATED ALWAYS AS (COALESCE(deadline_behavior_code_override, deadline_behavior_code)) STORED,
    retention_seconds integer NOT NULL,
    retention_seconds_override integer NULL,
    retention_seconds_effective integer GENERATED ALWAYS AS (COALESCE(retention_seconds_override, retention_seconds)) STORED,
    audit_level_code smallint NOT NULL,
    audit_level_code_override smallint NULL,
    audit_level_code_effective smallint GENERATED ALWAYS AS (COALESCE(audit_level_code_override, audit_level_code)) STORED,
    alert_profile_code smallint NOT NULL,
    alert_profile_code_override smallint NULL,
    alert_profile_code_effective smallint GENERATED ALWAYS AS (COALESCE(alert_profile_code_override, alert_profile_code)) STORED,
    alert_channel_name varchar(128) NULL,
    alert_channel_name_override varchar(128) NULL,
    alert_channel_name_effective varchar(128) GENERATED ALWAYS AS (COALESCE(alert_channel_name_override, alert_channel_name)) STORED,
    runbook_url varchar(512) NULL,
    runbook_url_override varchar(512) NULL,
    runbook_url_effective varchar(512) GENERATED ALWAYS AS (COALESCE(runbook_url_override, runbook_url)) STORED,
    display_name varchar(128) NULL,
    display_name_override varchar(128) NULL,
    display_name_effective varchar(128) GENERATED ALWAYS AS (COALESCE(display_name_override, display_name)) STORED,
    description varchar(512) NULL,
    description_override varchar(512) NULL,
    description_effective varchar(512) GENERATED ALWAYS AS (COALESCE(description_override, description)) STORED,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_definitions PRIMARY KEY (id)
    , CONSTRAINT ck_definitions_max_attempts CHECK (max_attempts >= 1)
    , CONSTRAINT ck_definitions_max_attempts_override CHECK (max_attempts_override IS NULL OR max_attempts_override >= 1)
    , CONSTRAINT ck_definitions_execution_timeout CHECK (execution_timeout_seconds > 0)
    , CONSTRAINT ck_definitions_execution_timeout_override CHECK (execution_timeout_seconds_override IS NULL OR execution_timeout_seconds_override > 0)
    , CONSTRAINT ck_definitions_deadline CHECK (deadline_seconds >= 0)
    , CONSTRAINT ck_definitions_deadline_override CHECK (deadline_seconds_override IS NULL OR deadline_seconds_override >= 0)
    , CONSTRAINT ck_definitions_retention CHECK (retention_seconds >= 0)
    , CONSTRAINT ck_definitions_retention_override CHECK (retention_seconds_override IS NULL OR retention_seconds_override >= 0)
    , CONSTRAINT ck_definitions_status_code CHECK (status_code IN (10, 240))
    , CONSTRAINT ck_definitions_tenant_requirement_code CHECK (tenant_requirement_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_priority_code_override CHECK (priority_code_override IS NULL OR priority_code_override IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_deadline_behavior_code CHECK (deadline_behavior_code IN (10, 20))
    , CONSTRAINT ck_definitions_deadline_behavior_code_override CHECK (deadline_behavior_code_override IS NULL OR deadline_behavior_code_override IN (10, 20))
    , CONSTRAINT ck_definitions_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_audit_level_code_override CHECK (audit_level_code_override IS NULL OR audit_level_code_override IN (0, 10, 20))
    , CONSTRAINT ck_definitions_alert_profile_code CHECK (alert_profile_code IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_alert_profile_code_override CHECK (alert_profile_code_override IS NULL OR alert_profile_code_override IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
    , CONSTRAINT ck_definitions_output_format_id_byte CHECK (output_format_id BETWEEN 0 AND 255)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_definitions_namespace_name ON {{schema}}.definitions (namespace_id, name);

-- JobEvent
CREATE TABLE IF NOT EXISTS {{schema}}.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_code smallint NOT NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    namespace_id smallint NOT NULL,
    actor_code smallint NOT NULL,
    actor_key varchar(128) NULL,
    job_id bigint NULL,
    job_ref uuid NULL,
    execution_number integer NULL,
    lineage_root_id bigint NULL,
    definition_id integer NULL,
    tenant_id integer NULL,
    worker_id integer NULL,
    from_status_code smallint NULL,
    to_status_code smallint NULL,
    execution_status_code smallint NULL,
    duration_ms integer NULL,
    reason_code smallint NULL,
    reason_message varchar(512) NULL,
    detail_format_id smallint DEFAULT 0 NOT NULL,
    detail bytea NULL
    , CONSTRAINT pk_events PRIMARY KEY (id)
    , CONSTRAINT ck_events_detail_pair CHECK ((detail_format_id = 0 AND detail IS NULL) OR (detail_format_id <> 0 AND detail IS NOT NULL))
    , CONSTRAINT ck_events_actor_code CHECK (actor_code IN (10, 20, 50, 70))
    , CONSTRAINT ck_events_from_status_code CHECK (from_status_code IS NULL OR from_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_to_status_code CHECK (to_status_code IS NULL OR to_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_execution_status_code CHECK (execution_status_code IS NULL OR execution_status_code IN (50, 100, 150, 151, 152, 200, 220, 230))
    , CONSTRAINT ck_events_detail_format_id_byte CHECK (detail_format_id BETWEEN 0 AND 255)
);
CREATE INDEX IF NOT EXISTS ix_events_lineage_timeline ON {{schema}}.events (lineage_root_id, created_at_utc, id) WHERE lineage_root_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_namespace_timeline ON {{schema}}.events (namespace_id, event_code, created_at_utc, id);
CREATE INDEX IF NOT EXISTS ix_events_job_timeline ON {{schema}}.events (job_id, created_at_utc, id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_events_namespace_created ON {{schema}}.events (namespace_id, created_at_utc DESC, id DESC);

-- Job
CREATE TABLE IF NOT EXISTS {{schema}}.jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_ref uuid NOT NULL,
    namespace_id smallint NOT NULL,
    definition_id integer NOT NULL,
    lineage_root_id bigint NULL,
    parent_id bigint NULL,
    tenant_id integer NULL,
    deduplication_key varchar(128) NULL,
    correlation_key varchar(64) NULL,
    exclusive_key varchar(128) NULL,
    input_format_id smallint NOT NULL,
    input bytea NULL,
    audit_level_code smallint NOT NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL
    , CONSTRAINT pk_jobs PRIMARY KEY (id)
    , CONSTRAINT ck_jobs_input_pair CHECK ((input_format_id = 0 AND input IS NULL) OR (input_format_id <> 0 AND input IS NOT NULL))
    , CONSTRAINT ck_jobs_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_jobs_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
);
CREATE INDEX IF NOT EXISTS ix_jobs_parent ON {{schema}}.jobs (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_jobs_namespace_created ON {{schema}}.jobs (namespace_id, created_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_ref ON {{schema}}.jobs (job_ref);
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_deduplication_key_root ON {{schema}}.jobs (namespace_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_deduplication_key_child ON {{schema}}.jobs (parent_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NOT NULL;

-- Lock
CREATE TABLE IF NOT EXISTS {{schema}}.locks (
    lock_key varchar(256) NOT NULL,
    job_id bigint NOT NULL,
    expires_at_utc timestamptz NOT NULL,
    hold_token uuid NOT NULL
    , CONSTRAINT pk_locks PRIMARY KEY (lock_key)
);
CREATE INDEX IF NOT EXISTS ix_locks_reclaim_expired ON {{schema}}.locks (expires_at_utc);

-- JobNamespace
CREATE TABLE IF NOT EXISTS {{schema}}.namespaces (
    id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(128) NOT NULL,
    owner_team varchar(512) NULL,
    description varchar(512) NULL,
    status_code smallint NOT NULL,
    catalog_hash varchar(128) NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_namespaces PRIMARY KEY (id)
    , CONSTRAINT ck_namespaces_status_code CHECK (status_code IN (10, 20))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_namespaces_name ON {{schema}}.namespaces (name);

-- Seed: reserved system namespace (id=1, 'sys') for cross-namespace audit events. Collation-neutral.
INSERT INTO {{schema}}.namespaces (id, name, status_code, description, created_at_utc, modified_at_utc)
VALUES (1, 'sys', 10, 'Reserved system namespace for cross-namespace audit events.', now(), now())
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('{{schema}}.namespaces', 'id'), GREATEST(1, (SELECT MAX(id) FROM {{schema}}.namespaces)));

-- JobResult
CREATE TABLE IF NOT EXISTS {{schema}}.results (
    job_id bigint NOT NULL,
    execution_number integer NOT NULL,
    result_format_id smallint NOT NULL,
    result bytea NOT NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL
    , CONSTRAINT pk_results PRIMARY KEY (job_id, execution_number)
    , CONSTRAINT ck_results_format_not_none CHECK (result_format_id <> 0)
    , CONSTRAINT ck_results_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_results_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);

-- JobRuntime
CREATE TABLE IF NOT EXISTS {{schema}}.runtimes (
    job_id bigint NOT NULL,
    namespace_id smallint NOT NULL,
    status_code smallint NOT NULL,
    priority_code smallint NOT NULL,
    next_run_at_utc timestamptz NULL,
    execution_number integer NOT NULL,
    failure_count smallint NOT NULL,
    leased_by_worker_id integer NULL,
    lease_expires_at_utc timestamptz NULL,
    retention_until_utc timestamptz NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_runtimes PRIMARY KEY (job_id)
    , CONSTRAINT ck_runtimes_lease_consistency CHECK ((leased_by_worker_id IS NULL AND lease_expires_at_utc IS NULL) OR (leased_by_worker_id IS NOT NULL AND lease_expires_at_utc IS NOT NULL))
    , CONSTRAINT ck_runtimes_counters CHECK (execution_number >= 0 AND failure_count >= 0)
    , CONSTRAINT ck_runtimes_status_code CHECK (status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_runtimes_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT fk_runtimes_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_runtimes_claim_ready ON {{schema}}.runtimes (namespace_id, priority_code DESC, next_run_at_utc, job_id) WHERE status_code IN (10, 20);
CREATE INDEX IF NOT EXISTS ix_runtimes_retention ON {{schema}}.runtimes (namespace_id, retention_until_utc, job_id) WHERE retention_until_utc IS NOT NULL AND status_code IN (100, 200, 220);
CREATE INDEX IF NOT EXISTS ix_runtimes_worker_inflight ON {{schema}}.runtimes (leased_by_worker_id, status_code) WHERE leased_by_worker_id IS NOT NULL AND status_code IN (40, 50);

-- JobSchedule
CREATE TABLE IF NOT EXISTS {{schema}}.schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    namespace_id smallint NOT NULL,
    job_id bigint NOT NULL,
    definition_id integer NOT NULL,
    name varchar(128) NOT NULL,
    origin_code smallint NOT NULL,
    expression varchar(128) NOT NULL,
    expression_override varchar(128) NULL,
    expression_effective varchar(128) GENERATED ALWAYS AS (COALESCE(expression_override, expression)) STORED,
    time_zone_id varchar(128) NOT NULL,
    time_zone_id_override varchar(128) NULL,
    time_zone_id_effective varchar(128) GENERATED ALWAYS AS (COALESCE(time_zone_id_override, time_zone_id)) STORED,
    expression_kind_code smallint NOT NULL,
    misfire_strategy_code smallint NOT NULL,
    next_run_at_utc timestamptz NULL,
    last_occurrence_at_utc timestamptz NULL,
    status_code smallint NOT NULL,
    paused_until_utc timestamptz NULL,
    description varchar(512) NULL,
    reason_message varchar(512) NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_schedules PRIMARY KEY (id)
    , CONSTRAINT ck_schedules_paused_pair CHECK (status_code = 30 OR paused_until_utc IS NULL)
    , CONSTRAINT ck_schedules_orphan_origin CHECK (origin_code = 40 OR status_code <> 230)
    , CONSTRAINT ck_schedules_origin_code CHECK (origin_code IN (20, 40))
    , CONSTRAINT ck_schedules_expression_kind_code CHECK (expression_kind_code IN (10, 20))
    , CONSTRAINT ck_schedules_misfire_strategy_code CHECK (misfire_strategy_code IN (10, 20))
    , CONSTRAINT ck_schedules_status_code CHECK (status_code IN (10, 30, 230))
    , CONSTRAINT fk_schedules_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
    , CONSTRAINT fk_schedules_definitions FOREIGN KEY (definition_id) REFERENCES {{schema}}.definitions (id)
);
CREATE INDEX IF NOT EXISTS ix_schedules_namespace_next ON {{schema}}.schedules (namespace_id, next_run_at_utc, id) WHERE status_code <> 230;
CREATE UNIQUE INDEX IF NOT EXISTS ux_schedules_job_name ON {{schema}}.schedules (job_id, name);

-- Setting
CREATE TABLE IF NOT EXISTS {{schema}}.settings (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scope_code smallint NOT NULL,
    scope_id integer NULL,
    name varchar(128) NOT NULL,
    value_format_id smallint NOT NULL,
    value bytea NULL,
    description varchar(512) NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_settings PRIMARY KEY (id)
    , CONSTRAINT ck_settings_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_settings_scope_code CHECK (scope_code IN (10, 30, 40))
    , CONSTRAINT ck_settings_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_settings_scope_name ON {{schema}}.settings (scope_code, scope_id, name) WHERE scope_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_settings_global_name ON {{schema}}.settings (scope_code, name) WHERE scope_id IS NULL;

-- JobStep
CREATE TABLE IF NOT EXISTS {{schema}}.steps (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    status_code smallint NOT NULL,
    attempt_number smallint NOT NULL,
    next_retry_at_utc timestamptz NULL,
    reason_code smallint NULL,
    reason_message varchar(512) NULL,
    result_format_id smallint NOT NULL,
    result bytea NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_steps PRIMARY KEY (id)
    , CONSTRAINT ck_steps_result_pair CHECK ((result_format_id = 0 AND result IS NULL) OR (result_format_id <> 0 AND result IS NOT NULL))
    , CONSTRAINT ck_steps_attempt_number CHECK (attempt_number >= 1)
    , CONSTRAINT ck_steps_status_code CHECK (status_code IN (10, 100, 200, 230))
    , CONSTRAINT ck_steps_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_steps_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_steps_job_name ON {{schema}}.steps (job_id, name);

-- Tag
CREATE TABLE IF NOT EXISTS {{schema}}.tags (
    scope_code smallint NOT NULL,
    scope_id bigint NOT NULL,
    namespace_id smallint NULL,
    name varchar(128) NOT NULL,
    value varchar(128) NULL,
    value_search varchar(128) NULL
    , CONSTRAINT pk_tags PRIMARY KEY (scope_code, scope_id, name)
    , CONSTRAINT ck_tags_scope_id CHECK (scope_id > 0)
    , CONSTRAINT ck_tags_namespace_id CHECK (namespace_id IS NULL OR namespace_id > 0)
    , CONSTRAINT ck_tags_scope_namespace CHECK ((scope_code = 20 AND namespace_id IS NULL) OR (scope_code = 30 AND namespace_id IS NOT NULL AND scope_id = namespace_id) OR (scope_code IN (40, 50, 60, 70, 80, 90) AND namespace_id IS NOT NULL))
    , CONSTRAINT ck_tags_value_search CHECK ((value IS NULL AND value_search IS NULL) OR (value IS NOT NULL AND value_search IS NOT NULL))
    , CONSTRAINT ck_tags_scope_code CHECK (scope_code IN (20, 30, 40, 50, 60, 70, 80, 90))
);
CREATE INDEX IF NOT EXISTS ix_tags_namespace_name_value_search ON {{schema}}.tags (namespace_id, name, value_search, scope_code, scope_id);

-- Tenant
CREATE TABLE IF NOT EXISTS {{schema}}.tenants (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_key varchar(128) NOT NULL,
    status_code smallint NOT NULL,
    display_name varchar(128) NULL,
    description varchar(512) NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_tenants PRIMARY KEY (id)
    , CONSTRAINT ck_tenants_status_code CHECK (status_code IN (10, 20))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tenants_key ON {{schema}}.tenants (tenant_key);

-- JobWorker
CREATE TABLE IF NOT EXISTS {{schema}}.workers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    worker_ref uuid NOT NULL,
    namespace_id smallint NOT NULL,
    status_code smallint NOT NULL,
    deployment_version varchar(128) NOT NULL,
    host varchar(256) NOT NULL,
    engine_version varchar(128) NULL,
    dotnet_version varchar(64) NULL,
    process_id integer NULL,
    max_concurrency integer NOT NULL,
    last_seen_at_utc timestamptz NOT NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_workers PRIMARY KEY (id)
    , CONSTRAINT ck_workers_max_concurrency CHECK (max_concurrency > 0)
    , CONSTRAINT ck_workers_status_code CHECK (status_code IN (10, 80, 100, 200))
    , CONSTRAINT fk_workers_namespaces FOREIGN KEY (namespace_id) REFERENCES {{schema}}.namespaces (id)
);
CREATE INDEX IF NOT EXISTS ix_workers_namespace_status_last_seen ON {{schema}}.workers (namespace_id, status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS ix_workers_status_last_seen ON {{schema}}.workers (status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS ix_workers_namespace_last_seen ON {{schema}}.workers (namespace_id, last_seen_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_workers_ref ON {{schema}}.workers (worker_ref);

-- JobCheckpoint
CREATE TABLE IF NOT EXISTS {{schema}}.checkpoints (
    job_id bigint NOT NULL,
    kind_code smallint NOT NULL,
    name varchar(128) NOT NULL,
    status_code smallint NULL,
    due_at_utc timestamptz NULL,
    value_format_id smallint DEFAULT 0 NOT NULL,
    value bytea NULL,
    created_at_utc timestamptz DEFAULT now() NOT NULL,
    modified_at_utc timestamptz DEFAULT now() NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_checkpoints PRIMARY KEY (job_id, kind_code, name)
    , CONSTRAINT ck_checkpoints_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_checkpoints_kind_code CHECK (kind_code IN (10, 20, 30, 40, 50))
    , CONSTRAINT ck_checkpoints_status_code CHECK (status_code IS NULL OR status_code IN (10, 20, 30, 100))
    , CONSTRAINT ck_checkpoints_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_checkpoints_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);


INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (0, 'init-entity-refs-v1', '{{schema}}')
ON CONFLICT (version) DO NOTHING;
INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (1, 'init', '{{schema}}')
ON CONFLICT (version) DO NOTHING;
