using System.Globalization;
using System.Text;
using Acta.Emit.Shared.Model;
using Acta.Relational.Schema;

namespace Acta.Emit.Shared.Sql;

internal sealed class PostgresDdlDialect : SqlDdlDialect
{
    public override string ProviderToolName => "pg";

    public override IReadOnlyList<string> HeaderExtraLines =>
        [
            "-- PostgreSQL: snake_case identifiers stay unquoted; DbKind.UtcInstant → timestamptz;",
            "--             DbKind.Byte → smallint + CHECK 0..255; DbKind.BinaryPayload → bytea.",
        ];

    public override string CreateSchemaStatement => $"CREATE SCHEMA IF NOT EXISTS {SchemaPlaceholder};";

    public override string? Terminator => null;

    public override string? TableGuardBegin(string tableName) => null;

    public override string? TableGuardEnd => null;

    public override string CreateTableClause => "CREATE TABLE IF NOT EXISTS";

    public override string CreateIndexClause(bool unique) => unique ? "CREATE UNIQUE INDEX IF NOT EXISTS" : "CREATE INDEX IF NOT EXISTS";

    // Postgres requires the declared type before GENERATED ALWAYS AS; STORED is the only supported form.
    public override string RenderGeneratedColumn(ColumnModel c) => $"{c.Name} {RenderType(c)} GENERATED ALWAYS AS ({c.Generated}) STORED";

    public override string RenderType(ColumnModel c) =>
        c.Kind switch
        {
            DbKind.Boolean => "boolean",
            DbKind.Byte => "smallint",
            DbKind.Int16 => "smallint",
            DbKind.Int32 => "integer",
            DbKind.Int64 => "bigint",
            DbKind.Guid => "uuid",
            DbKind.UtcInstant => "timestamptz",
            DbKind.Decimal => $"numeric({c.Precision}, {c.Scale})",
            DbKind.AsciiString => c.Size <= 0 ? "text" : $"varchar({c.Size})",
            DbKind.UnicodeString => c.Size <= 0 ? "text" : $"varchar({c.Size})",
            DbKind.Bytes => c.Size > 0
                ? "bytea"
                : throw new InvalidOperationException(
                    $"DbKind.Bytes on {c.Property.DeclaringType?.Name}.{c.Property.Name} requires Size > 0; use DbKind.BinaryPayload for unbounded."
                ),
            DbKind.BinaryPayload => "bytea",
            _ => throw new InvalidOperationException($"Unhandled DbKind {c.Kind} on {c.Property.DeclaringType?.Name}.{c.Property.Name}"),
        };

    public override string RenderDefault(DbDefault d, ColumnModel c) =>
        d switch
        {
            DbDefault.None => "",
            DbDefault.UtcNow => " DEFAULT now()",
            DbDefault.Zero => " DEFAULT 0",
            DbDefault.EmptyString => " DEFAULT ''",
            DbDefault.NewGuid => " DEFAULT gen_random_uuid()",
            _ => throw new InvalidOperationException($"Unhandled DbDefault {d} on {c.Property.DeclaringType?.Name}.{c.Property.Name}"),
        };

    public override string? PostTableSeed(string tableName) =>
        tableName == "namespaces"
            ? "-- Seed: reserved system namespace (id=1, 'sys') for cross-namespace audit events. Collation-neutral.\n"
                + $"INSERT INTO {SchemaPlaceholder}.namespaces (id, name, status_code, description, created_at_utc, modified_at_utc)\n"
                + $"VALUES (1, 'sys', {(byte)JobNamespaceStatusCode.Active}, 'Reserved system namespace for cross-namespace audit events.', now(), now())\n"
                + "ON CONFLICT (id) DO NOTHING;\n"
                + $"SELECT setval(pg_get_serial_sequence('{SchemaPlaceholder}.namespaces', 'id'), GREATEST(1, (SELECT MAX(id) FROM {SchemaPlaceholder}.namespaces)));"
            : null;

    public override string RenderIdentity() => " GENERATED BY DEFAULT AS IDENTITY";

    // Postgres has no table-level compression (TOAST handles large values) and no sequential-key
    // index hint, so both storage opt-ins render nothing here.
    public override string TableTrailingOptions(EntityModel e) => "";

    public override string PrimaryKeyTrailingOptions(DbPrimaryKeySpec pk) => "";

    public override void EmitProviderColumnChecks(StringBuilder sb, EntityModel e)
    {
        // Postgres has no tinyint; emit a range CHECK 0..255 for every plain Byte column so out-of-range
        // ids fail at the DB layer. Coded (enum-backed) byte columns are excluded: their enum IN (...)
        // CHECK already constrains the value, so a byte-range CHECK would be redundant.
        foreach (var c in e.Columns.Where(c => c.Kind == DbKind.Byte && !c.IsCoded))
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    , CONSTRAINT ck_{e.TableName}_{c.Name}_byte CHECK ({c.Name} BETWEEN 0 AND 255)"
            );
        }

        // Postgres bytea is unbounded; enforce the declared Size via octet_length per column.
        foreach (var c in e.Columns.Where(c => c.Kind == DbKind.Bytes))
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    , CONSTRAINT ck_{e.TableName}_{c.Name}_bytes CHECK (octet_length({c.Name}) <= {c.Size})"
            );
        }
    }

    public override string MigrationStamp(int version, string name) =>
        $"INSERT INTO {SchemaPlaceholder}.migrations (version, name, installed_schema)\n"
        + $"VALUES ({version}, '{PersistedMigrationName(version, name)}', '{SchemaPlaceholder}')\n"
        + "ON CONFLICT (version) DO NOTHING;";
}
