using System.Globalization;
using System.Text;
using Acta.Emit.Shared.Model;
using Acta.Relational.Schema;

namespace Acta.Emit.Shared.Sql;

/// <summary>
/// Single-walker DDL emitter: provider-specific choices delegate to a <see cref="SqlDdlDialect"/>.
/// The emitted MNNN script is self-contained and idempotent: schema, tables, indexes,
/// provider types, and its own migrations stamp. Provider-owned routine and view bodies are installed separately.
/// </summary>
internal static class SqlSchemaEmitter
{
    // Renders the durable schema (tables, indexes, and provider types) as a single migration
    // stamped at <paramref name="version"/>/<paramref name="name"/>. Serves the genesis baseline
    // (version 1, "init") and a late-joining provider's first migration (current version, "init").
    public static string EmitFullSchema(SchemaModel model, SqlDdlDialect dialect, int version, string name)
    {
        var sb = new StringBuilder();

        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"-- M{version:D3}_{name} ({dialect.ProviderToolName}): full schema baseline generated by Acta.Emit. Hand-edit only as a delta."
        );
        sb.AppendLine("-- Schema placeholder `{{schema}}` is substituted by the migration runner at apply time.");
        sb.AppendLine("-- Routine and view bodies are not baked in: the SQL object installer applies them after migrations.");
        foreach (var line in dialect.HeaderExtraLines)
        {
            sb.AppendLine(line);
        }
        sb.AppendLine();

        sb.AppendLine(dialect.CreateSchemaStatement);
        AppendTerminator(sb, dialect);
        sb.AppendLine();

        // Table-name order, deferring any table whose inline-FK target has not been emitted yet
        // (e.g. checkpoints sorts before its FK parent jobs). Stable: non-deferred tables keep
        // their alphabetical position; a deferred table lands right after its parent.
        var emittedTables = new HashSet<string>(StringComparer.Ordinal);
        var pending = new List<EntityModel>(model.Entities);
        while (pending.Count > 0)
        {
            var emittedThisPass = false;
            for (var i = 0; i < pending.Count; )
            {
                var entity = pending[i];
                if (entity.ForeignKeys.Any(fk => !emittedTables.Contains(ResolveTableName(fk.Target))))
                {
                    i++;
                    continue;
                }
                EmitTable(sb, entity, dialect, emittedTables);
                sb.AppendLine();
                pending.RemoveAt(i);
                emittedThisPass = true;
            }
            if (!emittedThisPass)
            {
                throw new InvalidOperationException(
                    "Inline-FK dependency cycle among tables: " + string.Join(", ", pending.Select(p => p.TableName))
                );
            }
        }

        // Request-shape table types (TVPs) consumed by hot-path routines: a dialect literal, not part
        // of the entity model (so they don't pollute the data-model docs). MSSQL only; Postgres null.
        if (dialect.TrailingTypeDefinitions is { } typeDefs)
        {
            sb.AppendLine(typeDefs);
            sb.AppendLine();
        }

        sb.AppendLine();
        sb.AppendLine(dialect.MigrationStamp(version, name));
        AppendTerminator(sb, dialect);

        return sb.ToString();
    }

    // Renders a full CREATE TABLE for a migration draft. Seeds the emitted-tables set with every live
    // table so inline FKs to already-existing tables pass the dependency-order guard.
    internal static string RenderCreateTableForDraft(EntityModel entity, SqlDdlDialect dialect, SchemaModel live)
    {
        var sb = new StringBuilder();
        var allTables = new HashSet<string>(live.Entities.Select(e => e.TableName), StringComparer.Ordinal);
        EmitTable(sb, entity, dialect, allTables);
        return sb.ToString().TrimEnd();
    }

    private static void EmitTable(StringBuilder sb, EntityModel e, SqlDdlDialect dialect, HashSet<string> emittedTables)
    {
        emittedTables.Add(e.TableName);

        sb.AppendLine(CultureInfo.InvariantCulture, $"-- {e.ClrType.Name}");
        if (dialect.TableGuardBegin(e.TableName) is { } guardBegin)
        {
            sb.AppendLine(guardBegin);
        }
        sb.AppendLine(CultureInfo.InvariantCulture, $"{dialect.CreateTableClause} {SqlDdlDialect.SchemaPlaceholder}.{e.TableName} (");

        var colDefs = e.Columns.Select(c => RenderColumn(c, dialect)).ToList();
        for (var i = 0; i < colDefs.Count; i++)
        {
            var comma = i < colDefs.Count - 1 ? "," : "";
            sb.AppendLine(CultureInfo.InvariantCulture, $"    {colDefs[i]}{comma}");
        }

        // A sole integer PK is folded into the column itself on inline-PK dialects (SQLite rowid
        // alias); the separate table-level constraint is then redundant and would create a second
        // index, so it is skipped.
        if (!PkRenderedInline(e, dialect))
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    , CONSTRAINT {e.PrimaryKey.Name} PRIMARY KEY ({string.Join(", ", e.PrimaryKey.Columns)}){dialect.PrimaryKeyTrailingOptions(e.PrimaryKey)}"
            );
        }

        foreach (var chk in e.Checks)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"    , CONSTRAINT {chk.Name} CHECK ({chk.Sql})");
        }

        // Per-coded-column IN-list CHECK: invalid enum ids fail at the DB layer, not just in C#.
        // Constraint name dedupes the `_code` suffix if the column already carries a `_code` segment (the
        // Acta column convention for code-bearing columns, including `{base}_code_override` shapes);
        // avoids `_code_code` doubling and the `_code_override_code` stutter alike.
        // Skipped for extensible families (the point of Extensible is that new members need no
        // migration) and for generated columns whose every source column already carries the CHECK
        // (COALESCE cannot leave a set both inputs are constrained to).
        foreach (var c in e.Columns.Where(c => c.IsCoded && !c.IsExtensible && !IsImpliedBySources(c, e)))
        {
            var values = EnumValueList(c);
            if (values is null)
            {
                continue;
            }
            var predicate = c.IsNullable ? $"{c.Name} IS NULL OR {c.Name} IN ({values})" : $"{c.Name} IN ({values})";
            var suffix = c.Name.Contains("_code", StringComparison.Ordinal) ? "" : "_code";
            sb.AppendLine(CultureInfo.InvariantCulture, $"    , CONSTRAINT ck_{e.TableName}_{c.Name}{suffix} CHECK ({predicate})");
        }

        // Provider-specific extras (Postgres byte range / bytea octet_length CHECKs).
        dialect.EmitProviderColumnChecks(sb, e);

        // FKs are table-level constraints (not post-CREATE ALTERs) so the whole table block stays
        // idempotent; that requires the target table to be emitted first.
        foreach (var fk in e.ForeignKeys)
        {
            var targetTable = ResolveTableName(fk.Target);
            if (!emittedTables.Contains(targetTable))
            {
                throw new InvalidOperationException(
                    $"FK {fk.Name} on {e.TableName} references {targetTable}, which is not emitted yet; inline FKs require dependency order in SchemaModel.Entities."
                );
            }
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    , CONSTRAINT {fk.Name} FOREIGN KEY ({fk.Column}) REFERENCES {dialect.ForeignKeyTargetTable(targetTable)} ({fk.TargetColumn}){RenderOnDelete(fk.OnDelete)}"
            );
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"){dialect.TableTrailingOptions(e)};");

        foreach (var idx in e.Indexes)
        {
            EmitIndex(sb, e.TableName, idx, dialect);
        }

        if (dialect.TableGuardEnd is { } guardEnd)
        {
            sb.AppendLine(guardEnd);
        }

        AppendTerminator(sb, dialect);

        // Bootstrap rows for this table (only namespaces seeds the reserved 'sys' row), emitted as
        // their own terminated block so a reset regenerates them instead of losing a hand-edit.
        if (dialect.PostTableSeed(e.TableName) is { } seed)
        {
            sb.AppendLine();
            foreach (var line in seed.Split('\n'))
            {
                sb.AppendLine(line.TrimEnd('\r'));
            }
            AppendTerminator(sb, dialect);
        }
    }

    private static void EmitIndex(StringBuilder sb, string tableName, DbIndexSpec idx, SqlDdlDialect dialect) =>
        sb.AppendLine(RenderIndex(tableName, idx, dialect));

    // Renders one standalone CREATE [UNIQUE] INDEX statement. Shared by M001 emission and
    // draft so an added index drafts exactly as M001 would render it.
    internal static string RenderIndex(string tableName, DbIndexSpec idx, SqlDdlDialect dialect)
    {
        var cols = string.Join(", ", idx.Columns.Select(c => idx.Descending?.Contains(c) == true ? $"{c} DESC" : c));
        var includes =
            dialect.SupportsIndexInclude && idx.Includes is { Count: > 0 } ? $" INCLUDE ({string.Join(", ", idx.Includes)})" : "";
        var filter = idx.Filter is null ? "" : $" WHERE {idx.Filter}";
        return $"{dialect.CreateIndexClause(idx.IsUnique)} {dialect.IndexNameAndTable(idx.Name, tableName)} ({cols}){includes}{filter};";
    }

    // True when this entity's primary key is a sole integer PK that the dialect folds inline on the
    // column (SQLite rowid alias). The same predicate drives both the column rendering and the
    // table-level constraint skip so they stay in lockstep.
    private static bool PkRenderedInline(EntityModel e, SqlDdlDialect dialect)
    {
        if (!dialect.InlineIntegerPrimaryKey || e.PrimaryKey.Columns.Count != 1)
        {
            return false;
        }
        var col = e.Columns.FirstOrDefault(c => c.Name == e.PrimaryKey.Columns[0]);
        return col is not null && col.IsSolePrimaryKey && !col.IsManualPrimaryKey && IsIdentityEligible(col.Kind);
    }

    internal static string RenderColumn(ColumnModel c, SqlDdlDialect dialect)
    {
        if (c.IsGenerated)
        {
            return dialect.RenderGeneratedColumn(c);
        }

        if (dialect.InlineIntegerPrimaryKey && c.IsSolePrimaryKey && !c.IsManualPrimaryKey && IsIdentityEligible(c.Kind))
        {
            // SQLite rowid alias with AUTOINCREMENT: keep provider parity with SQL Server/Postgres
            // identities by never reusing ids after retention deletes a highest row.
            return $"{c.Name} integer PRIMARY KEY AUTOINCREMENT";
        }

        var typeSql = dialect.RenderType(c);
        var nullable = c.IsNullable ? "NULL" : "NOT NULL";
        var allocation = RenderAllocation(c, dialect);
        // DbDefault renders only when no allocation-default already occupies the slot.
        // The generator's ACTA0403 catches the conflicting combinations at compile time.
        var defaultClause = allocation.Length == 0 ? dialect.RenderDefault(c.Default, c) : "";
        return $"{c.Name} {typeSql}{allocation}{defaultClause} {nullable}";
    }

    // Provider-native PK allocation. Order of precedence:
    //   1. sole single-column integer PK + no Manual → identity clause
    //   2. otherwise → no default
    private static string RenderAllocation(ColumnModel c, SqlDdlDialect dialect)
    {
        return c.IsSolePrimaryKey && !c.IsManualPrimaryKey && IsIdentityEligible(c.Kind) ? dialect.RenderIdentity() : "";
    }

    private static bool IsIdentityEligible(DbKind kind) => kind is DbKind.Byte or DbKind.Int16 or DbKind.Int32 or DbKind.Int64;

    // Sorted, comma-separated underlying-int values of the enum backing this coded column.
    // Returns null for columns whose property type isn't an enum (non-coded columns). Shared with
    // SchemaSnapshot so the committed snapshot records the CHECK value list as the drift signal.
    internal static string? EnumValueList(ColumnModel c)
    {
        var t = c.Property.PropertyType;
        var underlying = Nullable.GetUnderlyingType(t) ?? t;
        if (!underlying.IsEnum)
        {
            return null;
        }

        var values = Enum.GetValues(underlying).Cast<object>().Select(Convert.ToInt64).OrderBy(v => v);
        return string.Join(", ", values);
    }

    /// <summary>
    /// <c>true</c> when a generated column's IN-list CHECK would be redundant. Recognizes exactly the
    /// override triple - <c>x_effective = COALESCE(x_override, x)</c> over two sibling columns of the
    /// same code family, each already carrying its own CHECK - because COALESCE only ever returns one
    /// of its arguments. Deliberately narrow: any other expression may compute a value outside the set
    /// its inputs are constrained to, so it keeps its CHECK.
    /// </summary>
    private static bool IsImpliedBySources(ColumnModel c, EntityModel e)
    {
        if (!c.IsGenerated || c.Generated is not { } expr || !expr.TrimStart().StartsWith("COALESCE(", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var sources = e.Columns.Where(s => !ReferenceEquals(s, c) && ReferencesColumn(expr, s.Name)).ToList();

        return sources.Count == 2 && sources.All(s => s.IsCoded && !s.IsExtensible && s.EnumTypeName == c.EnumTypeName);
    }

    /// <summary>
    /// Whole-identifier match, so <c>priority_code</c> does not match inside <c>priority_code_override</c>.
    /// </summary>
    private static bool ReferencesColumn(string expression, string columnName)
    {
        for (
            var i = expression.IndexOf(columnName, StringComparison.Ordinal);
            i >= 0;
            i = expression.IndexOf(columnName, i + 1, StringComparison.Ordinal)
        )
        {
            var endsAt = i + columnName.Length;
            var boundedLeft = i == 0 || !IsIdentifierChar(expression[i - 1]);
            var boundedRight = endsAt >= expression.Length || !IsIdentifierChar(expression[endsAt]);
            if (boundedLeft && boundedRight)
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsIdentifierChar(char ch) => char.IsLetterOrDigit(ch) || ch == '_';

    private static string RenderOnDelete(DbForeignKeyAction action) =>
        action switch
        {
            DbForeignKeyAction.NoAction => "",
            DbForeignKeyAction.Cascade => " ON DELETE CASCADE",
            DbForeignKeyAction.SetNull => " ON DELETE SET NULL",
            _ => throw new InvalidOperationException($"Unhandled DbForeignKeyAction {action}"),
        };

    private static string ResolveTableName(Type t)
    {
        var table = (DbTableAttribute?)Attribute.GetCustomAttribute(t, typeof(DbTableAttribute));
        return table?.Name ?? throw new InvalidOperationException($"FK target {t.Name} has no [DbTable].");
    }

    private static void AppendTerminator(StringBuilder sb, SqlDdlDialect dialect)
    {
        if (dialect.Terminator is { } t)
        {
            sb.AppendLine(t);
        }
    }
}
