using System.Globalization;
using System.Reflection;
using System.Text;
using Acta.Emit.Shared.Model;

namespace Acta.Emit.Features.Docs;

/// <summary>Emits the code-family decoder reference from source declarations.</summary>
internal static class CodeFamilyEmitter
{
    private const string PayloadFormatName = "JobPayloadFormat";

    internal static string EmitCodes(SchemaModel schema, string repoRoot)
    {
        var families = CodeFamilyDiscovery.DiscoverAll(schema);
        var payload = PayloadFormatFamily.Discover();
        var areas = CodeFamilySourceLocator.ResolveAreas(repoRoot, families.Select(family => family.Name).Append(PayloadFormatName));

        var sb = new StringBuilder();
        EmitHeader(sb, families.Count + 1, families.Sum(family => family.Values.Count) + payload.Values.Count);
        EmitInventory(sb, families, areas);
        EmitCodesByArea(sb, families, payload, areas);
        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, int familyCount, int valueCount)
    {
        sb.AppendLine(
            "<!-- GENERATED by tools/Acta.Emit (subcommand `docs`). Do not hand-edit; CI drift-checks via `Acta.Emit check`. Sources: `[Code]` declarations under `src/Acta` and the `JobPayloadFormat` registry. -->"
        );
        sb.AppendLine();
        sb.AppendLine("# Code families");
        sb.AppendLine();
        sb.AppendLine("> Generated reference for Acta code families and the payload-format registry.");
        sb.AppendLine(
            "> Every persisted code is documented here exactly once; the data-model reference [`data-model.md`](./data-model.md) links into this file from every code-bearing column."
        );
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"This release: **{familyCount} families**, **{valueCount} values**.");
        sb.AppendLine();
        sb.AppendLine(
            "> Numeric IDs are stable family-local persistence identifiers. Enum members carry programmatic meaning; textual codes carry operator-facing meaning."
        );
        sb.AppendLine("> Numeric grouping is a readability convention, not a runtime schema. Canonical failure states use `200`.");
        sb.AppendLine(
            "> Unknown values and `255` are rejected in closed families. `JobPayloadFormat` is the explicit exception permitting consumer-defined value `255`."
        );
        sb.AppendLine("> Assigned, deprecated, retired, and permanently reserved identities are never reused.");
        sb.AppendLine();
        sb.AppendLine("## Human-readable ordering");
        sb.AppendLine();
        sb.AppendLine("The numbers are arranged so a raw value gives you a quick hint about the state you are looking at:");
        sb.AppendLine();
        sb.AppendLine("- `0` means nothing is selected, enabled, or present.");
        sb.AppendLine("- Values below `100` represent work that is still active or waiting.");
        sb.AppendLine("- `100` represents normal successful completion.");
        sb.AppendLine(
            "- Values between `150` and `199` represent controlled completion, such as rescheduling, suppression, or administrative closure."
        );
        sb.AppendLine("- `200` represents failure, exhaustion, or death.");
        sb.AppendLine("- `220` represents cancellation.");
        sb.AppendLine("- `230` represents interruption or an unknown outcome.");
        sb.AppendLine("- `240` represents retirement or deprecation.");
        sb.AppendLine("- `255` is reserved and rejected in closed code families.");
        sb.AppendLine();
        sb.AppendLine(
            "This pattern makes raw values easier to scan in database rows, logs, and diagnostics. Treat it as a visual guide only. Application code must check explicit enum members and must not infer behavior from numeric comparisons."
        );
        sb.AppendLine();
        sb.AppendLine("`JobPayloadFormat` is the one exception: consumer-defined formats may use IDs from `128` through `255`.");
        sb.AppendLine();
    }

    private static void EmitInventory(StringBuilder sb, IReadOnlyList<CodeFamilyModel> families, IReadOnlyDictionary<string, string> areas)
    {
        var rows = families
            .Select(family => new InventoryRow(family.Name, family.CodeKind, family.Storage, areas[family.Name], family.IsMeta))
            .Append(new InventoryRow(PayloadFormatName, "payload-format", "byte", areas[PayloadFormatName], IsMeta: false))
            .OrderBy(row => row.Name, StringComparer.Ordinal);

        sb.AppendLine("## Code-family inventory");
        sb.AppendLine();
        sb.AppendLine("| Family | Code kind | Backing | Folder |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var row in rows)
        {
            var codeKind = row.IsMeta ? "_(meta-enum)_" : $"`{row.CodeKind}`";
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| {Anchors.LinkCodeFamilyLocal(row.Name)} | {codeKind} | `{row.Storage}` | `{row.Area}` |"
            );
        }
        sb.AppendLine();
    }

    private static void EmitCodesByArea(
        StringBuilder sb,
        IReadOnlyList<CodeFamilyModel> families,
        PayloadFormatFamily payload,
        IReadOnlyDictionary<string, string> areas
    )
    {
        var familiesByName = families.ToDictionary(family => family.Name, StringComparer.Ordinal);

        sb.AppendLine("## Codes");
        sb.AppendLine();
        foreach (var areaGroup in areas.GroupBy(entry => entry.Value).OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            sb.Append("### ").AppendLine(areaGroup.Key);
            sb.AppendLine();

            foreach (var name in areaGroup.Select(entry => entry.Key).OrderBy(name => name, StringComparer.Ordinal))
            {
                if (string.Equals(name, PayloadFormatName, StringComparison.Ordinal))
                {
                    EmitPayloadFormat(sb, payload);
                }
                else
                {
                    EmitFamily(sb, familiesByName[name]);
                }
            }
        }
    }

    private static void EmitFamily(StringBuilder sb, CodeFamilyModel family)
    {
        var kind = family.IsMeta ? "meta-enum" : family.CodeKind;
        sb.Append("#### `")
            .Append(family.Name)
            .Append("` · `")
            .Append(kind)
            .Append("` ")
            .AppendLine(Anchors.Tag(Anchors.CodeFamily(family.Name)));
        sb.AppendLine();

        sb.AppendLine("| Member | Id | Code | Description | Lifecycle |");
        sb.AppendLine("|---|---:|---|---|---|");
        foreach (var value in family.Values)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{value.Member}` | {value.Id} | `{MarkdownEscape.Cell(value.Code)}` | {MarkdownEscape.Cell(value.Description)} | {value.Lifecycle} |"
            );
        }
        sb.AppendLine();

        if (family.ReservedCodes.Count > 0)
        {
            sb.AppendLine("**Reserved codes**");
            sb.AppendLine();
            sb.AppendLine("| Id | Code |");
            sb.AppendLine("|---:|---|");
            foreach (var reserved in family.ReservedCodes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"| {reserved.Id} | `{MarkdownEscape.Cell(reserved.Code)}` |");
            }
            sb.AppendLine();
        }

        if (family.ReservedRanges.Count > 0)
        {
            sb.AppendLine("**Reserved ranges**");
            sb.AppendLine();
            sb.AppendLine("| Ids | Reason | Availability |");
            sb.AppendLine("|---:|---|---|");
            foreach (var range in family.ReservedRanges)
            {
                var availability = range.PermanentlyUnavailable ? "Permanent" : "Held";
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"| {range.Start}–{range.End} | {MarkdownEscape.Cell(range.Reason)} | {availability} |"
                );
            }
            sb.AppendLine();
        }
    }

    private static void EmitPayloadFormat(StringBuilder sb, PayloadFormatFamily payload)
    {
        sb.Append("#### `")
            .Append(PayloadFormatName)
            .Append("` · `payload-format` ")
            .AppendLine(Anchors.Tag(Anchors.CodeFamily(PayloadFormatName)));
        sb.AppendLine();

        sb.AppendLine("| Member | Id | Code | Description | Lifecycle |");
        sb.AppendLine("|---|---:|---|---|---|");
        foreach (var value in payload.Values)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{value.Member}` | {value.Id} | `{MarkdownEscape.Cell(value.Name)}` | {MarkdownEscape.Cell(value.Description)} | Active |"
            );
        }
        sb.AppendLine();
    }

    private sealed record InventoryRow(string Name, string? CodeKind, string Storage, string Area, bool IsMeta);
}

internal sealed record PayloadFormatFamily(IReadOnlyList<PayloadFormatEntry> Values)
{
    internal static PayloadFormatFamily Discover()
    {
        var asm = typeof(Acta.JobPayloadFormat).Assembly;
        var docs = XmlDocSource.ForAssembly(asm);
        var entries = new List<PayloadFormatEntry>();

        var fields = typeof(Acta.JobPayloadFormat)
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(field => field.FieldType == typeof(Acta.JobPayloadFormat));

        foreach (var field in fields)
        {
            var value = (Acta.JobPayloadFormat)field.GetValue(null)!;
            entries.Add(new PayloadFormatEntry(value.Id, field.Name, value.Name, docs.ForField(field) ?? ""));
        }
        return new PayloadFormatFamily(entries.OrderBy(entry => entry.Id).ToList());
    }
}

internal sealed record PayloadFormatEntry(byte Id, string Member, string Name, string Description);
