using System.Globalization;
using System.Reflection;
using System.Text;
using Acta.Emit.Shared.Model;

namespace Acta.Emit.Features.Docs;

/// <summary>
/// Emits <c>docs/reference/code-families.md</c> from the discovered code families + payload formats.
/// </summary>
internal static class CodeFamilyEmitter
{
    public static string EmitCodes(SchemaModel schema)
    {
        // Pass the schema so meta-enums referenced by columns (e.g. CodeLifecycleCode on
        // codes.lifecycle_code) are discovered alongside Code families and get a doc anchor.
        var families = CodeFamilyDiscovery.DiscoverAll(schema);
        var payload = PayloadFormatFamily.Discover();

        var sb = new StringBuilder();

        EmitHeader(sb, families.Count + 1, families.Sum(f => f.Values.Count) + payload.Values.Count);
        EmitInventory(sb, schema, families, payload);
        EmitDomainGroups(sb, schema, families, payload);

        return sb.ToString();
    }

    // -------------------- Page header --------------------

    private static void EmitHeader(StringBuilder sb, int familyCount, int valueCount)
    {
        sb.AppendLine(
            "<!-- GENERATED by tools/Acta.Emit (subcommand `docs`). Do not hand-edit; re-run after `[Code]` attribute changes; CI drift-checks via `Acta.Emit check`. Source of truth is the `[Code]`-decorated enums in `src/Acta.Contracts` domain folders (and `JobPayloadFormat` for the payload registry). -->"
        );
        sb.AppendLine();
        sb.AppendLine("# Code families");
        sb.AppendLine();
        sb.AppendLine("> Generated reference for Acta code families and the payload-format registry.");
        sb.AppendLine(
            "> Every persisted code is documented here exactly once; the data-model reference [`data-model.md`](./data-model.md) links into this file from every code-bearing column."
        );
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"This release: **{familyCount} families**, **{valueCount} values**.");
        sb.AppendLine();
        sb.AppendLine(
            "> Numeric IDs are stable family-local persistence identifiers. Enum members carry programmatic meaning; textual codes carry operator-facing meaning."
        );
        sb.AppendLine("> Numeric grouping is a readability convention, not a runtime schema. Canonical failure states use `200`.");
        sb.AppendLine(
            "> Unknown values and `255` are rejected in closed families. `JobPayloadFormat` is the explicit exception permitting consumer-defined value `255`."
        );
        sb.AppendLine("> Assigned, deprecated, retired, and permanently reserved identities are never reused.");
        sb.AppendLine();
        sb.AppendLine("## Human-readable ordering");
        sb.AppendLine();
        sb.AppendLine("The numbers are arranged so a raw value gives you a quick hint about the state you are looking at:");
        sb.AppendLine();
        sb.AppendLine("- `0` means nothing is selected, enabled, or present.");
        sb.AppendLine("- Values below `100` represent work that is still active or waiting.");
        sb.AppendLine("- `100` represents normal successful completion.");
        sb.AppendLine(
            "- Values between `150` and `199` represent controlled completion, such as rescheduling, suppression, or administrative closure."
        );
        sb.AppendLine("- `200` represents failure, exhaustion, or death.");
        sb.AppendLine("- `220` represents cancellation.");
        sb.AppendLine("- `230` represents interruption or an unknown outcome.");
        sb.AppendLine("- `240` represents retirement or deprecation.");
        sb.AppendLine("- `255` is reserved and rejected in closed code families.");
        sb.AppendLine();
        sb.AppendLine(
            "This pattern makes raw values easier to scan in database rows, logs, and diagnostics. Treat it as a visual guide only. Application code must check explicit enum members and must not infer behavior from numeric comparisons."
        );
        sb.AppendLine();
        sb.AppendLine("`JobPayloadFormat` is the one exception: consumer-defined formats may use IDs from `128` through `255`.");
        sb.AppendLine();
    }

    // -------------------- Inventory --------------------

    private static void EmitInventory(
        StringBuilder sb,
        SchemaModel schema,
        IReadOnlyList<CodeFamilyModel> families,
        PayloadFormatFamily payload
    )
    {
        sb.AppendLine("## Code-family inventory");
        sb.AppendLine();
        sb.AppendLine("| Family | Code kind | Backing | Domain | Style | Set by |");
        sb.AppendLine("|---|---|---|---|---|---|");

        foreach (var f in families)
        {
            var domain = CodeFamilyInference.DomainLabel(CodeFamilyInference.DomainFor(f.Name));
            var style = f.IsMeta ? "Meta-enum" : CodeFamilyInference.CodeStyleFor(f.Name);
            var setBy = CodeFamilyInference.CodeSetByFor(f.Name);
            var codeKindCell = f.CodeKind is null ? "_(meta-enum)_" : $"`{f.CodeKind}`";
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| {Anchors.LinkCodeFamilyLocal(f.Name)} | {codeKindCell} | `{f.Storage}` | {domain} | {style} | {setBy} |"
            );
        }

        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"| {Anchors.LinkCodeFamilyLocal("JobPayloadFormat")} | `payload-format` | `byte` | {CodeFamilyInference.DomainLabel(CodeFamilyInference.CodeDomain.Payloads)} | Registry | {CodeFamilyInference.CodeSetByFor("JobPayloadFormat")} |"
        );
        sb.AppendLine();
    }

    // -------------------- Domain groups --------------------

    private static void EmitDomainGroups(
        StringBuilder sb,
        SchemaModel schema,
        IReadOnlyList<CodeFamilyModel> families,
        PayloadFormatFamily payload
    )
    {
        var groups = families.GroupBy(f => CodeFamilyInference.DomainFor(f.Name)).ToDictionary(g => g.Key, g => g.ToList());

        // Payload domain is special — JobPayloadFormat is the only family.
        if (!groups.ContainsKey(CodeFamilyInference.CodeDomain.Payloads))
        {
            groups[CodeFamilyInference.CodeDomain.Payloads] = new List<CodeFamilyModel>();
        }

        sb.AppendLine("## Domain groups");
        sb.AppendLine();
        foreach (CodeFamilyInference.CodeDomain domain in Enum.GetValues(typeof(CodeFamilyInference.CodeDomain)))
        {
            if (!groups.TryGetValue(domain, out var domainFamilies) && domain != CodeFamilyInference.CodeDomain.Payloads)
            {
                continue;
            }

            sb.Append("### ")
                .Append(CodeFamilyInference.DomainLabel(domain))
                .Append(' ')
                .AppendLine(Anchors.Tag(CodeFamilyInference.DomainSlug(domain)));
            sb.AppendLine();

            // Family list for the group
            var list = domainFamilies ?? new List<CodeFamilyModel>();
            foreach (var f in list)
            {
                var ck = f.CodeKind is null ? "_meta-enum_" : $"`{f.CodeKind}`";
                var st = f.IsMeta ? "Meta-enum (no `code_kind`)" : CodeFamilyInference.CodeStyleFor(f.Name);
                sb.AppendLine(CultureInfo.InvariantCulture, $"- {Anchors.LinkCodeFamilyLocal(f.Name)} · {ck} ({f.Storage}-backed). {st}.");
            }
            if (domain == CodeFamilyInference.CodeDomain.Payloads)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"- {Anchors.LinkCodeFamilyLocal("JobPayloadFormat")} · `payload-format` (byte-backed). Registry (not `[Code]`)."
                );
            }
            sb.AppendLine();

            // Per-family detail
            foreach (var f in list)
            {
                EmitFamily(sb, schema, f);
            }
            if (domain == CodeFamilyInference.CodeDomain.Payloads)
            {
                EmitPayloadFormat(sb, schema, payload);
            }
        }
    }

    // -------------------- Per-family detail --------------------

    private static void EmitFamily(StringBuilder sb, SchemaModel schema, CodeFamilyModel f)
    {
        var heading = f.CodeKind is null ? $"`{f.Name}` (meta-enum) " : $"`{f.Name}` · `{f.CodeKind}` ";
        sb.Append("#### ").Append(heading).AppendLine(Anchors.Tag(Anchors.CodeFamily(f.Name)));
        sb.AppendLine();

        // One-line meaning
        var style = f.IsMeta ? "Meta-enum" : CodeFamilyInference.CodeStyleFor(f.Name);
        var oneLine = MarkdownText.FirstSentenceOrNull(f.Summary) ?? $"{style} code family.";
        sb.AppendLine(oneLine);
        sb.AppendLine();
        if (f.IsMeta)
        {
            sb.AppendLine(
                "> This is a **meta-enum**: it classifies other code families rather than seeding rows there. No `code_kind` discriminator; no entries in the catalog. The column that uses it stores the enum's underlying numeric value directly."
            );
            sb.AppendLine();
        }

        // Badges
        var badges = CodeFamilyInference.CodeBadges(f.Name, style);
        if (badges.Count > 0)
        {
            sb.AppendLine(string.Join(" ", badges.Select(b => $"`{b}`")));
            sb.AppendLine();
        }

        // At-a-glance
        var domain = CodeFamilyInference.DomainLabel(CodeFamilyInference.DomainFor(f.Name));
        var setBy = CodeFamilyInference.CodeSetByFor(f.Name);
        var appearsIn = AppearsInLine(schema, f.Name);
        var codeKindRow = f.CodeKind is null ? "_(meta-enum)_" : $"`{f.CodeKind}`";
        var sourceRow = f.IsMeta ? "Plain `enum` (referenced by schema; no `[Code]` decorations)" : "`[Code]` enum";

        sb.AppendLine("| At a glance | |");
        sb.AppendLine("|---|---|");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Backing type | `{f.Storage}` |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Code kind | {codeKindRow} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Source | {sourceRow} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Domain | {domain} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Code style | {style} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Appears in | {appearsIn} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Set by | {setBy} |");
        if (f.Capacity is { } capacity)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"| Consumed ids | {capacity.Consumed} |");
            sb.AppendLine(CultureInfo.InvariantCulture, $"| Held reserve | {capacity.HeldReserve} |");
            sb.AppendLine(CultureInfo.InvariantCulture, $"| Available ids | {capacity.Available} |");
        }
        sb.AppendLine();

        if (f.Capacity is { } report)
        {
            sb.AppendLine("**Capacity**");
            sb.AppendLine();
            sb.AppendLine("| Assigned | Deprecated | Retired | Permanently reserved | Held reserve | Available | Invalid sentinels |");
            sb.AppendLine("|---:|---:|---:|---:|---:|---:|---:|");
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| {report.Assigned} | {report.Deprecated} | {report.Retired} | {report.PermanentlyReserved} | {report.HeldReserve} | {report.Available} | {report.InvalidSentinels} |"
            );
            sb.AppendLine();
        }

        // Full value reference
        sb.AppendLine("**Values**");
        sb.AppendLine();
        sb.AppendLine("| Id | Code | Description | Lifecycle |");
        sb.AppendLine("|---:|---|---|---|");
        foreach (var v in f.Values)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| {v.Id} | `{MarkdownEscape.Cell(v.Code)}` | {MarkdownEscape.Cell(v.Description)} | {v.Lifecycle} |"
            );
        }
        sb.AppendLine();

        sb.AppendLine("---");
        sb.AppendLine();
    }

    // -------------------- JobPayloadFormat (special) --------------------

    private static void EmitPayloadFormat(StringBuilder sb, SchemaModel schema, PayloadFormatFamily payload)
    {
        sb.Append("#### ").Append("`JobPayloadFormat` · `payload-format` ").AppendLine(Anchors.Tag(Anchors.CodeFamily("JobPayloadFormat")));
        sb.AppendLine();

        sb.AppendLine(
            "Byte-backed payload-format selector carried on every `*_format_id` column. **Not** an `[Code]` enum: `JobPayloadFormat` is a `readonly record struct (byte Id, string Name)` so consumer apps can declare custom formats in the 128-255 id range via `JobPayloadFormat.Custom(id, name)`."
        );
        sb.AppendLine();
        sb.AppendLine("`Registry` `Payloads` `Extensible`");
        sb.AppendLine();

        var appearsIn = AppearsInPayloadLine(schema);
        sb.AppendLine("| At a glance | |");
        sb.AppendLine("|---|---|");
        sb.AppendLine("| Backing type | `byte` |");
        sb.AppendLine("| Code kind | `payload-format` |");
        sb.AppendLine("| Source | `JobPayloadFormat` registry (not `[Code]`) |");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"| Domain | {CodeFamilyInference.DomainLabel(CodeFamilyInference.CodeDomain.Payloads)} |"
        );
        sb.AppendLine("| Code style | Registry |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Appears in | {appearsIn} |");
        sb.AppendLine("| Reserved ranges | `0..127` system-reserved; `128..255` consumer-extensible |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Set by | {CodeFamilyInference.CodeSetByFor("JobPayloadFormat")} |");
        sb.AppendLine();

        sb.AppendLine("**Values**");
        sb.AppendLine();
        sb.AppendLine("| Id | Name | Description | Lifecycle |");
        sb.AppendLine("|---:|---|---|---|");
        foreach (var v in payload.Values)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| {v.Id} | `{MarkdownEscape.Cell(v.Name)}` | {MarkdownEscape.Cell(v.Description)} | Active |"
            );
        }
        sb.AppendLine();

        sb.AppendLine("---");
        sb.AppendLine();
    }

    // -------------------- Helpers --------------------

    private static string AppearsInLine(SchemaModel schema, string familyName)
    {
        var refs = CodeFamilyInference.ColumnsForFamily(schema, familyName);
        if (refs.Count == 0)
        {
            return "·";
        }
        return string.Join(", ", refs.Select(r => Anchors.LinkColumnToDataModel(r.Table, r.Column)));
    }

    private static string AppearsInPayloadLine(SchemaModel schema)
    {
        var refs = CodeFamilyInference.PayloadFormatColumns(schema);
        if (refs.Count == 0)
        {
            return "·";
        }
        return string.Join(", ", refs.Select(r => Anchors.LinkColumnToDataModel(r.Table, r.Column)));
    }
}

internal sealed record PayloadFormatFamily(IReadOnlyList<PayloadFormatEntry> Values)
{
    public static PayloadFormatFamily Discover()
    {
        var asm = typeof(Acta.JobPayloadFormat).Assembly;
        var docs = XmlDocSource.ForAssembly(asm);
        var entries = new List<PayloadFormatEntry>();

        var fields = typeof(Acta.JobPayloadFormat)
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.FieldType == typeof(Acta.JobPayloadFormat));

        foreach (var f in fields)
        {
            var v = (Acta.JobPayloadFormat)f.GetValue(null)!;
            entries.Add(new PayloadFormatEntry(v.Id, v.Name, docs.ForField(f) ?? ""));
        }
        return new PayloadFormatFamily(entries.OrderBy(e => e.Id).ToList());
    }
}

internal sealed record PayloadFormatEntry(byte Id, string Name, string Description);
