using System.Globalization;
using System.Text;
using Acta.Emit.Shared.Model;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Docs;

/// <summary>
/// Emits <c>docs/reference/data-model.md</c> from the entity-model graph. Every structural fact is read
/// from the model; all prose is the XML-doc summary already written on each entity and column:
/// the emitter invents no per-table narrative.
/// </summary>
internal static class DataModelEmitter
{
    public static string EmitDataModelReference(SchemaModel model)
    {
        var sb = new StringBuilder();

        EmitHeader(sb, model);
        EmitInventory(sb, model);
        EmitEntities(sb, model);

        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, SchemaModel model)
    {
        sb.AppendLine(
            "<!-- GENERATED by tools/Acta.Emit (subcommand `docs`). Do not hand-edit; re-run after entity-model changes; CI drift-checks via `Acta.Emit check`. Source of truth is the entity classes under `src/Acta.Relational/Entities/`. -->"
        );
        sb.AppendLine();
        sb.AppendLine("# Data model reference");
        sb.AppendLine();
        sb.AppendLine(
            $"Structural reference for the Acta persistence model: **{model.Entities.Count} entities**, "
                + $"**{model.Entities.Sum(e => e.Columns.Count)} columns**, "
                + $"**{model.Entities.Sum(e => e.Indexes.Count)} indexes**, **{model.Entities.Sum(e => e.Checks.Count)} check constraints**, "
                + $"**{model.Entities.Sum(e => e.ForeignKeys.Count)} foreign keys**. Names render with the default `acta` schema prefix; "
                + "substitute the configured schema if different. Code families resolve into [`code-families.md`](./code-families.md). "
                + "The foreign-key enforcement policy (which references are CASCADE, RESTRICT, or deliberately unenforced) is in "
                + "[`sql-recipes.md`](../guide/sql-recipes.md#foreign-key-policy)."
        );
        sb.AppendLine();
    }

    private static void EmitInventory(StringBuilder sb, SchemaModel model)
    {
        sb.AppendLine("## Schema inventory");
        sb.AppendLine();
        Tables.Header(sb, "Entity", "Purpose", "Key code families");
        foreach (var e in model.Entities)
        {
            var link = Anchors.LinkEntityLocal(e.TableName, $"acta.{e.TableName}");
            var purpose = MarkdownEscape.Cell(MarkdownText.FirstSentenceOrNull(e.Summary) ?? "·");
            var families = CodeFamiliesUsed(e);
            var familiesCell = families.Count == 0 ? "·" : string.Join(", ", families.Select(Anchors.LinkCodeFamilyToCodeFamilies));
            sb.AppendLine(CultureInfo.InvariantCulture, $"| {link} | {purpose} | {familiesCell} |");
        }
        sb.AppendLine();
    }

    private static void EmitEntities(StringBuilder sb, SchemaModel model)
    {
        sb.AppendLine("## Entity reference");
        sb.AppendLine();
        foreach (var e in model.Entities)
        {
            EmitEntity(sb, e);
        }
    }

    private static void EmitEntity(StringBuilder sb, EntityModel e)
    {
        sb.Append("### ")
            .Append(CultureInfo.InvariantCulture, $"`acta.{e.TableName}` ")
            .AppendLine(Anchors.Tag(Anchors.Entity(e.TableName)));
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(e.Summary))
        {
            sb.AppendLine(e.Summary.Replace("\r\n", "\n").Trim());
            sb.AppendLine();
        }

        var pk = $"`{e.PrimaryKey.Name}` ({string.Join(", ", e.PrimaryKey.Columns.Select(c => $"`{c}`"))})";
        sb.AppendLine(CultureInfo.InvariantCulture, $"**CLR type** `{e.ClrType.FullName}` · **Primary key** {pk}");
        sb.AppendLine();

        EmitColumns(sb, e);
        EmitIndexes(sb, e);
        EmitChecks(sb, e);
        EmitForeignKeys(sb, e);

        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void EmitColumns(StringBuilder sb, EntityModel e)
    {
        sb.AppendLine("**Columns**");
        sb.AppendLine();
        Tables.Header(sb, "Column", "Kind", "Size", "Nullable", "Default", "Codes", "Description");
        foreach (var c in e.Columns)
        {
            var size = FormatSize(c);
            var nullable = c.IsNullable ? "yes" : "no";
            var @default = FormatDefault(c);
            var note = CodeOrConstraintNote(c);
            var description = MarkdownEscape.Cell(c.Summary);
            // The column anchor is load-bearing: code-families.md deep-links here per code column.
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{c.Name}`{Anchors.Tag(Anchors.Column(e.TableName, c.Name))} | `{c.Kind}` | {size} | {nullable} | {@default} | {note} | {description} |"
            );
        }
        sb.AppendLine();
    }

    private static void EmitIndexes(StringBuilder sb, EntityModel e)
    {
        if (e.Indexes.Count == 0)
        {
            return;
        }
        sb.AppendLine("**Indexes**");
        sb.AppendLine();
        Tables.Header(sb, "Name", "Columns", "Uniqueness", "Filter", "Usage");
        foreach (var idx in e.Indexes)
        {
            var unique = idx.IsUnique ? "unique" : "not unique";
            var cols = string.Join(", ", idx.Columns.Select(c => idx.Descending?.Contains(c) == true ? $"`{c}` DESC" : $"`{c}`"));
            var filter = idx.Filter is null ? "none" : $"`{idx.Filter}`";
            var usage = idx.Usage.Length == 0 ? "·" : $"`{idx.Usage}`";
            sb.AppendLine(CultureInfo.InvariantCulture, $"| `{idx.Name}` | {cols} | {unique} | {filter} | {usage} |");
        }
        sb.AppendLine();
    }

    private static void EmitChecks(StringBuilder sb, EntityModel e)
    {
        if (e.Checks.Count == 0)
        {
            return;
        }
        sb.AppendLine("**Check constraints**");
        sb.AppendLine();
        Tables.Header(sb, "Name", "SQL expression");
        foreach (var chk in e.Checks)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"| `{chk.Name}` | `{chk.Sql}` |");
        }
        sb.AppendLine();
    }

    private static void EmitForeignKeys(StringBuilder sb, EntityModel e)
    {
        if (e.ForeignKeys.Count == 0)
        {
            return;
        }
        sb.AppendLine("**Foreign keys**");
        sb.AppendLine();
        Tables.Header(sb, "Constraint", "Column → Target", "On delete");
        foreach (var fk in e.ForeignKeys)
        {
            var targetTable =
                (Attribute.GetCustomAttribute(fk.Target, typeof(DbTableAttribute)) as DbTableAttribute)?.Name ?? fk.Target.Name;
            var onDelete = fk.OnDelete switch
            {
                DbForeignKeyAction.Cascade => "CASCADE",
                DbForeignKeyAction.SetNull => "SET NULL",
                _ => "NO ACTION",
            };
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{fk.Name}` | `{fk.Column}` → `acta.{targetTable}({fk.TargetColumn})` | {onDelete} |"
            );
        }
        sb.AppendLine();
    }

    // Distinct code families referenced by this entity's columns, in column order. The synthetic
    // JobPayloadFormat family is added when any payload / *_format_id column is present.
    private static IReadOnlyList<string> CodeFamiliesUsed(EntityModel e)
    {
        var families = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var c in e.Columns)
        {
            if (c.EnumTypeName is not null && seen.Add(c.EnumTypeName))
            {
                families.Add(c.EnumTypeName);
            }
        }
        var hasPayload = e.Columns.Any(c => c.Kind == DbKind.BinaryPayload || c.Name.EndsWith("_format_id", StringComparison.Ordinal));
        if (hasPayload && seen.Add("JobPayloadFormat"))
        {
            families.Add("JobPayloadFormat");
        }
        return families;
    }

    // Length / precision facet of the column type, mirroring the DDL dialects' RenderType.
    // Only variable-width kinds carry a size; fixed-width kinds (Int, Utc, Code, ...) render "·".
    // Unbounded string / payload columns render "max" to match varchar(max) / varbinary(max).
    private static string FormatSize(ColumnModel c) =>
        c.Kind switch
        {
            DbKind.Decimal => $"{c.Precision}, {c.Scale}",
            DbKind.AsciiString or DbKind.UnicodeString => c.Size > 0 ? c.Size.ToString(CultureInfo.InvariantCulture) : "max",
            DbKind.Bytes => c.Size > 0 ? c.Size.ToString(CultureInfo.InvariantCulture) : "max",
            DbKind.BinaryPayload => "max",
            _ => "·",
        };

    // Effective column default, mirroring SqlSchemaEmitter's allocation precedence (identity for an
    // auto sole PK, then the DbDefault). Rendered as provider-neutral tokens; "·" means no default,
    // so the caller must supply the value at INSERT.
    private static string FormatDefault(ColumnModel c)
    {
        return c.IsSolePrimaryKey && !c.IsManualPrimaryKey && c.Kind is DbKind.Byte or DbKind.Int16 or DbKind.Int32 or DbKind.Int64
            ? "`Identity`"
            : c.Default switch
            {
                DbDefault.UtcNow => "`UtcNow`",
                DbDefault.Zero => "`0`",
                DbDefault.EmptyString => "`''`",
                DbDefault.NewGuid => "`NewGuid`",
                _ => "·",
            };
    }

    private static string CodeOrConstraintNote(ColumnModel c)
    {
        if (c.EnumTypeName is not null)
        {
            return c.CodeKind is not null
                ? $"{Anchors.LinkCodeFamilyToCodeFamilies(c.EnumTypeName)} (`{c.CodeKind}`)"
                : $"enum `{c.EnumTypeName}` (meta-enum)";
        }
        if (c.IsPrimaryKey)
        {
            return "PK";
        }
        if (c.IsConcurrencyToken)
        {
            return "concurrency token";
        }
        return c.Name.EndsWith("_format_id", StringComparison.Ordinal) ? Anchors.LinkCodeFamilyToCodeFamilies("JobPayloadFormat") : "·";
    }
}
