using System.Text;
using System.Text.Json;
using Acta.Relational.Resources;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Docs;

/// <summary>
/// Emits <c>docs/reference/schema-{dialect}.sql</c>: one provider's complete schema script,
/// composed from the same on-disk SQL the provider embeds (migration history table, every migration
/// in order, operator views, routines) and fully rendered for the default schema, so a DBA can
/// review and run it verbatim. Exists because locked-down deployments forbid DDL from the
/// application principal: the pipeline runs this file under an elevated one, the application keeps
/// <c>ApplyMigrationsOnStartup = false</c>, and because each migration records its own history row
/// (including the baseline stamp) the bootstrap accepts the result as its own work.
/// </summary>
internal static class ProvisionScriptEmitter
{
    /// <summary>The published file for one dialect: flat beside the other reference artifacts.</summary>
    internal static string PathFor(string repoRoot, string token) => Path.Combine(repoRoot, "docs", "reference", $"schema-{token}.sql");

    internal static readonly (string Token, string Project, string Schema)[] Providers =
    [
        ("pg", "Acta.Postgres", "acta"),
        ("mssql", "Acta.SqlServer", "acta"),
        ("sqlite", "Acta.Sqlite", "main"),
    ];

    internal static string Emit(string repoRoot, string token)
    {
        var (_, project, schema) = Providers.Single(p => string.Equals(p.Token, token, StringComparison.Ordinal));
        var providerDir = Path.Combine(repoRoot, "src", project);
        var mssql = string.Equals(token, "mssql", StringComparison.Ordinal);

        var script = new StringBuilder();
        script.AppendLine($"-- Acta full provisioning script ({token}), schema '{schema}'. GENERATED by tools/Acta.Emit (`docs`");
        script.AppendLine("-- command); do not hand-edit here - edit the source SQL and regenerate. To relocate, replace the");
        script.AppendLine($"-- schema name '{schema}' throughout. Baseline stamp: {SchemaMigrationRunner.RequiredBaselineStamp}.");
        script.AppendLine("--");
        script.AppendLine("-- The same SQL the bootstrap migration runner applies: the migration history table, every");
        script.AppendLine("-- migration in order (each records its own history row), then the operator objects the");
        script.AppendLine("-- provider installs.");
        script.AppendLine("--");
        script.AppendLine("-- INSTALL AND UPGRADE ARE THE SAME FILE. Run it on an empty database or on one already");
        script.AppendLine("-- running an earlier Acta version: every statement is individually guarded, so it applies");
        script.AppendLine("-- exactly what is missing and skips what is present. Re-running it is a no-op. Views and");
        script.AppendLine("-- routines carry no version and are always rewritten to the definitions shipped here.");
        script.AppendLine("--");
        script.AppendLine("-- Run it under a DDL-capable principal; the application principal then needs only DML and");
        script.AppendLine("-- EXECUTE, with ApplyMigrationsOnStartup left false. Because the history rows (and the");
        script.AppendLine("-- baseline stamp) are recorded by the script itself, a bootstrap with migrations enabled also");
        script.AppendLine("-- accepts the result and applies nothing. Site-specific physical tuning (partitioning,");
        script.AppendLine("-- tablespaces, compression) is yours to add; keep the logical shape - tables, columns,");
        script.AppendLine("-- constraints, routine signatures - intact.");
        script.AppendLine();

        void Append(string text)
        {
            var body = text.TrimEnd();
            script.AppendLine(body);
            // Migration files already end with their own batch separator; a second one would emit an
            // empty batch into a file whose whole purpose is being read by a DBA.
            if (!mssql)
            {
                script.AppendLine();
            }
            else if (!body.EndsWith("\nGO", StringComparison.Ordinal))
            {
                script.AppendLine("GO");
            }
        }

        string Render(string sql)
        {
            if (sql.Contains("{{table", StringComparison.Ordinal))
            {
                throw new InvalidOperationException("Provision scripts never include outbox source-catalog templates.");
            }
            if (!string.Equals(token, "sqlite", StringComparison.Ordinal) && sql.Contains("{{now}}", StringComparison.Ordinal))
            {
                throw new InvalidOperationException("The {{now}} token is the SQLite instant encoding; other dialects use native now().");
            }
            // Full-line comments keep their tokens verbatim: substituting prose like "`{{schema}}` is
            // substituted at apply time" would turn a true statement about a token into nonsense
            // about a literal schema name in the DBA-facing file. Decode tokens render on the joined
            // text (never inside comments) so an expression wrapping a line still expands.
            var lines = sql.ReplaceLineEndings("\n")
                .Split('\n')
                .Select(line =>
                    line.TrimStart().StartsWith("--", StringComparison.Ordinal)
                        ? line
                        : line.Replace("{{schema}}", schema).Replace("{{now}}", "CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)")
                );
            return CodeDecodeSql.RenderDecodeTokens(string.Join("\n", lines));
        }

        if (mssql)
        {
            // Mirrors the runner's prelude: M001 has filtered indexes that require these session options.
            Append("SET QUOTED_IDENTIFIER ON;\nSET ANSI_NULLS ON;");
        }
        Append(mssql ? "SET XACT_ABORT ON;\nBEGIN TRANSACTION;" : "BEGIN;");
        Append(
            "-- ===== migration history table =====\n"
                + Render(File.ReadAllText(Path.Combine(providerDir, "Sql", "Schema", "EnsureMigrations.sql")))
        );

        var migrationsDir = Path.Combine(providerDir, "Schema", "Migrations");
        foreach (var migration in Directory.GetFiles(migrationsDir, "M*.sql").OrderBy(f => f, StringComparer.Ordinal))
        {
            var name = Path.GetFileNameWithoutExtension(migration);
            // Drop the migration file's own leading comment banner: it addresses migration editors
            // ("hand-edit only as a delta", "`{{schema}}` is substituted at apply time") and reads
            // false or confusing inside the fully rendered script; the BEGIN banner names the file.
            var body = File.ReadAllText(migration)
                .ReplaceLineEndings("\n")
                .Split('\n')
                .SkipWhile(line => line.StartsWith("--", StringComparison.Ordinal) || line.Length == 0);
            Append($"-- ===== BEGIN {name} =====\n" + Render(string.Join("\n", body)));
            Append($"-- ===== END {name} =====");
        }

        // Views before routines, each set in resource-name order, mirroring SqlObjectInstaller.
        Append("-- ===== operator views (versionless; always rewritten to this file's definitions) =====");
        foreach (var (name, body) in SqlObjects(providerDir, ".view.sql"))
        {
            if (!name.EndsWith("_view", StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Provider view '{name}' must install as a plural '_view' name.");
            }
            var statements = SqlObjectInstaller.WrapView(token, $"{schema}.{name}", Render(body).Trim());
            Append(string.Join("\n", statements.Select(s => s.Body)));
        }
        var routines = SqlObjects(providerDir, ".routine.sql").ToArray();
        if (routines.Length > 0)
        {
            Append("-- ===== routines (versionless; always rewritten to this file's definitions) =====");
        }
        foreach (var (_, body) in routines)
        {
            Append(Render(body));
        }

        Append(mssql ? "COMMIT TRANSACTION;" : "COMMIT;");
        return script.ToString().ReplaceLineEndings("\n");
    }

    private static IEnumerable<(string Name, string Body)> SqlObjects(string providerDir, string suffix) =>
        Directory
            .EnumerateFiles(Path.Combine(providerDir, "Sql"), "*" + suffix, SearchOption.AllDirectories)
            .Select(path => (Path: path, Resource: Path.GetRelativePath(providerDir, path).Replace('\\', '.').Replace('/', '.')))
            .OrderBy(f => f.Resource, StringComparer.Ordinal)
            .Select(f =>
                (JsonNamingPolicy.SnakeCaseLower.ConvertName(Path.GetFileName(f.Path)[..^suffix.Length]), File.ReadAllText(f.Path))
            );
}
