using System.Globalization;
using System.Text;
using System.Text.Json;
using Acta.Emit.Features.Migrations;
using Acta.Emit.Shared;
using Acta.Relational.Resources;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Docs;

/// <summary>
/// Emits <c>docs/reference/schema-{dialect}.sql</c>: one provider's complete schema script,
/// composed from the same on-disk SQL the provider embeds (migration history table, every migration
/// in order, operator views, routines) and fully rendered for the default schema, so a DBA can
/// review and run it verbatim. Exists because locked-down deployments forbid DDL from the
/// application principal: the pipeline runs this file under an elevated one, the application keeps
/// <c>ApplyMigrationsOnStartup = false</c>, and because each migration records its own history row
/// (including the baseline stamp) the bootstrap accepts the result as its own work.
/// </summary>
internal static class ProvisionScriptEmitter
{
    /// <summary>The published file for one dialect: flat beside the other reference artifacts.</summary>
    internal static string PathFor(string repoRoot, string token) => Path.Combine(repoRoot, "docs", "reference", $"schema-{token}.sql");

    internal static readonly (string Token, string Project, string Schema)[] Providers =
    [
        .. ProviderCatalog.All.Select(p => (p.Token, p.Project, p.Schema)),
    ];

    internal static string Emit(string repoRoot, string token)
    {
        var (_, project, schema) = Providers.Single(p => string.Equals(p.Token, token, StringComparison.Ordinal));
        var providerDir = Path.Combine(repoRoot, "src", project);
        var mssql = string.Equals(token, "mssql", StringComparison.Ordinal);
        var sqlite = string.Equals(token, "sqlite", StringComparison.Ordinal);

        var script = new StringBuilder();
        script.AppendLine(
            CultureInfo.InvariantCulture,
            $"-- Acta full provisioning script ({token}), schema '{schema}'. GENERATED by tools/Acta.Emit (`docs`"
        );
        script.AppendLine("-- command); do not hand-edit here - edit the source SQL and regenerate. To relocate, replace the");
        // Read from the provider's own baseline migration rather than from the generated constants, so
        // one emit pass produces a script and a stamp that describe the same SQL.
        var stamp =
            MigrationFiles.BaselineStampFor(repoRoot, token)
            ?? throw new InvalidOperationException($"Provider '{token}' has no baseline migration recording a stamp row.");
        script.AppendLine(CultureInfo.InvariantCulture, $"-- schema name '{schema}' throughout. Baseline stamp: {stamp}.");
        script.AppendLine("--");
        script.AppendLine("-- The same SQL the bootstrap migration runner applies: the migration history table, every");
        script.AppendLine("-- migration in order (each records its own history row), then the operator objects the");
        script.AppendLine("-- provider installs.");
        script.AppendLine("-- It takes the per-schema lock the runtime bootstrap takes before either reads the history, so");
        script.AppendLine("-- two installers, script or bootstrap, never interleave.");
        if (mssql)
        {
            script.AppendLine("-- It also sets READ_COMMITTED_SNAPSHOT on the database, the way the runtime's own bootstrap");
            script.AppendLine("-- does: the first batch, outside the transaction, skipped on a fresh install and on a re-run");
            script.AppendLine("-- alike once the database has it on.");
        }
        if (sqlite)
        {
            script.AppendLine("-- It also puts the database in WAL journal mode, the way the runtime's own bootstrap does:");
            script.AppendLine("-- the first line, ahead of the transaction, and a no-op on a database already in WAL.");
        }
        script.AppendLine("--");
        script.AppendLine("-- WHERE TO RUN IT. Run it on an empty database to install, or again on a database it already");
        script.AppendLine("-- provisioned: every statement is individually guarded, so a re-run applies nothing that is");
        script.AppendLine("-- present and leaves the data in place. Views and routines carry no version and are rewritten");
        script.AppendLine("-- to the definitions shipped here, except over a newer release's package: then the script stops");
        script.AppendLine("-- before changing anything. A later 1.x release upgrades a 1.x database with");
        script.AppendLine("-- its own migrations, carried in its own copy of this script. A database provisioned by a");
        script.AppendLine("-- release candidate (1.0.0-rc.x) has no upgrade path: provision a new one. Startup refuses it");
        script.AppendLine("-- and names its baseline.");
        script.AppendLine("--");
        script.AppendLine("-- Run it with a client that stops at the first error, which is what makes the transaction below a");
        script.AppendLine(
            token switch
            {
                "pg" => "-- guarantee: psql -v ON_ERROR_STOP=1. A client that runs on past a failed statement would reach the",
                "mssql" => "-- guarantee: sqlcmd -b, or SQLCMD mode with stop-on-error in SSMS. A client that runs on past a failed",
                _ => "-- guarantee: sqlite3 -bail. A client that runs on past a failed statement would reach the package",
            }
        );
        script.AppendLine(
            token switch
            {
                "pg" => "-- package stamp inside an aborted transaction, which then rolls back on commit.",
                "mssql" => "-- batch would reach the package stamp with an object it failed to replace still in place.",
                _ => "-- stamp with an object it failed to replace still in place.",
            }
        );
        script.AppendLine("-- Run it under a DDL-capable principal; the application principal then needs only DML and");
        script.AppendLine("-- EXECUTE, with ApplyMigrationsOnStartup left false. Because the history rows (and the");
        script.AppendLine("-- baseline stamp) are recorded by the script itself, a bootstrap with migrations enabled also");
        script.AppendLine("-- accepts the result and applies nothing. Site-specific physical tuning (partitioning,");
        script.AppendLine("-- tablespaces, compression) is yours to add; keep the logical shape - tables, columns,");
        script.AppendLine("-- constraints, routine signatures - intact.");
        script.AppendLine();

        void Append(string text)
        {
            var body = text.TrimEnd();
            script.AppendLine(body);
            // Migration files already end with their own batch separator; a second one would emit an
            // empty batch into a file whose whole purpose is being read by a DBA.
            if (!mssql)
            {
                script.AppendLine();
            }
            else if (!body.EndsWith("\nGO", StringComparison.Ordinal))
            {
                script.AppendLine("GO");
            }
        }

        string Render(string sql)
        {
            if (sql.Contains("{{table", StringComparison.Ordinal))
            {
                throw new InvalidOperationException("Provision scripts never include outbox source-catalog templates.");
            }
            if (!string.Equals(token, "sqlite", StringComparison.Ordinal) && sql.Contains("{{now}}", StringComparison.Ordinal))
            {
                throw new InvalidOperationException("The {{now}} token is the SQLite instant encoding; other dialects use native now().");
            }
            // Full-line comments keep their tokens verbatim: substituting prose like "`{{schema}}` is
            // substituted at apply time" would turn a true statement about a token into nonsense
            // about a literal schema name in the DBA-facing file. Decode tokens render on the joined
            // text (never inside comments) so an expression wrapping a line still expands.
            var lines = sql.ReplaceLineEndings("\n")
                .Split('\n')
                .Select(line =>
                    line.TrimStart().StartsWith("--", StringComparison.Ordinal)
                        ? line
                        : line.Replace("{{schema}}", schema, StringComparison.Ordinal)
                            .Replace("{{now}}", "CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)", StringComparison.Ordinal)
                );
            return CodeDecodeSql.RenderDecodeTokens(string.Join("\n", lines));
        }

        if (mssql)
        {
            // READ_COMMITTED_SNAPSHOT the way SqlServerSchemaMigrator sets it (same guard, same
            // termination clause), because the DBA path provisions databases the runtime bootstrap
            // never touches. ALTER DATABASE cannot run inside a user transaction, so it is its own
            // batch; it goes first so the session options below outlive any connection disruption
            // the flip causes.
            Append(
                """
                -- READ_COMMITTED_SNAPSHOT is part of a provisioned Acta database rather than an optional
                -- tuning knob: it is the configuration Acta certifies, and it is what keeps operator and
                -- dashboard reads from taking shared locks and trading blocking with the claim path. Job
                -- correctness does not depend on it - mutations are fenced by lock hints and
                -- compare-and-swap - but reader-side operability does. ALTER DATABASE cannot run inside a
                -- user transaction, hence this separate batch ahead of the one below. A database that
                -- already has it on skips the statement entirely, on install and on re-run alike; when it
                -- does run, WITH ROLLBACK IMMEDIATE disconnects the other sessions in the database, so run
                -- this file in a maintenance window.
                IF (SELECT is_read_committed_snapshot_on FROM sys.databases WHERE database_id = DB_ID()) = 0
                    ALTER DATABASE CURRENT SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
                """
            );
            // Mirrors the runner's prelude: M001 has filtered indexes that require these session options.
            Append("SET QUOTED_IDENTIFIER ON;\nSET ANSI_NULLS ON;");
        }
        if (sqlite)
        {
            // The one PRAGMA SqliteSchemaMigrator stamps once at provision time. The rest
            // (foreign_keys, busy_timeout, synchronous) are per-connection settings SqliteDialect
            // applies on every open, so they would be theatre in a file that runs once.
            Append(
                """
                -- WAL journal mode is part of a provisioned Acta database rather than an optional tuning
                -- knob: it is the configuration Acta certifies, and it is what lets readers run alongside
                -- the single writer instead of queueing behind one global write lock. journal_mode cannot
                -- change inside a transaction, hence this line ahead of the BEGIN below. The setting lives
                -- in the database file header rather than in the connection, so it is written once and a
                -- database already in WAL takes this as a no-op, on install and on re-run alike.
                PRAGMA journal_mode = WAL;
                """
            );
        }
        Append(
            mssql ? "SET XACT_ABORT ON;\nBEGIN TRANSACTION;"
            : sqlite ? "BEGIN IMMEDIATE;"
            : "BEGIN;"
        );
        Append("-- ===== the installer lock, held to commit =====\n" + InstallerLock(token, schema));
        Append(
            "-- ===== migration history table =====\n"
                + Render(File.ReadAllText(Path.Combine(providerDir, "Sql", "Schema", "EnsureMigrations.sql")))
        );
        Append(
            "-- ===== refuse a database a newer release already upgraded =====\n"
                + Render(NoDowngradeGuard(token, MigrationFiles.CurrentMaxVersion(repoRoot)))
        );

        var migrationsDir = Path.Combine(providerDir, "Schema", "Migrations");
        foreach (var migration in Directory.GetFiles(migrationsDir, "M*.sql").OrderBy(f => f, StringComparer.Ordinal))
        {
            var name = Path.GetFileNameWithoutExtension(migration);
            // Drop the migration file's own leading comment banner: it addresses migration editors
            // ("hand-edit only as a delta", "`{{schema}}` is substituted at apply time") and reads
            // false or confusing inside the fully rendered script; the BEGIN banner names the file.
            var body = File.ReadAllText(migration)
                .ReplaceLineEndings("\n")
                .Split('\n')
                .SkipWhile(line => line.StartsWith("--", StringComparison.Ordinal) || line.Length == 0);
            Append($"-- ===== BEGIN {name} =====\n" + Render(string.Join("\n", body)));
            Append($"-- ===== END {name} =====");
        }

        // Views before routines, each set in resource-name order, mirroring SqlObjectInstaller.
        Append("-- ===== operator views (versionless; always rewritten to this file's definitions) =====");
        foreach (var (name, body) in SqlObjects(providerDir, ".view.sql"))
        {
            if (!name.EndsWith("_view", StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Provider view '{name}' must install as a plural '_view' name.");
            }
            var statements = SqlObjectInstaller.WrapView(token, $"{schema}.{name}", Render(body).Trim());
            Append(string.Join("\n", statements.Select(s => s.Body)));
        }
        var routines = SqlObjects(providerDir, ".routine.sql").ToArray();
        if (routines.Length > 0)
        {
            Append("-- ===== routines (versionless; always rewritten to this file's definitions) =====");
        }
        foreach (var (_, body) in routines)
        {
            Append(Render(body));
        }

        // A host with migrations disabled is provisioned by this script and never runs the installer, so
        // a script that stayed silent would leave the package unrecorded for exactly the deployment the
        // startup check exists for. The stamp names every object above and is written only when all of
        // them exist, so a client that ran on past a failed batch leaves no stamp rather than a false one.
        Append("-- ===== installed object package (names the versionless objects above; recorded only when all exist) =====");
        var installed = SqlObjects(providerDir, ".view.sql").Concat(routines).Select(o => o.Name).ToList();
        Append(string.Join("\n", SqlObjectInstaller.StampStatements(schema, token, installed)));

        Append(mssql ? "COMMIT TRANSACTION;" : "COMMIT;");
        return script.ToString().ReplaceLineEndings("\n");
    }

    /// <summary>
    /// The lock the bootstrap takes before it reads migration history (<see cref="SchemaCommands.LockKey"/>),
    /// taken by the script at the same point and held to its commit, so a script and a bootstrap, or two
    /// scripts, never interleave: an older one cannot pass its downgrade guard and then overwrite a newer
    /// install that committed meanwhile. SQLite's <c>BEGIN IMMEDIATE</c> is the lock there.
    /// </summary>
    internal static string InstallerLock(string token, string schema)
    {
        var key = SchemaCommands.LockKey(schema);
        return token switch
        {
            "pg" => $"SELECT pg_advisory_xact_lock(hashtext('{key}'));",
            "mssql" => $"""
                DECLARE @lock_rc INT;
                EXEC @lock_rc = sp_getapplock N'{key}', 'Exclusive', 'Transaction', 60000;
                IF @lock_rc < 0
                    THROW 50000, 'sp_getapplock failed acquiring the {key} lock', 1;
                """,
            _ => "-- BEGIN IMMEDIATE above holds the database's single write lock from here to COMMIT.",
        };
    }

    /// <summary>
    /// Stops the script before it changes anything when a newer build already upgraded the database: a
    /// migration past this script's last, or a higher object package revision. The script's half of the
    /// bootstrap's same rule, because rerunning an older release's script during a rollback must not
    /// rewrite what newer workers call. SQLite has no raise outside a trigger, so a failing CHECK names
    /// the refusal instead.
    /// </summary>
    internal static string NoDowngradeGuard(string token, int lastMigration)
    {
        var prefix = $"objects-{ObjectPackageStamp.ContractMajor}.";
        var start = prefix.Length + 1;
        // NULL rather than an error on any other history row: neither server promises to test the LIKE first.
        var revisionText = token switch
        {
            "pg" => $"substring(name from '^{prefix.Replace(".", "\\.", StringComparison.Ordinal)}([0-9]+)-')::INT",
            "mssql" => $"TRY_CAST(SUBSTRING(name, {start}, NULLIF(CHARINDEX('-', name, {start}), 0) - {start}) AS INT)",
            _ => $"CAST(substr(name, {start}) AS INTEGER)",
        };
        var newer = $"""
            SELECT 1 FROM {"{{schema}}"}.migrations
            WHERE version > {lastMigration}
                OR (version = {ObjectPackageStamp.HistoryVersion} AND name LIKE '{prefix}%-%' AND {revisionText} > {ObjectPackageStamp.PackageRevision})
            """;
        const string message =
            "A newer Acta release already upgraded this database. Run the newest provisioning script; this one would move it backwards.";
        return token switch
        {
            "pg" => $"""
                DO $$
                BEGIN
                    IF EXISTS (
                {Indent(newer, 8)}
                    ) THEN
                        RAISE EXCEPTION '{message}';
                    END IF;
                END
                $$;
                """,
            "mssql" => $"""
                IF EXISTS (
                {Indent(newer, 4)}
                )
                    THROW 50000, N'{message}', 1;
                """,
            _ => $"""
                CREATE TEMP TABLE release_guard (
                    newer INTEGER CONSTRAINT newer_acta_release_installed_run_the_newest_script CHECK (newer = 0)
                );
                INSERT INTO release_guard
                SELECT EXISTS (
                {Indent(newer, 4)}
                );
                DROP TABLE release_guard;
                """,
        };
    }

    private static string Indent(string text, int spaces) =>
        string.Join("\n", text.Split('\n').Select(line => new string(' ', spaces) + line));

    /// <summary>
    /// The objects one provider installs, in the order the installer applies them: views first, then
    /// routines, each set in resource-name order, named the way the installer names them. Shared with
    /// the object-package hash, which is only meaningful if it covers exactly this set in exactly this
    /// order.
    /// </summary>
    internal static IEnumerable<(string Name, string Body)> SqlObjects(string providerDir, string suffix) =>
        Directory
            .EnumerateFiles(Path.Combine(providerDir, "Sql"), "*" + suffix, SearchOption.AllDirectories)
            .Select(path => (Path: path, Resource: Path.GetRelativePath(providerDir, path).Replace('\\', '.').Replace('/', '.')))
            .OrderBy(f => f.Resource, StringComparer.Ordinal)
            .Select(f =>
                (JsonNamingPolicy.SnakeCaseLower.ConvertName(Path.GetFileName(f.Path)[..^suffix.Length]), File.ReadAllText(f.Path))
            );
}
