SELECT
    d.id AS definition_id,
    ns.name AS namespace,
    d.name AS job_name,
    {{decode:job-definition-status:d.status_code}} AS status,
    d.status_code,
    d.definition_hash,
    d.manifest_generation_at_utc,
    d.input_type_name,
    d.input_format_name,
    d.output_type_name,
    d.output_format_name,
    {{decode:job-priority:d.priority_code_effective}} AS priority,
    d.priority_code_effective AS priority_code,
    d.priority_code AS priority_default_code,
    d.priority_code_override AS priority_override_code,
    d.max_attempts_effective AS max_attempts,
    d.max_attempts AS max_attempts_default,
    d.max_attempts_override,
    d.backoff_effective AS backoff,
    d.backoff AS backoff_default,
    d.backoff_override,
    d.execution_timeout_seconds_effective AS execution_timeout_seconds,
    d.execution_timeout_seconds AS execution_timeout_seconds_default,
    d.execution_timeout_seconds_override,
    d.deadline_seconds_effective AS deadline_seconds,
    d.deadline_seconds AS deadline_seconds_default,
    d.deadline_seconds_override,
    {{decode:deadline-behavior:d.deadline_behavior_code_effective}} AS deadline_behavior,
    d.deadline_behavior_code_effective AS deadline_behavior_code,
    d.deadline_behavior_code AS deadline_behavior_default_code,
    d.deadline_behavior_code_override AS deadline_behavior_override_code,
    d.retention_seconds_effective AS retention_seconds,
    d.retention_seconds AS retention_seconds_default,
    d.retention_seconds_override,
    {{decode:job-audit-level:d.audit_level_code_effective}} AS audit_level,
    d.audit_level_code_effective AS audit_level_code,
    d.audit_level_code AS audit_level_default_code,
    d.audit_level_code_override AS audit_level_override_code,
    {{decode:alert-profile:d.alert_profile_code_effective}} AS alert_profile,
    d.alert_profile_code_effective AS alert_profile_code,
    d.alert_profile_code AS alert_profile_default_code,
    d.alert_profile_code_override AS alert_profile_override_code,
    d.alert_channel_name_effective AS alert_channel_name,
    d.alert_channel_name AS alert_channel_name_default,
    d.alert_channel_name_override,
    d.runbook_url_effective AS runbook_url,
    d.runbook_url AS runbook_url_default,
    d.runbook_url_override,
    d.created_at_utc,
    d.modified_at_utc,
    d.version
FROM {{schema}}.definitions AS d
JOIN {{schema}}.namespaces AS ns ON ns.id = d.namespace_id
