SELECT jd.name,
       jd.manifest_generation_at_utc,
       jd.input_type_name,
       jd.output_type_name,
       jd.input_format_id,
       jd.input_format_name,
       jd.output_format_id,
       jd.output_format_name,
       jd.id,
       jd.definition_hash,
       jd.status_code,
       jd.modified_at_utc,
       jd.priority_code_effective,
       jd.max_attempts_effective,
       jd.backoff_effective,
       jd.execution_timeout_seconds_effective,
       jd.deadline_seconds_effective,
       jd.deadline_behavior_code_effective,
       jd.retention_seconds_effective,
       jd.audit_level_code_effective,
       jd.alert_profile_code_effective,
       jd.alert_channel_name_effective,
       jd.runbook_url_effective
  FROM {{schema}}.definitions jd
 WHERE jd.namespace_id = @p_namespace_id;
