using System.Globalization;
using System.Text;
using Acta.Emit.Shared;

namespace Acta.Emit.Features.Migrations;

/// <summary>
/// Emits <c>src/Acta.Relational/Schema/BaselineStamps.g.cs</c>: the stamp each provider's committed
/// baseline migration carries, as constants the runtime requires at bootstrap. The SQL is the source
/// of truth; this file is how the runtime reads it without parsing migrations at startup.
/// </summary>
internal static class BaselineStampsEmitter
{
    internal static string PathFor(string repoRoot) => Path.Combine(repoRoot, "src", "Acta.Relational", "Schema", "BaselineStamps.g.cs");

    internal static string Emit(string repoRoot)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Written by tools/Acta.Emit (`schema add` / `schema amend`) and verified by `Acta.Emit check`.");
        sb.AppendLine("// Each value is a content hash of that provider's committed baseline migration; edit the SQL,");
        sb.AppendLine("// not this file.");
        sb.AppendLine();
        sb.AppendLine("namespace Acta.Relational.Schema;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// The baseline generation each provider package ships, as recorded in the version-0 row of its");
        sb.AppendLine("/// baseline migration. A database whose history carries a different value was built from another");
        sb.AppendLine("/// generation of the schema and is refused at bootstrap.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class BaselineStamps");
        sb.AppendLine("{");

        foreach (var provider in ProviderCatalog.All)
        {
            var stamp =
                MigrationFiles.BaselineStampFor(repoRoot, provider.Suffix)
                ?? throw new InvalidOperationException(
                    $"Provider '{provider.Token}' has no baseline migration recording a stamp row; run `schema add` before generating {PathFor(repoRoot)}."
                );
            sb.AppendLine(CultureInfo.InvariantCulture, $"    internal const string {MemberName(provider.Token)} = \"{stamp}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>The stamp for one dialect, named by the token the provider hooks carry.</summary>");
        sb.AppendLine("    internal static string ForDialect(string dialectToken) =>");
        sb.AppendLine("        dialectToken switch");
        sb.AppendLine("        {");
        foreach (var provider in ProviderCatalog.All)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            \"{provider.Token}\" => {MemberName(provider.Token)},");
        }
        sb.AppendLine(
            "            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, \"Unknown dialect token.\"),"
        );
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString().ReplaceLineEndings("\n");
    }

    internal static void Write(string repoRoot)
    {
        var path = PathFor(repoRoot);
        File.WriteAllText(path, Emit(repoRoot));
        Console.WriteLine($"  wrote {path}");
    }

    private static string MemberName(string token) => char.ToUpperInvariant(token[0]) + token[1..];
}
