using System.Globalization;
using System.Text;
using Acta.Emit.Shared.Model;
using Acta.Emit.Shared.Sql;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Migrations;

/// <summary>
/// Renders a per-provider delta migration for an additive <see cref="SchemaDiff"/> by reusing the
/// full-schema emitter's fragment renderers against the live model, so a drafted statement matches
/// how the baseline renders the same object. Additive DDL is emitted directly; non-additive changes
/// (drops, renames, routines, views, synthetic checks) are surfaced as `-- WARNING`/`-- TODO` lines
/// for the engineer to hand-edit. The migration self-stamps via <c>MigrationStamp</c> as its last line.
/// </summary>
internal static class MigrationDeltaEmitter
{
    internal static string EmitDelta(SchemaDiff diff, SchemaModel live, SqlDdlDialect dialect, int version, string name)
    {
        var byTable = live.Entities.ToDictionary(e => e.TableName, StringComparer.Ordinal);
        var sb = new StringBuilder();

        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"-- M{version:D3}_{name} ({dialect.ProviderToolName}) delta — generated by Acta.Emit schema add/amend."
        );
        sb.AppendLine("-- Review the WARNING/TODO lines and hand-edit before committing.");
        sb.AppendLine("-- `{{schema}}` is substituted by the migration runner at apply time.");
        foreach (var warning in diff.Warnings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"-- WARNING: {warning}");
        }
        sb.AppendLine();

        // Emit new tables in live (dependency) order, not the diff's alphabetical order, so an inline
        // FK from one new table to another new table is created after its target.
        var addedTables = diff.AddedTables.ToHashSet(StringComparer.Ordinal);
        foreach (var entity in live.Entities.Where(e => addedTables.Contains(e.TableName)))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"-- new table: {entity.TableName}");
            sb.AppendLine(SqlSchemaEmitter.RenderCreateTableForDraft(entity, dialect, live));
            sb.AppendLine();
        }

        foreach (var (table, column) in diff.AddedColumns)
        {
            var col = byTable[table].Columns.First(c => c.Name == column);
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"ALTER TABLE {SqlDdlDialect.SchemaPlaceholder}.{table} ADD {SqlSchemaEmitter.RenderColumn(col, dialect)};"
            );
            if (col.IsCoded)
            {
                var codeSuffix = col.Name.EndsWith("_code", StringComparison.Ordinal) ? "" : "_code";
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"-- TODO: add the synthetic ck_{table}_{col.Name}{codeSuffix} constraint (enum IN-list CHECK) for this coded column (see M001)."
                );
            }
            else if (col.Kind is DbKind.Byte or DbKind.Bytes)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"-- TODO: add the synthetic ck_{table}_{col.Name} {(col.Kind == DbKind.Byte ? "0..255 range" : "octet-length")} constraint for this {col.Kind} column (see M001)."
                );
            }
            if (col.IsGenerated)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"-- TODO: {table}.{col.Name} is a STORED generated column; SQLite cannot ADD one via ALTER TABLE — rebuild the table by hand for the sqlite migration."
                );
            }
            else if (!col.IsNullable && col.Default == DbDefault.None)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"-- TODO: {table}.{col.Name} is NOT NULL with no default; backfill existing rows in the same migration."
                );
            }
        }

        foreach (var (table, index) in diff.AddedIndexes)
        {
            var idx = byTable[table].Indexes.First(i => i.Name == index);
            sb.AppendLine(SqlSchemaEmitter.RenderIndex(table, idx, dialect));
        }

        foreach (var (table, check) in diff.AddedChecks)
        {
            var chk = byTable[table].Checks.First(c => c.Name == check);
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"ALTER TABLE {SqlDdlDialect.SchemaPlaceholder}.{table} ADD CONSTRAINT {chk.Name} CHECK ({chk.Sql});"
            );
        }

        foreach (var (table, fkName) in diff.AddedForeignKeys)
        {
            var fk = byTable[table].ForeignKeys.First(f => f.Name == fkName);
            var targetTable = live.Entities.First(e => e.ClrType == fk.Target).TableName;
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"ALTER TABLE {SqlDdlDialect.SchemaPlaceholder}.{table} ADD CONSTRAINT {fk.Name} FOREIGN KEY ({fk.Column}) REFERENCES {dialect.ForeignKeyTargetTable(targetTable)} ({fk.TargetColumn}){RenderOnDelete(fk.OnDelete)};"
            );
        }

        // Self-stamp so the runner records this version as applied (else it re-runs every boot).
        sb.AppendLine();
        sb.AppendLine(dialect.MigrationStamp(version, name));
        if (dialect.Terminator is { } terminator)
        {
            sb.AppendLine(terminator);
        }

        return sb.ToString();
    }

    private static string RenderOnDelete(DbForeignKeyAction action) =>
        action switch
        {
            DbForeignKeyAction.Cascade => " ON DELETE CASCADE",
            DbForeignKeyAction.SetNull => " ON DELETE SET NULL",
            _ => "",
        };
}
