using System.Globalization;
using System.Text;
using System.Text.Json;
using Acta.Emit.Shared;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Migrations;

/// <summary>
/// Emits <c>src/Acta.Relational/Schema/ObjectPackageHashes.g.cs</c>: the content hash of each provider's
/// installed object set, computed here and frozen into the assembly so the runtime never hashes anything
/// at startup. The SQL is the source of truth; this file is how the installer names what it wrote.
/// </summary>
internal static class ObjectPackageEmitter
{
    internal static string PathFor(string repoRoot) => Path.Combine(repoRoot, "src", "Acta.Relational", "Schema", "ObjectPackageHashes.g.cs");

    /// <summary>
    /// The objects one provider installs, in the order the installer applies them: views first, then
    /// routines, each set in resource-name order. SQLite has no routines, because its mutation SQL ships
    /// inline in the assembly and cannot go stale in a database, so its package is its operator views.
    /// </summary>
    internal static IReadOnlyList<(string Name, string Body)> ObjectsFor(string repoRoot, string suffix)
    {
        var providerDir = Path.Combine(repoRoot, "src", $"Acta.{DirectoryName(suffix)}");
        return [.. Enumerate(providerDir, ".view.sql"), .. Enumerate(providerDir, ".routine.sql")];
    }

    internal static string HashFor(string repoRoot, string suffix) => ObjectPackageStamp.HashOf(ObjectsFor(repoRoot, suffix));

    internal static string Emit(string repoRoot)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Written by tools/Acta.Emit (`objects record`) and verified by `Acta.Emit check`.");
        sb.AppendLine("// Each value is a content hash of that provider's installed views and routines; edit the SQL,");
        sb.AppendLine("// not this file.");
        sb.AppendLine();
        sb.AppendLine("namespace Acta.Relational.Schema;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// The object package each provider package ships, as recorded in the sentinel row its install");
        sb.AppendLine("/// writes. Identity only: the startup verdict reads the major and revision beside it, never this.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class ObjectPackageHashes");
        sb.AppendLine("{");

        foreach (var provider in ProviderCatalog.All)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    internal const string {MemberName(provider.Token)} = \"{HashFor(repoRoot, provider.Suffix)}\";"
            );
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>The hash for one dialect, named by the token the provider hooks carry.</summary>");
        sb.AppendLine("    internal static string ForDialect(string dialectToken) =>");
        sb.AppendLine("        dialectToken switch");
        sb.AppendLine("        {");
        foreach (var provider in ProviderCatalog.All)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            \"{provider.Token}\" => {MemberName(provider.Token)},");
        }
        sb.AppendLine(
            "            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, \"Unknown dialect token.\"),"
        );
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString().ReplaceLineEndings("\n");
    }

    internal static void Write(string repoRoot)
    {
        var path = PathFor(repoRoot);
        File.WriteAllText(path, Emit(repoRoot));
        Console.WriteLine($"  wrote {path}");
    }

    private static List<(string Name, string Body)> Enumerate(string providerDir, string suffix)
    {
        var root = Path.Combine(providerDir, "Sql");
        if (!Directory.Exists(root))
        {
            return [];
        }

        return Directory
            .EnumerateFiles(root, "*" + suffix, SearchOption.AllDirectories)
            .Select(path => (Path: path, Resource: Path.GetRelativePath(providerDir, path).Replace('\\', '.').Replace('/', '.')))
            .OrderBy(f => f.Resource, StringComparer.Ordinal)
            .Select(f =>
                (JsonNamingPolicy.SnakeCaseLower.ConvertName(Path.GetFileName(f.Path)[..^suffix.Length]), File.ReadAllText(f.Path))
            )
            .ToList();
    }

    private static string DirectoryName(string suffix) =>
        suffix switch
        {
            "mssql" => "SqlServer",
            "pg" => "Postgres",
            "sqlite" => "Sqlite",
            _ => throw new ArgumentOutOfRangeException(nameof(suffix), suffix, "Unknown provider suffix."),
        };

    private static string MemberName(string token) => char.ToUpperInvariant(token[0]) + token[1..];
}
