using System.Globalization;
using System.Text;
using Acta.Emit.Features.Docs;
using Acta.Emit.Shared;
using Acta.Relational.Schema;

namespace Acta.Emit.Features.Migrations;

/// <summary>
/// Emits <c>src/Acta.Relational/Schema/ObjectPackageHashes.g.cs</c>: the content hash of each provider's
/// installed object set, computed here and frozen into the assembly so the runtime never hashes anything
/// at startup. The SQL is the source of truth; this file is how the installer names what it wrote.
/// </summary>
internal static class ObjectPackageEmitter
{
    internal static string PathFor(string repoRoot) =>
        Path.Combine(repoRoot, "src", "Acta.Relational", "Schema", "ObjectPackageHashes.g.cs");

    /// <summary>
    /// One hash per provider token, computed once per command. SQLite has no routines, because its
    /// mutation SQL ships inline in the assembly and cannot go stale in a database, so its package is its
    /// operator views.
    /// </summary>
    internal static IReadOnlyDictionary<string, string> HashAll(string repoRoot) =>
        ProviderCatalog.All.ToDictionary(p => p.Token, p => HashFor(repoRoot, p), StringComparer.Ordinal);

    private static string HashFor(string repoRoot, ProviderInfo provider)
    {
        var providerDir = Path.Combine(repoRoot, "src", provider.Project);
        return ObjectPackageStamp.HashOf([
            .. ProvisionScriptEmitter.SqlObjects(providerDir, ".view.sql"),
            .. ProvisionScriptEmitter.SqlObjects(providerDir, ".routine.sql"),
        ]);
    }

    internal static string Emit(IReadOnlyDictionary<string, string> hashes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Written by tools/Acta.Emit (`objects record`) and verified by `Acta.Emit check`.");
        sb.AppendLine("// Each value is a content hash of that provider's installed views and routines; edit the SQL,");
        sb.AppendLine("// not this file.");
        sb.AppendLine();
        sb.AppendLine("namespace Acta.Relational.Schema;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// The object package each provider package ships, as recorded in the sentinel row its install");
        sb.AppendLine("/// writes. Identity only: the startup verdict reads the major and revision beside it, never this.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class ObjectPackageHashes");
        sb.AppendLine("{");

        foreach (var provider in ProviderCatalog.All)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"    internal const string {MemberName(provider.Token)} = \"{hashes[provider.Token]}\";"
            );
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>The hash for one dialect, named by the token the provider hooks carry.</summary>");
        sb.AppendLine("    internal static string ForDialect(string dialectToken) =>");
        sb.AppendLine("        dialectToken switch");
        sb.AppendLine("        {");
        foreach (var provider in ProviderCatalog.All)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            \"{provider.Token}\" => {MemberName(provider.Token)},");
        }
        sb.AppendLine(
            "            _ => throw new ArgumentOutOfRangeException(nameof(dialectToken), dialectToken, \"Unknown dialect token.\"),"
        );
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString().ReplaceLineEndings("\n");
    }

    internal static void Write(string repoRoot, IReadOnlyDictionary<string, string> hashes)
    {
        var path = PathFor(repoRoot);
        File.WriteAllText(path, Emit(hashes));
        Console.WriteLine($"  wrote {path}");
    }

    private static string MemberName(string token) => char.ToUpperInvariant(token[0]) + token[1..];
}
