-- M001_init (mssql): full schema baseline generated by Acta.Emit. Hand-edit only as a delta.
-- Schema placeholder `{{schema}}` is substituted by the migration runner at apply time.
-- Routine and view bodies are not baked in: the SQL object installer applies them after migrations.

IF SCHEMA_ID('{{schema}}') IS NULL EXEC('CREATE SCHEMA {{schema}}');
GO

-- JobAlert
IF OBJECT_ID(N'{{schema}}.alerts', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.alerts (
    id bigint IDENTITY(1,1) NOT NULL,
    namespace_id smallint NOT NULL,
    job_id bigint NULL,
    job_ref uniqueidentifier NULL,
    origin_code tinyint NOT NULL,
    severity_code tinyint NOT NULL,
    kind_code tinyint NOT NULL,
    title nvarchar(512) NOT NULL,
    message nvarchar(512) NOT NULL,
    channel_name varchar(128) NOT NULL,
    dedupe_key varchar(512) NULL,
    dedupe_window_start_utc datetime2(3) NULL,
    occurrence_count int NOT NULL,
    resolved_at_utc datetime2(3) NULL,
    acknowledged_at_utc datetime2(3) NULL,
    delivery_status_code tinyint NOT NULL,
    retry_count tinyint NOT NULL,
    retry_after_utc datetime2(3) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_alerts PRIMARY KEY (id)
    , CONSTRAINT ck_alerts_job_ref_pair CHECK ((job_id IS NULL AND job_ref IS NULL) OR (job_id IS NOT NULL AND job_ref IS NOT NULL))
    , CONSTRAINT ck_alerts_dedupe_pair CHECK ((dedupe_key IS NULL AND dedupe_window_start_utc IS NULL) OR (dedupe_key IS NOT NULL AND dedupe_window_start_utc IS NOT NULL))
    , CONSTRAINT ck_alerts_occurrence_count CHECK (occurrence_count >= 1)
    , CONSTRAINT ck_alerts_origin_code CHECK (origin_code IN (10, 20))
    , CONSTRAINT ck_alerts_severity_code CHECK (severity_code IN (10, 20, 30, 40))
    , CONSTRAINT ck_alerts_delivery_status_code CHECK (delivery_status_code IN (10, 20, 30, 100, 200))
);
CREATE INDEX ix_alerts_delivery_due ON {{schema}}.alerts (namespace_id, delivery_status_code, retry_after_utc, id);
CREATE INDEX ix_alerts_namespace_created ON {{schema}}.alerts (namespace_id, created_at_utc DESC, id DESC);
CREATE INDEX ix_alerts_namespace_unresolved ON {{schema}}.alerts (namespace_id, created_at_utc DESC, id DESC) WHERE resolved_at_utc IS NULL;
CREATE UNIQUE INDEX ux_alerts_dedupe ON {{schema}}.alerts (namespace_id, dedupe_key, dedupe_window_start_utc) WHERE dedupe_key IS NOT NULL;
END
GO

-- JobDefinition
IF OBJECT_ID(N'{{schema}}.definitions', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.definitions (
    id int IDENTITY(1,1) NOT NULL,
    namespace_id smallint NOT NULL,
    name varchar(128) NOT NULL,
    status_code tinyint NOT NULL,
    definition_hash varchar(128) NOT NULL,
    manifest_generation_at_utc datetime2(3) NOT NULL,
    input_type_name varchar(512) NOT NULL,
    input_format_id tinyint NOT NULL,
    input_format_name varchar(128) NOT NULL,
    output_type_name varchar(512) NULL,
    output_format_id tinyint NOT NULL,
    output_format_name varchar(128) NOT NULL,
    tenant_requirement_code tinyint NOT NULL,
    priority_code tinyint NOT NULL,
    priority_code_override tinyint NULL,
    priority_code_effective AS (COALESCE(priority_code_override, priority_code)) PERSISTED,
    max_attempts smallint NOT NULL,
    max_attempts_override smallint NULL,
    max_attempts_effective AS (COALESCE(max_attempts_override, max_attempts)) PERSISTED,
    backoff nvarchar(64) NOT NULL,
    backoff_override nvarchar(64) NULL,
    backoff_effective AS (COALESCE(backoff_override, backoff)) PERSISTED,
    execution_timeout_seconds int NOT NULL,
    execution_timeout_seconds_override int NULL,
    execution_timeout_seconds_effective AS (COALESCE(execution_timeout_seconds_override, execution_timeout_seconds)) PERSISTED,
    deadline_seconds int NOT NULL,
    deadline_seconds_override int NULL,
    deadline_seconds_effective AS (COALESCE(deadline_seconds_override, deadline_seconds)) PERSISTED,
    deadline_behavior_code tinyint NOT NULL,
    deadline_behavior_code_override tinyint NULL,
    deadline_behavior_code_effective AS (COALESCE(deadline_behavior_code_override, deadline_behavior_code)) PERSISTED,
    retention_seconds int NOT NULL,
    retention_seconds_override int NULL,
    retention_seconds_effective AS (COALESCE(retention_seconds_override, retention_seconds)) PERSISTED,
    audit_level_code tinyint NOT NULL,
    audit_level_code_override tinyint NULL,
    audit_level_code_effective AS (COALESCE(audit_level_code_override, audit_level_code)) PERSISTED,
    alert_profile_code tinyint NOT NULL,
    alert_profile_code_override tinyint NULL,
    alert_profile_code_effective AS (COALESCE(alert_profile_code_override, alert_profile_code)) PERSISTED,
    alert_channel_name varchar(128) NULL,
    alert_channel_name_override varchar(128) NULL,
    alert_channel_name_effective AS (COALESCE(alert_channel_name_override, alert_channel_name)) PERSISTED,
    runbook_url varchar(512) NULL,
    runbook_url_override varchar(512) NULL,
    runbook_url_effective AS (COALESCE(runbook_url_override, runbook_url)) PERSISTED,
    display_name nvarchar(128) NULL,
    display_name_override nvarchar(128) NULL,
    display_name_effective AS (COALESCE(display_name_override, display_name)) PERSISTED,
    description nvarchar(512) NULL,
    description_override nvarchar(512) NULL,
    description_effective AS (COALESCE(description_override, description)) PERSISTED,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_definitions PRIMARY KEY (id)
    , CONSTRAINT ck_definitions_max_attempts CHECK (max_attempts >= 1)
    , CONSTRAINT ck_definitions_max_attempts_override CHECK (max_attempts_override IS NULL OR max_attempts_override >= 1)
    , CONSTRAINT ck_definitions_execution_timeout CHECK (execution_timeout_seconds > 0)
    , CONSTRAINT ck_definitions_execution_timeout_override CHECK (execution_timeout_seconds_override IS NULL OR execution_timeout_seconds_override > 0)
    , CONSTRAINT ck_definitions_deadline CHECK (deadline_seconds >= 0)
    , CONSTRAINT ck_definitions_deadline_override CHECK (deadline_seconds_override IS NULL OR deadline_seconds_override >= 0)
    , CONSTRAINT ck_definitions_retention CHECK (retention_seconds >= 0)
    , CONSTRAINT ck_definitions_retention_override CHECK (retention_seconds_override IS NULL OR retention_seconds_override >= 0)
    , CONSTRAINT ck_definitions_status_code CHECK (status_code IN (10, 240))
    , CONSTRAINT ck_definitions_tenant_requirement_code CHECK (tenant_requirement_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_priority_code_override CHECK (priority_code_override IS NULL OR priority_code_override IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_deadline_behavior_code CHECK (deadline_behavior_code IN (10, 20))
    , CONSTRAINT ck_definitions_deadline_behavior_code_override CHECK (deadline_behavior_code_override IS NULL OR deadline_behavior_code_override IN (10, 20))
    , CONSTRAINT ck_definitions_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_audit_level_code_override CHECK (audit_level_code_override IS NULL OR audit_level_code_override IN (0, 10, 20))
    , CONSTRAINT ck_definitions_alert_profile_code CHECK (alert_profile_code IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_alert_profile_code_override CHECK (alert_profile_code_override IS NULL OR alert_profile_code_override IN (0, 10, 20, 30, 40))
);
CREATE UNIQUE INDEX ux_definitions_namespace_name ON {{schema}}.definitions (namespace_id, name);
END
GO

-- JobEvent
IF OBJECT_ID(N'{{schema}}.events', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.events (
    id bigint IDENTITY(1,1) NOT NULL,
    event_code tinyint NOT NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    namespace_id smallint NOT NULL,
    actor_code tinyint NOT NULL,
    actor_key varchar(128) NULL,
    job_id bigint NULL,
    job_ref uniqueidentifier NULL,
    execution_number int NULL,
    lineage_root_id bigint NULL,
    definition_id int NULL,
    tenant_id int NULL,
    worker_id int NULL,
    from_status_code tinyint NULL,
    to_status_code tinyint NULL,
    execution_status_code tinyint NULL,
    duration_ms int NULL,
    reason_code tinyint NULL,
    reason_message nvarchar(512) NULL,
    detail_format_id tinyint DEFAULT 0 NOT NULL,
    detail varbinary(max) NULL
    , CONSTRAINT pk_events PRIMARY KEY (id) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON)
    , CONSTRAINT ck_events_detail_pair CHECK ((detail_format_id = 0 AND detail IS NULL) OR (detail_format_id <> 0 AND detail IS NOT NULL))
    , CONSTRAINT ck_events_actor_code CHECK (actor_code IN (10, 20, 50, 70))
    , CONSTRAINT ck_events_from_status_code CHECK (from_status_code IS NULL OR from_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_to_status_code CHECK (to_status_code IS NULL OR to_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_execution_status_code CHECK (execution_status_code IS NULL OR execution_status_code IN (50, 100, 150, 151, 152, 200, 220, 230))
) WITH (DATA_COMPRESSION = PAGE);
CREATE INDEX ix_events_lineage_timeline ON {{schema}}.events (lineage_root_id, created_at_utc, id) WHERE lineage_root_id IS NOT NULL;
CREATE INDEX ix_events_namespace_timeline ON {{schema}}.events (namespace_id, event_code, created_at_utc, id);
CREATE INDEX ix_events_job_timeline ON {{schema}}.events (job_id, created_at_utc, id) WHERE job_id IS NOT NULL;
CREATE INDEX ix_events_namespace_created ON {{schema}}.events (namespace_id, created_at_utc DESC, id DESC);
END
GO

-- Job
IF OBJECT_ID(N'{{schema}}.jobs', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.jobs (
    id bigint IDENTITY(1,1) NOT NULL,
    job_ref uniqueidentifier NOT NULL,
    namespace_id smallint NOT NULL,
    definition_id int NOT NULL,
    lineage_root_id bigint NULL,
    parent_id bigint NULL,
    tenant_id int NULL,
    deduplication_key varchar(128) NULL,
    correlation_key varchar(64) NULL,
    exclusive_key varchar(128) NULL,
    input_format_id tinyint NOT NULL,
    input varbinary(max) NULL,
    audit_level_code tinyint NOT NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL
    , CONSTRAINT pk_jobs PRIMARY KEY (id) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON)
    , CONSTRAINT ck_jobs_input_pair CHECK ((input_format_id = 0 AND input IS NULL) OR (input_format_id <> 0 AND input IS NOT NULL))
    , CONSTRAINT ck_jobs_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
);
CREATE INDEX ix_jobs_parent ON {{schema}}.jobs (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX ix_jobs_namespace_created ON {{schema}}.jobs (namespace_id, created_at_utc DESC, id DESC);
CREATE UNIQUE INDEX ux_jobs_ref ON {{schema}}.jobs (job_ref);
CREATE UNIQUE INDEX ux_jobs_deduplication_key_root ON {{schema}}.jobs (namespace_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NULL;
CREATE UNIQUE INDEX ux_jobs_deduplication_key_child ON {{schema}}.jobs (parent_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NOT NULL;
END
GO

-- Lock
IF OBJECT_ID(N'{{schema}}.locks', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.locks (
    lock_key varchar(256) NOT NULL,
    job_id bigint NOT NULL,
    expires_at_utc datetime2(3) NOT NULL,
    hold_token uniqueidentifier NOT NULL
    , CONSTRAINT pk_locks PRIMARY KEY (lock_key)
);
CREATE INDEX ix_locks_reclaim_expired ON {{schema}}.locks (expires_at_utc);
END
GO

-- JobNamespace
IF OBJECT_ID(N'{{schema}}.namespaces', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.namespaces (
    id smallint IDENTITY(1,1) NOT NULL,
    name varchar(128) NOT NULL,
    owner_team nvarchar(512) NULL,
    description nvarchar(512) NULL,
    status_code tinyint NOT NULL,
    catalog_hash varchar(128) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_namespaces PRIMARY KEY (id)
    , CONSTRAINT ck_namespaces_status_code CHECK (status_code IN (10, 20))
);
CREATE UNIQUE INDEX ux_namespaces_name ON {{schema}}.namespaces (name);
END
GO

-- Seed: reserved system namespace (id=1, 'sys') for cross-namespace audit events. Collation-neutral.
IF NOT EXISTS (SELECT 1 FROM {{schema}}.namespaces WHERE id = 1)
BEGIN
    SET IDENTITY_INSERT {{schema}}.namespaces ON;
    INSERT INTO {{schema}}.namespaces (id, name, status_code, description, created_at_utc, modified_at_utc)
    VALUES (1, N'sys', 10, N'Reserved system namespace for cross-namespace audit events.', SYSUTCDATETIME(), SYSUTCDATETIME());
    SET IDENTITY_INSERT {{schema}}.namespaces OFF;
END
GO

-- JobResult
IF OBJECT_ID(N'{{schema}}.results', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.results (
    job_id bigint NOT NULL,
    execution_number int NOT NULL,
    result_format_id tinyint NOT NULL,
    result varbinary(max) NOT NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL
    , CONSTRAINT pk_results PRIMARY KEY (job_id, execution_number)
    , CONSTRAINT ck_results_format_not_none CHECK (result_format_id <> 0)
    , CONSTRAINT fk_results_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
) WITH (DATA_COMPRESSION = PAGE);
END
GO

-- JobRuntime
IF OBJECT_ID(N'{{schema}}.runtimes', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.runtimes (
    job_id bigint NOT NULL,
    namespace_id smallint NOT NULL,
    status_code tinyint NOT NULL,
    priority_code tinyint NOT NULL,
    next_run_at_utc datetime2(3) NULL,
    execution_number int NOT NULL,
    failure_count smallint NOT NULL,
    leased_by_worker_id int NULL,
    lease_expires_at_utc datetime2(3) NULL,
    retention_until_utc datetime2(3) NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_runtimes PRIMARY KEY (job_id) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY = ON)
    , CONSTRAINT ck_runtimes_lease_consistency CHECK ((leased_by_worker_id IS NULL AND lease_expires_at_utc IS NULL) OR (leased_by_worker_id IS NOT NULL AND lease_expires_at_utc IS NOT NULL))
    , CONSTRAINT ck_runtimes_counters CHECK (execution_number >= 0 AND failure_count >= 0)
    , CONSTRAINT ck_runtimes_status_code CHECK (status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_runtimes_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT fk_runtimes_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);
CREATE INDEX ix_runtimes_claim_ready ON {{schema}}.runtimes (namespace_id, priority_code DESC, next_run_at_utc, job_id) WHERE status_code = 10;
CREATE INDEX ix_runtimes_retention ON {{schema}}.runtimes (namespace_id, retention_until_utc, job_id) WHERE retention_until_utc IS NOT NULL AND status_code IN (100, 200, 220);
CREATE INDEX ix_runtimes_worker_inflight ON {{schema}}.runtimes (leased_by_worker_id, status_code) WHERE leased_by_worker_id IS NOT NULL AND status_code IN (40, 50);
END
GO

-- JobSchedule
IF OBJECT_ID(N'{{schema}}.schedules', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.schedules (
    id bigint IDENTITY(1,1) NOT NULL,
    namespace_id smallint NOT NULL,
    job_id bigint NOT NULL,
    definition_id int NOT NULL,
    name varchar(128) NOT NULL,
    origin_code tinyint NOT NULL,
    expression varchar(128) NOT NULL,
    expression_override varchar(128) NULL,
    expression_effective AS (COALESCE(expression_override, expression)) PERSISTED,
    time_zone_id varchar(128) NOT NULL,
    time_zone_id_override varchar(128) NULL,
    time_zone_id_effective AS (COALESCE(time_zone_id_override, time_zone_id)) PERSISTED,
    expression_kind_code tinyint NOT NULL,
    misfire_strategy_code tinyint NOT NULL,
    next_run_at_utc datetime2(3) NULL,
    last_occurrence_at_utc datetime2(3) NULL,
    status_code tinyint NOT NULL,
    paused_until_utc datetime2(3) NULL,
    description nvarchar(512) NULL,
    reason_message nvarchar(512) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_schedules PRIMARY KEY (id)
    , CONSTRAINT ck_schedules_paused_pair CHECK (status_code = 30 OR paused_until_utc IS NULL)
    , CONSTRAINT ck_schedules_orphan_origin CHECK (origin_code = 40 OR status_code <> 230)
    , CONSTRAINT ck_schedules_origin_code CHECK (origin_code IN (20, 40))
    , CONSTRAINT ck_schedules_expression_kind_code CHECK (expression_kind_code IN (10, 20))
    , CONSTRAINT ck_schedules_misfire_strategy_code CHECK (misfire_strategy_code IN (10, 20))
    , CONSTRAINT ck_schedules_status_code CHECK (status_code IN (10, 30, 230))
    , CONSTRAINT fk_schedules_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
    , CONSTRAINT fk_schedules_definitions FOREIGN KEY (definition_id) REFERENCES {{schema}}.definitions (id)
);
CREATE INDEX ix_schedules_namespace_next ON {{schema}}.schedules (namespace_id, next_run_at_utc, id) WHERE status_code <> 230;
CREATE UNIQUE INDEX ux_schedules_job_name ON {{schema}}.schedules (job_id, name);
END
GO

-- Setting
IF OBJECT_ID(N'{{schema}}.settings', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.settings (
    id int IDENTITY(1,1) NOT NULL,
    scope_code tinyint NOT NULL,
    scope_id int NULL,
    name varchar(128) NOT NULL,
    value_format_id tinyint NOT NULL,
    value varbinary(max) NULL,
    description nvarchar(512) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_settings PRIMARY KEY (id)
    , CONSTRAINT ck_settings_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_settings_scope_code CHECK (scope_code IN (10, 30, 40))
);
CREATE UNIQUE INDEX ux_settings_scope_name ON {{schema}}.settings (scope_code, scope_id, name) WHERE scope_id IS NOT NULL;
CREATE UNIQUE INDEX ux_settings_global_name ON {{schema}}.settings (scope_code, name) WHERE scope_id IS NULL;
END
GO

-- JobStep
IF OBJECT_ID(N'{{schema}}.steps', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.steps (
    id bigint IDENTITY(1,1) NOT NULL,
    job_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    status_code tinyint NOT NULL,
    attempt_number smallint NOT NULL,
    next_retry_at_utc datetime2(3) NULL,
    reason_code tinyint NULL,
    reason_message nvarchar(512) NULL,
    result_format_id tinyint NOT NULL,
    result varbinary(max) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_steps PRIMARY KEY (id)
    , CONSTRAINT ck_steps_result_pair CHECK ((result_format_id = 0 AND result IS NULL) OR (result_format_id <> 0 AND result IS NOT NULL))
    , CONSTRAINT ck_steps_attempt_number CHECK (attempt_number >= 1)
    , CONSTRAINT ck_steps_status_code CHECK (status_code IN (10, 100, 200, 230))
    , CONSTRAINT fk_steps_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ux_steps_job_name ON {{schema}}.steps (job_id, name);
END
GO

-- Tag
IF OBJECT_ID(N'{{schema}}.tags', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.tags (
    scope_code tinyint NOT NULL,
    scope_id bigint NOT NULL,
    namespace_id smallint NULL,
    name varchar(128) NOT NULL,
    value nvarchar(128) NULL,
    value_search nvarchar(128) NULL
    , CONSTRAINT pk_tags PRIMARY KEY (scope_code, scope_id, name)
    , CONSTRAINT ck_tags_scope_id CHECK (scope_id > 0)
    , CONSTRAINT ck_tags_namespace_id CHECK (namespace_id IS NULL OR namespace_id > 0)
    , CONSTRAINT ck_tags_scope_namespace CHECK ((scope_code = 20 AND namespace_id IS NULL) OR (scope_code = 30 AND namespace_id IS NOT NULL AND scope_id = namespace_id) OR (scope_code IN (40, 50, 60, 70, 80, 90) AND namespace_id IS NOT NULL))
    , CONSTRAINT ck_tags_value_search CHECK ((value IS NULL AND value_search IS NULL) OR (value IS NOT NULL AND value_search IS NOT NULL))
    , CONSTRAINT ck_tags_scope_code CHECK (scope_code IN (20, 30, 40, 50, 60, 70, 80, 90))
);
CREATE INDEX ix_tags_namespace_name_value_search ON {{schema}}.tags (namespace_id, name, value_search, scope_code, scope_id);
END
GO

-- Tenant
IF OBJECT_ID(N'{{schema}}.tenants', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.tenants (
    id int IDENTITY(1,1) NOT NULL,
    tenant_key varchar(128) NOT NULL,
    status_code tinyint NOT NULL,
    display_name nvarchar(128) NULL,
    description nvarchar(512) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_tenants PRIMARY KEY (id)
    , CONSTRAINT ck_tenants_status_code CHECK (status_code IN (10, 20))
);
CREATE UNIQUE INDEX ux_tenants_key ON {{schema}}.tenants (tenant_key);
END
GO

-- JobWorker
IF OBJECT_ID(N'{{schema}}.workers', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.workers (
    id int IDENTITY(1,1) NOT NULL,
    namespace_id smallint NOT NULL,
    status_code tinyint NOT NULL,
    deployment_version varchar(128) NOT NULL,
    host varchar(256) NOT NULL,
    engine_version varchar(128) NULL,
    dotnet_version varchar(64) NULL,
    process_id int NULL,
    max_concurrency int NOT NULL,
    last_seen_at_utc datetime2(3) NOT NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_workers PRIMARY KEY (id)
    , CONSTRAINT ck_workers_max_concurrency CHECK (max_concurrency > 0)
    , CONSTRAINT ck_workers_status_code CHECK (status_code IN (10, 80, 100, 200))
    , CONSTRAINT fk_workers_namespaces FOREIGN KEY (namespace_id) REFERENCES {{schema}}.namespaces (id)
);
CREATE INDEX ix_workers_namespace_status_last_seen ON {{schema}}.workers (namespace_id, status_code, last_seen_at_utc);
CREATE INDEX ix_workers_status_last_seen ON {{schema}}.workers (status_code, last_seen_at_utc);
CREATE INDEX ix_workers_namespace_last_seen ON {{schema}}.workers (namespace_id, last_seen_at_utc DESC, id DESC);
END
GO

-- JobCheckpoint
IF OBJECT_ID(N'{{schema}}.checkpoints', N'U') IS NULL
BEGIN
CREATE TABLE {{schema}}.checkpoints (
    job_id bigint NOT NULL,
    kind_code tinyint NOT NULL,
    name varchar(128) NOT NULL,
    status_code tinyint NULL,
    due_at_utc datetime2(3) NULL,
    value_format_id tinyint DEFAULT 0 NOT NULL,
    value varbinary(max) NULL,
    created_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    modified_at_utc datetime2(3) DEFAULT SYSUTCDATETIME() NOT NULL,
    version int DEFAULT 0 NOT NULL
    , CONSTRAINT pk_checkpoints PRIMARY KEY (job_id, kind_code, name)
    , CONSTRAINT ck_checkpoints_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_checkpoints_kind_code CHECK (kind_code IN (10, 20, 30, 40, 50))
    , CONSTRAINT ck_checkpoints_status_code CHECK (status_code IS NULL OR status_code IN (10, 20, 100))
    , CONSTRAINT fk_checkpoints_jobs FOREIGN KEY (job_id) REFERENCES {{schema}}.jobs (id) ON DELETE CASCADE
);
END
GO

-- TVP table types used by hot-path routines + their batched parameters.

-- Per-row enqueue batch: one row per Job to enqueue (1..5000 per call).
-- Consumed by acta.enqueue_batch's @p_batch sproc parameter.
IF TYPE_ID(N'{{schema}}.job_enqueue_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_enqueue_batch AS TABLE (
    ordinal           INT              NOT NULL,
    job_ref           UNIQUEIDENTIFIER NOT NULL,
    namespace_name    VARCHAR(128)     NOT NULL,
    job_name          VARCHAR(128)     NOT NULL,
    deduplication_key        VARCHAR(128)     NULL,
    correlation_key    VARCHAR(64)      NULL,
    priority_override TINYINT          NULL,
    input_format_id   TINYINT          NOT NULL,
    input             VARBINARY(MAX)   NULL,
    exclusive_key   VARCHAR(128)     NULL,
    next_run_at_utc   DATETIME2(3)     NULL,
    delay_seconds     INT              NULL,
    parent_id         BIGINT           NULL,
    tenant_key        VARCHAR(128)     NULL,
    tenant_override   BIT              NOT NULL,
    PRIMARY KEY (ordinal)
);');
GO

-- Per-tag enqueue batch: zero-or-more rows per Job, joined to the main batch by ordinal.
-- Consumed by acta.enqueue_batch's @p_tag_batch sproc parameter.
IF TYPE_ID(N'{{schema}}.job_enqueue_tag_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_enqueue_tag_batch AS TABLE (
    ordinal INT          NOT NULL,
    name    VARCHAR(128) NOT NULL,
    value   NVARCHAR(128) NULL,
    value_search NVARCHAR(128) NULL,
    PRIMARY KEY (ordinal, name)
);');
GO

-- Per-definition registration batch: one row per [Job] descriptor under a single namespace.
-- Consumed by acta.register_job_definitions's @p_definitions sproc parameter (one round trip per
-- worker regardless of definition count). name is the per-namespace natural key.
IF TYPE_ID(N'{{schema}}.job_definition_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_definition_batch AS TABLE (
    name                                 VARCHAR(128)  NOT NULL,
    priority_code                        TINYINT       NOT NULL,
    max_attempts                         SMALLINT      NOT NULL,
    backoff                              NVARCHAR(64)  NOT NULL,
    execution_timeout_seconds            INT           NOT NULL,
    deadline_seconds                     INT           NOT NULL,
    deadline_behavior_code               TINYINT       NOT NULL,
    retention_seconds                    INT           NOT NULL,
    input_type_name                      VARCHAR(512)  NOT NULL,
    output_type_name                     VARCHAR(512)  NULL,
    input_format_id                      TINYINT       NOT NULL,
    input_format_name                    VARCHAR(128)  NOT NULL,
    output_format_id                     TINYINT       NOT NULL,
    output_format_name                   VARCHAR(128)  NOT NULL,
    audit_level_code                     TINYINT       NOT NULL,
    alert_profile_code                   TINYINT       NOT NULL,
    alert_channel_name                   VARCHAR(128)  NULL,
    runbook_url                          VARCHAR(512)  NULL,
    display_name                         NVARCHAR(128) NULL,
    description                          NVARCHAR(512) NULL,
    definition_hash                      VARCHAR(128)  NOT NULL,
    tenant_requirement_code              TINYINT       NOT NULL,
    PRIMARY KEY (name)
);');
GO

-- Per-schedule cursor advances applied by acta.complete_execution on a recurring slot fire.
-- One row per due schedule; next_run_at_utc NULL clears the cursor (schedule exhausted).
IF TYPE_ID(N'{{schema}}.job_schedule_advance_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_schedule_advance_batch AS TABLE (
    schedule_id     BIGINT       NOT NULL PRIMARY KEY,
    next_run_at_utc DATETIME2(3) NULL
);');
GO

-- Per-row group-committed completion batch: one row per simple terminal completion under the
-- Bulk execution profile. Consumed by acta.complete_executions_batch's @p_batch sproc parameter.
IF TYPE_ID(N'{{schema}}.complete_executions_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.complete_executions_batch AS TABLE (
    ordinal           INT            NOT NULL PRIMARY KEY,
    job_id            BIGINT         NOT NULL,
    worker_id         INT            NOT NULL,
    execution_number  INT            NOT NULL,
    succeeded         BIT            NOT NULL,
    duration_ms       INT            NULL,
    reason_code       TINYINT        NULL,
    reason_message    NVARCHAR(512)  NULL,
    result_format_id  TINYINT        NOT NULL,
    result            VARBINARY(MAX) NULL,
    failure_count     SMALLINT       NULL,
    retention_seconds INT            NULL
);');
GO

-- Per-definition recurring slot batch: one row per definition reconciled in a single
-- acta.register_scheduled_jobs call (all definitions share one namespace, passed as a scalar).
-- deduplication_key is the slot job's natural key (the job name).
IF TYPE_ID(N'{{schema}}.job_schedule_slot_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_schedule_slot_batch AS TABLE (
    definition_id    INT              NOT NULL PRIMARY KEY,
    job_ref              UNIQUEIDENTIFIER NOT NULL,
    deduplication_key           VARCHAR(128)     NOT NULL,
    input_format_id      TINYINT        NOT NULL,
    input                VARBINARY(MAX) NULL,
    audit_level_code     TINYINT        NOT NULL,
    slot_status_code     TINYINT        NOT NULL,
    slot_next_run_at_utc DATETIME2(3)   NULL
);');
GO

-- All definitions' reconciled schedules for one acta.register_scheduled_jobs call, tagged with
-- definition_id so each schedule links to its definition's slot. next_run_at_utc is the
-- C#-computed cursor; description is the optional operator note.
IF TYPE_ID(N'{{schema}}.job_schedule_upsert_batch') IS NULL
EXEC(N'CREATE TYPE {{schema}}.job_schedule_upsert_batch AS TABLE (
    definition_id             INT          NOT NULL,
    name                          VARCHAR(128) NOT NULL,
    expression                    VARCHAR(128) NOT NULL,
    time_zone_id                  VARCHAR(128) NOT NULL,
    expression_kind_code          TINYINT      NOT NULL,
    misfire_strategy_code         TINYINT      NOT NULL,
    next_run_at_utc               DATETIME2(3) NULL,
    description                   NVARCHAR(512) NULL,
    PRIMARY KEY (definition_id, name)
);');
GO


IF NOT EXISTS (SELECT 1 FROM {{schema}}.migrations WHERE version = 0)
INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (0, 'init-locks-hold-token-v1', '{{schema}}');
IF NOT EXISTS (SELECT 1 FROM {{schema}}.migrations WHERE version = 1)
INSERT INTO {{schema}}.migrations (version, name, installed_schema)
VALUES (1, 'init', '{{schema}}');
GO
