using System.Reflection;
using System.Text;
using Xunit;

namespace Acta.Tests.Contracts;

/// <summary>
/// The public API baseline. Schema and persisted codes have had mechanical drift gates for a while;
/// the .NET surface had none, so <c>docs/internals/design.md</c>'s promise to close "the public,
/// physical, and numeric vocabulary together" at 1.0 was unenforceable. This renders every exported
/// type and member of the shipped assemblies into one ordered text file and fails when it moves.
/// </summary>
/// <remarks>
/// Deliberately not <c>Microsoft.CodeAnalysis.PublicApiAnalyzers</c>: that wants two tracked files
/// per project. This mirrors the idiom already in the repo (<see cref="PersistedCodeContractTests"/>
/// for the baseline, <c>DocsContractTests</c> for emit-on-demand), so there is one file and one test.
/// Regenerate after an intended change:
/// <c>ACTA_EMIT_API=1 dotnet test tests/Acta.Tests --filter PublicApiContractTests</c>, then read the
/// diff before committing it - that diff is the point of the gate.
/// </remarks>
public sealed class PublicApiContractTests
{
    // The packable assemblies a consumer compiles against. Acta.Relational is absent on purpose:
    // ArchitectureBoundaryTests already asserts it exports no public types.
    private static readonly string[] ShippedAssemblies =
    [
        "Acta.dll",
        "Acta.Runtime.dll",
        "Acta.AspNetCore.dll",
        "Acta.Postgres.dll",
        "Acta.SqlServer.dll",
        "Acta.Sqlite.dll",
        "Acta.Redis.dll",
        "Acta.Testing.dll",
    ];

    private const string BaselineFile = "tests/Acta.Tests/Contracts/PublicApiSurface.approved.txt";

    [Fact]
    public void Public_api_surface_matches_the_committed_baseline()
    {
        var actual = RenderSurface();
        var path = Path.Combine(ResolveRepoRoot(), BaselineFile.Replace('/', Path.DirectorySeparatorChar));

        if (Environment.GetEnvironmentVariable("ACTA_EMIT_API") == "1")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, actual);
        }

        Assert.True(File.Exists(path), $"{BaselineFile} missing: run with ACTA_EMIT_API=1.");
        Assert.Equal(File.ReadAllText(path).ReplaceLineEndings("\n"), actual.ReplaceLineEndings("\n"));
    }

    private static string RenderSurface()
    {
        var sb = new StringBuilder();
        sb.Append("# Acta public API surface\n");
        sb.Append("# Generated by PublicApiContractTests. Regenerate with ACTA_EMIT_API=1.\n");
        sb.Append("# Every line here is a 1.0 commitment: additive in 1.x, breaking only in 2.0.\n");

        foreach (var file in ShippedAssemblies.Order(StringComparer.Ordinal))
        {
            var assembly = Assembly.LoadFrom(Path.Combine(AppContext.BaseDirectory, file));
            sb.Append('\n').Append("## ").Append(assembly.GetName().Name).Append('\n');

            // Types with unspeakable metadata names (they contain '<': the compiler's string-switch
            // hash-lookup classes nested in the generated *CodeExtensions) are exported but not API:
            // no consumer can reference them, they carry no [CompilerGenerated] marker, and their
            // names are content hashes - so without this filter an edit to a [Code] description
            // string moves this baseline and trains a reflexive re-approve on the one gate whose
            // whole value is a human reading the diff.
            foreach (
                var type in assembly
                    .GetExportedTypes()
                    .Where(t => !t.Name.Contains('<', StringComparison.Ordinal))
                    .OrderBy(t => t.FullName, StringComparer.Ordinal)
            )
            {
                sb.Append(Describe(type)).Append('\n');
                foreach (var member in Members(type))
                {
                    sb.Append("    ").Append(member).Append('\n');
                }
            }
        }

        return sb.ToString();
    }

    private static string Describe(Type type)
    {
        var kind =
            type.IsEnum ? "enum"
            : type.IsInterface ? "interface"
            : type.IsValueType ? "struct"
            : typeof(Delegate).IsAssignableFrom(type) ? "delegate"
            : type.IsAbstract && type.IsSealed ? "static class"
            : type.IsAbstract ? "abstract class"
            : type.IsSealed ? "sealed class"
            : "class";
        return $"{kind} {Name(type)}";
    }

    private static IEnumerable<string> Members(Type type)
    {
        const BindingFlags flags =
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        var lines = new List<string>();

        foreach (var field in type.GetFields(flags).Where(Visible))
        {
            if (type.IsEnum)
            {
                // Skips the synthetic `value__` backing field, which is not a literal.
                if (field.IsLiteral)
                {
                    lines.Add($"{field.Name} = {Convert.ToInt64(field.GetRawConstantValue())}");
                }
                continue;
            }

            // A const's value is baked into consumers, so it is part of the contract, not just its type.
            var constant = field.IsLiteral ? $" = {Literal(field.GetRawConstantValue())}" : "";
            lines.Add($"{Name(field.FieldType)} {field.Name}{constant}");
        }

        foreach (var ctor in type.GetConstructors(flags).Where(Visible))
        {
            lines.Add($".ctor({Parameters(ctor)})");
        }

        foreach (var property in type.GetProperties(flags))
        {
            var get = property.GetMethod is { } g && Visible(g);
            var set = property.SetMethod is { } s && Visible(s);
            if (!get && !set)
            {
                continue;
            }
            var accessors =
                (get ? "get;" : "")
                + (
                    set
                        ? (
                            property.SetMethod!.ReturnParameter.GetRequiredCustomModifiers().Any(m => m.Name == "IsExternalInit")
                                ? "init;"
                                : "set;"
                        )
                        : ""
                );
            var indexer = property.GetIndexParameters();
            var name = indexer.Length == 0 ? property.Name : $"this[{string.Join(", ", indexer.Select(p => Name(p.ParameterType)))}]";
            lines.Add($"{Name(property.PropertyType)} {name} {{ {accessors} }}");
        }

        foreach (var evt in type.GetEvents(flags).Where(e => e.AddMethod is { } a && Visible(a)))
        {
            lines.Add($"event {Name(evt.EventHandlerType!)} {evt.Name}");
        }

        foreach (var method in type.GetMethods(flags).Where(Visible).Where(NotAccessor))
        {
            lines.Add($"{Name(method.ReturnType)} {method.Name}{TypeArgs(method)}({Parameters(method)})");
        }

        lines.Sort(StringComparer.Ordinal);
        return lines;
    }

    // Compiler-generated record plumbing is not a contract anyone writes against, and it moves for
    // reasons that are not API changes.
    private static bool NotAccessor(MethodInfo method) =>
        !method.IsSpecialName
        && method.Name is not ("<Clone>$" or "Deconstruct" or "PrintMembers" or "GetHashCode" or "ToString" or "Equals");

    private static bool Visible(FieldInfo f) => (f.IsPublic || f.IsFamily || f.IsFamilyOrAssembly) && !f.Name.Contains('<');

    private static bool Visible(MethodBase m) =>
        (m.IsPublic || m.IsFamily || m.IsFamilyOrAssembly) && !m.Name.Contains('<') && m.Name != "get_EqualityContract";

    // One member per line is the whole point of the format, so a const string with a newline in it
    // would corrupt the diff rather than show up in it.
    //
    // Long values are fingerprinted rather than inlined. A generated const can hold an entire
    // document (CodeManifests.MarkdownReport is ~20 KB), and dumping it here would both drown the
    // diff this gate exists to make readable and re-trigger it on every code-family description
    // edit - which PersistedCodeContractTests already fences with its own hash. The length and digest
    // still detect any change to the value.
    private const int MaxLiteralLength = 120;

    private static string Literal(object? value)
    {
        if (value is null)
        {
            return "null";
        }

        var text = value.ToString()!.Replace("\r", "\\r").Replace("\n", "\\n");
        if (text.Length <= MaxLiteralLength)
        {
            return text;
        }

        var digest = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(text)))[..8];
        return $"<{text.Length} chars, sha256:{digest}>";
    }

    private static string Parameters(MethodBase method) =>
        string.Join(", ", method.GetParameters().Select(p => $"{Name(p.ParameterType)} {p.Name}{(p.HasDefaultValue ? " = default" : "")}"));

    private static string TypeArgs(MethodInfo method) =>
        method.IsGenericMethodDefinition ? "<" + string.Join(", ", method.GetGenericArguments().Select(a => a.Name)) + ">" : "";

    private static string Name(Type type)
    {
        if (type.IsByRef)
        {
            return "ref " + Name(type.GetElementType()!);
        }
        if (type.IsArray)
        {
            return Name(type.GetElementType()!) + "[]";
        }
        if (!type.IsGenericType)
        {
            return type.FullName ?? type.Name;
        }
        var definition = type.GetGenericTypeDefinition().FullName ?? type.Name;
        var tick = definition.IndexOf('`');
        var bare = tick < 0 ? definition : definition[..tick];
        return $"{bare}<{string.Join(", ", type.GetGenericArguments().Select(Name))}>";
    }

    private static string ResolveRepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Acta.slnx")))
            {
                return directory.FullName;
            }
            directory = directory.Parent;
        }
        throw new InvalidOperationException("Could not locate Acta.slnx from " + AppContext.BaseDirectory);
    }
}
