-- Acta full provisioning script (sqlite), schema 'main'. GENERATED by tools/Acta.Emit (`docs`
-- command); do not hand-edit here - edit the source SQL and regenerate. To relocate, replace the
-- schema name 'main' throughout. Baseline stamp: init-entity-refs-v1.
--
-- The same SQL the bootstrap migration runner applies: the migration history table, every
-- migration in order (each records its own history row), then the operator objects the
-- provider installs.
--
-- INSTALL AND UPGRADE ARE THE SAME FILE. Run it on an empty database or on one already
-- running an earlier Acta version: every statement is individually guarded, so it applies
-- exactly what is missing and skips what is present. Re-running it is a no-op. Views and
-- routines carry no version and are always rewritten to the definitions shipped here.
--
-- Run it under a DDL-capable principal; the application principal then needs only DML and
-- EXECUTE, with ApplyMigrationsOnStartup left false. Because the history rows (and the
-- baseline stamp) are recorded by the script itself, a bootstrap with migrations enabled also
-- accepts the result and applies nothing. Site-specific physical tuning (partitioning,
-- tablespaces, compression) is yours to add; keep the logical shape - tables, columns,
-- constraints, routine signatures - intact.

BEGIN;

-- ===== migration history table =====
CREATE TABLE IF NOT EXISTS main.migrations (
    version INTEGER NOT NULL,
    name TEXT NOT NULL,
    applied_at_utc TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'now')),
    installed_schema TEXT NOT NULL,
    CONSTRAINT pk_migrations PRIMARY KEY (version)
) STRICT;

-- ===== BEGIN M001_init =====
CREATE TABLE IF NOT EXISTS main.alerts (
    id integer PRIMARY KEY AUTOINCREMENT,
    alert_ref text NOT NULL,
    namespace_id integer NOT NULL,
    job_id integer NULL,
    job_ref text NULL,
    origin_code integer NOT NULL,
    severity_code integer NOT NULL,
    kind_code integer NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    channel_name text NOT NULL,
    dedupe_key text NULL,
    dedupe_window_start_utc integer NULL,
    occurrence_count integer NOT NULL,
    resolved_at_utc integer NULL,
    acknowledged_at_utc integer NULL,
    delivery_status_code integer NOT NULL,
    retry_count integer NOT NULL,
    retry_after_utc integer NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_alerts_job_ref_pair CHECK ((job_id IS NULL AND job_ref IS NULL) OR (job_id IS NOT NULL AND job_ref IS NOT NULL))
    , CONSTRAINT ck_alerts_dedupe_pair CHECK ((dedupe_key IS NULL AND dedupe_window_start_utc IS NULL) OR (dedupe_key IS NOT NULL AND dedupe_window_start_utc IS NOT NULL))
    , CONSTRAINT ck_alerts_occurrence_count CHECK (occurrence_count >= 1)
    , CONSTRAINT ck_alerts_origin_code CHECK (origin_code IN (10, 20))
    , CONSTRAINT ck_alerts_severity_code CHECK (severity_code IN (10, 20, 30, 40))
    , CONSTRAINT ck_alerts_delivery_status_code CHECK (delivery_status_code IN (10, 20, 30, 100, 200))
    , CONSTRAINT ck_alerts_retry_count_byte CHECK (retry_count BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_alerts_delivery_due ON alerts (namespace_id, delivery_status_code, retry_after_utc, id);
CREATE INDEX IF NOT EXISTS main.ix_alerts_namespace_created ON alerts (namespace_id, created_at_utc DESC, id DESC);
CREATE INDEX IF NOT EXISTS main.ix_alerts_namespace_unresolved ON alerts (namespace_id, created_at_utc DESC, id DESC) WHERE resolved_at_utc IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_alerts_ref ON alerts (alert_ref);
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_alerts_dedupe ON alerts (namespace_id, dedupe_key, dedupe_window_start_utc) WHERE dedupe_key IS NOT NULL;

-- JobDefinition
CREATE TABLE IF NOT EXISTS main.definitions (
    id integer PRIMARY KEY AUTOINCREMENT,
    namespace_id integer NOT NULL,
    name text NOT NULL,
    status_code integer NOT NULL,
    definition_hash text NOT NULL,
    manifest_generation_at_utc integer NOT NULL,
    input_type_name text NOT NULL,
    input_format_id integer NOT NULL,
    input_format_name text NOT NULL,
    output_type_name text NULL,
    output_format_id integer NOT NULL,
    output_format_name text NOT NULL,
    tenant_requirement_code integer NOT NULL,
    priority_code integer NOT NULL,
    priority_code_override integer NULL,
    priority_code_effective integer AS (COALESCE(priority_code_override, priority_code)) STORED,
    max_attempts integer NOT NULL,
    max_attempts_override integer NULL,
    max_attempts_effective integer AS (COALESCE(max_attempts_override, max_attempts)) STORED,
    backoff text NOT NULL,
    backoff_override text NULL,
    backoff_effective text AS (COALESCE(backoff_override, backoff)) STORED,
    execution_timeout_seconds integer NOT NULL,
    execution_timeout_seconds_override integer NULL,
    execution_timeout_seconds_effective integer AS (COALESCE(execution_timeout_seconds_override, execution_timeout_seconds)) STORED,
    deadline_seconds integer NOT NULL,
    deadline_seconds_override integer NULL,
    deadline_seconds_effective integer AS (COALESCE(deadline_seconds_override, deadline_seconds)) STORED,
    deadline_behavior_code integer NOT NULL,
    deadline_behavior_code_override integer NULL,
    deadline_behavior_code_effective integer AS (COALESCE(deadline_behavior_code_override, deadline_behavior_code)) STORED,
    retention_seconds integer NOT NULL,
    retention_seconds_override integer NULL,
    retention_seconds_effective integer AS (COALESCE(retention_seconds_override, retention_seconds)) STORED,
    audit_level_code integer NOT NULL,
    audit_level_code_override integer NULL,
    audit_level_code_effective integer AS (COALESCE(audit_level_code_override, audit_level_code)) STORED,
    alert_profile_code integer NOT NULL,
    alert_profile_code_override integer NULL,
    alert_profile_code_effective integer AS (COALESCE(alert_profile_code_override, alert_profile_code)) STORED,
    alert_channel_name text NULL,
    alert_channel_name_override text NULL,
    alert_channel_name_effective text AS (COALESCE(alert_channel_name_override, alert_channel_name)) STORED,
    runbook_url text NULL,
    runbook_url_override text NULL,
    runbook_url_effective text AS (COALESCE(runbook_url_override, runbook_url)) STORED,
    display_name text NULL,
    display_name_override text NULL,
    display_name_effective text AS (COALESCE(display_name_override, display_name)) STORED,
    description text NULL,
    description_override text NULL,
    description_effective text AS (COALESCE(description_override, description)) STORED,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_definitions_max_attempts CHECK (max_attempts >= 1)
    , CONSTRAINT ck_definitions_max_attempts_override CHECK (max_attempts_override IS NULL OR max_attempts_override >= 1)
    , CONSTRAINT ck_definitions_execution_timeout CHECK (execution_timeout_seconds > 0)
    , CONSTRAINT ck_definitions_execution_timeout_override CHECK (execution_timeout_seconds_override IS NULL OR execution_timeout_seconds_override > 0)
    , CONSTRAINT ck_definitions_deadline CHECK (deadline_seconds >= 0)
    , CONSTRAINT ck_definitions_deadline_override CHECK (deadline_seconds_override IS NULL OR deadline_seconds_override >= 0)
    , CONSTRAINT ck_definitions_retention CHECK (retention_seconds >= 0)
    , CONSTRAINT ck_definitions_retention_override CHECK (retention_seconds_override IS NULL OR retention_seconds_override >= 0)
    , CONSTRAINT ck_definitions_status_code CHECK (status_code IN (10, 240))
    , CONSTRAINT ck_definitions_tenant_requirement_code CHECK (tenant_requirement_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_priority_code_override CHECK (priority_code_override IS NULL OR priority_code_override IN (0, 50, 70, 85, 100))
    , CONSTRAINT ck_definitions_deadline_behavior_code CHECK (deadline_behavior_code IN (10, 20))
    , CONSTRAINT ck_definitions_deadline_behavior_code_override CHECK (deadline_behavior_code_override IS NULL OR deadline_behavior_code_override IN (10, 20))
    , CONSTRAINT ck_definitions_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_definitions_audit_level_code_override CHECK (audit_level_code_override IS NULL OR audit_level_code_override IN (0, 10, 20))
    , CONSTRAINT ck_definitions_alert_profile_code CHECK (alert_profile_code IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_alert_profile_code_override CHECK (alert_profile_code_override IS NULL OR alert_profile_code_override IN (0, 10, 20, 30, 40))
    , CONSTRAINT ck_definitions_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
    , CONSTRAINT ck_definitions_output_format_id_byte CHECK (output_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_definitions_namespace_name ON definitions (namespace_id, name);

-- JobEvent
CREATE TABLE IF NOT EXISTS main.events (
    id integer PRIMARY KEY AUTOINCREMENT,
    event_code integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    namespace_id integer NOT NULL,
    actor_code integer NOT NULL,
    actor_key text NULL,
    job_id integer NULL,
    job_ref text NULL,
    execution_number integer NULL,
    lineage_root_id integer NULL,
    definition_id integer NULL,
    tenant_id integer NULL,
    worker_id integer NULL,
    from_status_code integer NULL,
    to_status_code integer NULL,
    execution_status_code integer NULL,
    duration_ms integer NULL,
    reason_code integer NULL,
    reason_message text NULL,
    detail_format_id integer DEFAULT 0 NOT NULL,
    detail blob NULL
    , CONSTRAINT ck_events_detail_pair CHECK ((detail_format_id = 0 AND detail IS NULL) OR (detail_format_id <> 0 AND detail IS NOT NULL))
    , CONSTRAINT ck_events_actor_code CHECK (actor_code IN (10, 20, 50, 70))
    , CONSTRAINT ck_events_from_status_code CHECK (from_status_code IS NULL OR from_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_to_status_code CHECK (to_status_code IS NULL OR to_status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_events_execution_status_code CHECK (execution_status_code IS NULL OR execution_status_code IN (50, 100, 150, 151, 152, 200, 220, 230))
    , CONSTRAINT ck_events_detail_format_id_byte CHECK (detail_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_events_lineage_timeline ON events (lineage_root_id, created_at_utc, id) WHERE lineage_root_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS main.ix_events_namespace_timeline ON events (namespace_id, event_code, created_at_utc, id);
CREATE INDEX IF NOT EXISTS main.ix_events_job_timeline ON events (job_id, created_at_utc, id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS main.ix_events_namespace_created ON events (namespace_id, created_at_utc DESC, id DESC);

-- Job
CREATE TABLE IF NOT EXISTS main.jobs (
    id integer PRIMARY KEY AUTOINCREMENT,
    job_ref text NOT NULL,
    namespace_id integer NOT NULL,
    definition_id integer NOT NULL,
    lineage_root_id integer NULL,
    parent_id integer NULL,
    tenant_id integer NULL,
    deduplication_key text NULL,
    correlation_key text NULL,
    exclusive_key text NULL,
    input_format_id integer NOT NULL,
    input blob NULL,
    audit_level_code integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL
    , CONSTRAINT ck_jobs_input_pair CHECK ((input_format_id = 0 AND input IS NULL) OR (input_format_id <> 0 AND input IS NOT NULL))
    , CONSTRAINT ck_jobs_audit_level_code CHECK (audit_level_code IN (0, 10, 20))
    , CONSTRAINT ck_jobs_input_format_id_byte CHECK (input_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_jobs_parent ON jobs (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS main.ix_jobs_namespace_created ON jobs (namespace_id, created_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_jobs_ref ON jobs (job_ref);
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_jobs_deduplication_key_root ON jobs (namespace_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_jobs_deduplication_key_child ON jobs (parent_id, deduplication_key) WHERE deduplication_key IS NOT NULL AND parent_id IS NOT NULL;

-- Lock
CREATE TABLE IF NOT EXISTS main.locks (
    lock_key text NOT NULL,
    job_id integer NOT NULL,
    expires_at_utc integer NOT NULL,
    hold_token text NOT NULL
    , CONSTRAINT pk_locks PRIMARY KEY (lock_key)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_locks_reclaim_expired ON locks (expires_at_utc);

-- JobNamespace
CREATE TABLE IF NOT EXISTS main.namespaces (
    id integer PRIMARY KEY AUTOINCREMENT,
    name text NOT NULL,
    owner_team text NULL,
    description text NULL,
    status_code integer NOT NULL,
    catalog_hash text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_namespaces_status_code CHECK (status_code IN (10, 20))
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_namespaces_name ON namespaces (name);

-- Seed: reserved system namespace (id=1, 'sys') for cross-namespace audit events. Collation-neutral.
INSERT OR IGNORE INTO main.namespaces (id, name, status_code, description, created_at_utc, modified_at_utc)
VALUES (1, 'sys', 10, 'Reserved system namespace for cross-namespace audit events.', CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER), CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER));

-- JobResult
CREATE TABLE IF NOT EXISTS main.results (
    job_id integer NOT NULL,
    execution_number integer NOT NULL,
    result_format_id integer NOT NULL,
    result blob NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL
    , CONSTRAINT pk_results PRIMARY KEY (job_id, execution_number)
    , CONSTRAINT ck_results_format_not_none CHECK (result_format_id <> 0)
    , CONSTRAINT ck_results_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_results_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;

-- JobRuntime
CREATE TABLE IF NOT EXISTS main.runtimes (
    job_id integer NOT NULL,
    namespace_id integer NOT NULL,
    status_code integer NOT NULL,
    priority_code integer NOT NULL,
    next_run_at_utc integer NULL,
    execution_number integer NOT NULL,
    failure_count integer NOT NULL,
    leased_by_worker_id integer NULL,
    lease_expires_at_utc integer NULL,
    retention_until_utc integer NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_runtimes PRIMARY KEY (job_id)
    , CONSTRAINT ck_runtimes_lease_consistency CHECK ((leased_by_worker_id IS NULL AND lease_expires_at_utc IS NULL) OR (leased_by_worker_id IS NOT NULL AND lease_expires_at_utc IS NOT NULL))
    , CONSTRAINT ck_runtimes_counters CHECK (execution_number >= 0 AND failure_count >= 0)
    , CONSTRAINT ck_runtimes_status_code CHECK (status_code IN (10, 20, 30, 40, 50, 100, 200, 220))
    , CONSTRAINT ck_runtimes_priority_code CHECK (priority_code IN (0, 50, 70, 85, 100))
    , CONSTRAINT fk_runtimes_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_runtimes_claim_ready ON runtimes (namespace_id, priority_code DESC, next_run_at_utc, job_id) WHERE status_code = 10;
CREATE INDEX IF NOT EXISTS main.ix_runtimes_retention ON runtimes (namespace_id, retention_until_utc, job_id) WHERE retention_until_utc IS NOT NULL AND status_code IN (100, 200, 220);
CREATE INDEX IF NOT EXISTS main.ix_runtimes_worker_inflight ON runtimes (leased_by_worker_id, status_code) WHERE leased_by_worker_id IS NOT NULL AND status_code IN (40, 50);

-- JobSchedule
CREATE TABLE IF NOT EXISTS main.schedules (
    id integer PRIMARY KEY AUTOINCREMENT,
    namespace_id integer NOT NULL,
    job_id integer NOT NULL,
    definition_id integer NOT NULL,
    name text NOT NULL,
    origin_code integer NOT NULL,
    expression text NOT NULL,
    expression_override text NULL,
    expression_effective text AS (COALESCE(expression_override, expression)) STORED,
    time_zone_id text NOT NULL,
    time_zone_id_override text NULL,
    time_zone_id_effective text AS (COALESCE(time_zone_id_override, time_zone_id)) STORED,
    expression_kind_code integer NOT NULL,
    misfire_strategy_code integer NOT NULL,
    next_run_at_utc integer NULL,
    last_occurrence_at_utc integer NULL,
    status_code integer NOT NULL,
    paused_until_utc integer NULL,
    description text NULL,
    reason_message text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_schedules_paused_pair CHECK (status_code = 30 OR paused_until_utc IS NULL)
    , CONSTRAINT ck_schedules_orphan_origin CHECK (origin_code = 40 OR status_code <> 230)
    , CONSTRAINT ck_schedules_origin_code CHECK (origin_code IN (20, 40))
    , CONSTRAINT ck_schedules_expression_kind_code CHECK (expression_kind_code IN (10, 20))
    , CONSTRAINT ck_schedules_misfire_strategy_code CHECK (misfire_strategy_code IN (10, 20))
    , CONSTRAINT ck_schedules_status_code CHECK (status_code IN (10, 30, 230))
    , CONSTRAINT fk_schedules_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
    , CONSTRAINT fk_schedules_definitions FOREIGN KEY (definition_id) REFERENCES definitions (id)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_schedules_namespace_next ON schedules (namespace_id, next_run_at_utc, id) WHERE status_code <> 230;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_schedules_job_name ON schedules (job_id, name);

-- Setting
CREATE TABLE IF NOT EXISTS main.settings (
    id integer PRIMARY KEY AUTOINCREMENT,
    scope_code integer NOT NULL,
    scope_id integer NULL,
    name text NOT NULL,
    value_format_id integer NOT NULL,
    value blob NULL,
    description text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_settings_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_settings_scope_code CHECK (scope_code IN (10, 30, 40))
    , CONSTRAINT ck_settings_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_settings_scope_name ON settings (scope_code, scope_id, name) WHERE scope_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_settings_global_name ON settings (scope_code, name) WHERE scope_id IS NULL;

-- JobStep
CREATE TABLE IF NOT EXISTS main.steps (
    id integer PRIMARY KEY AUTOINCREMENT,
    job_id integer NOT NULL,
    name text NOT NULL,
    status_code integer NOT NULL,
    attempt_number integer NOT NULL,
    next_retry_at_utc integer NULL,
    reason_code integer NULL,
    reason_message text NULL,
    result_format_id integer NOT NULL,
    result blob NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_steps_result_pair CHECK ((result_format_id = 0 AND result IS NULL) OR (result_format_id <> 0 AND result IS NOT NULL))
    , CONSTRAINT ck_steps_attempt_number CHECK (attempt_number >= 1)
    , CONSTRAINT ck_steps_status_code CHECK (status_code IN (10, 100, 200, 230))
    , CONSTRAINT ck_steps_result_format_id_byte CHECK (result_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_steps_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_steps_job_name ON steps (job_id, name);

-- Tag
CREATE TABLE IF NOT EXISTS main.tags (
    scope_code integer NOT NULL,
    scope_id integer NOT NULL,
    namespace_id integer NULL,
    name text NOT NULL,
    value text NULL,
    value_search text NULL
    , CONSTRAINT pk_tags PRIMARY KEY (scope_code, scope_id, name)
    , CONSTRAINT ck_tags_scope_id CHECK (scope_id > 0)
    , CONSTRAINT ck_tags_namespace_id CHECK (namespace_id IS NULL OR namespace_id > 0)
    , CONSTRAINT ck_tags_scope_namespace CHECK ((scope_code = 20 AND namespace_id IS NULL) OR (scope_code = 30 AND namespace_id IS NOT NULL AND scope_id = namespace_id) OR (scope_code IN (40, 50, 60, 70, 80, 90) AND namespace_id IS NOT NULL))
    , CONSTRAINT ck_tags_value_search CHECK ((value IS NULL AND value_search IS NULL) OR (value IS NOT NULL AND value_search IS NOT NULL))
    , CONSTRAINT ck_tags_scope_code CHECK (scope_code IN (20, 30, 40, 50, 60, 70, 80, 90))
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_tags_namespace_name_value_search ON tags (namespace_id, name, value_search, scope_code, scope_id);

-- Tenant
CREATE TABLE IF NOT EXISTS main.tenants (
    id integer PRIMARY KEY AUTOINCREMENT,
    tenant_key text NOT NULL,
    status_code integer NOT NULL,
    display_name text NULL,
    description text NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_tenants_status_code CHECK (status_code IN (10, 20))
) STRICT;
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_tenants_key ON tenants (tenant_key);

-- JobWorker
CREATE TABLE IF NOT EXISTS main.workers (
    id integer PRIMARY KEY AUTOINCREMENT,
    worker_ref text NOT NULL,
    namespace_id integer NOT NULL,
    status_code integer NOT NULL,
    deployment_version text NOT NULL,
    host text NOT NULL,
    engine_version text NULL,
    dotnet_version text NULL,
    process_id integer NULL,
    max_concurrency integer NOT NULL,
    last_seen_at_utc integer NOT NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT ck_workers_max_concurrency CHECK (max_concurrency > 0)
    , CONSTRAINT ck_workers_status_code CHECK (status_code IN (10, 80, 100, 200))
    , CONSTRAINT fk_workers_namespaces FOREIGN KEY (namespace_id) REFERENCES namespaces (id)
) STRICT;
CREATE INDEX IF NOT EXISTS main.ix_workers_namespace_status_last_seen ON workers (namespace_id, status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS main.ix_workers_status_last_seen ON workers (status_code, last_seen_at_utc);
CREATE INDEX IF NOT EXISTS main.ix_workers_namespace_last_seen ON workers (namespace_id, last_seen_at_utc DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS main.ux_workers_ref ON workers (worker_ref);

-- JobCheckpoint
CREATE TABLE IF NOT EXISTS main.checkpoints (
    job_id integer NOT NULL,
    kind_code integer NOT NULL,
    name text NOT NULL,
    status_code integer NULL,
    due_at_utc integer NULL,
    value_format_id integer DEFAULT 0 NOT NULL,
    value blob NULL,
    created_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    modified_at_utc integer DEFAULT (CAST(unixepoch('now', 'subsec') * 1000 AS INTEGER)) NOT NULL,
    version integer DEFAULT 0 NOT NULL
    , CONSTRAINT pk_checkpoints PRIMARY KEY (job_id, kind_code, name)
    , CONSTRAINT ck_checkpoints_value_pair CHECK ((value_format_id = 0 AND value IS NULL) OR (value_format_id <> 0 AND value IS NOT NULL))
    , CONSTRAINT ck_checkpoints_kind_code CHECK (kind_code IN (10, 20, 30, 40, 50))
    , CONSTRAINT ck_checkpoints_status_code CHECK (status_code IS NULL OR status_code IN (10, 20, 100))
    , CONSTRAINT ck_checkpoints_value_format_id_byte CHECK (value_format_id BETWEEN 0 AND 255)
    , CONSTRAINT fk_checkpoints_jobs FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
) STRICT;


INSERT INTO main.migrations (version, name, installed_schema)
VALUES (0, 'init-entity-refs-v1', 'main')
ON CONFLICT (version) DO NOTHING;
INSERT INTO main.migrations (version, name, installed_schema)
VALUES (1, 'init', 'main')
ON CONFLICT (version) DO NOTHING;

-- ===== END M001_init =====

-- ===== operator views (versionless; always rewritten to this file's definitions) =====

DROP VIEW IF EXISTS main.alerts_view;
CREATE VIEW main.alerts_view AS
SELECT
    a.id AS alert_id,
    a.alert_ref,
    ns.name AS namespace,
    a.job_id,
    a.job_ref,
    j.definition_id,
    d.name AS job_name,
    CASE a.origin_code WHEN 10 THEN 'automatic' WHEN 20 THEN 'manual' END AS origin,
    a.origin_code,
    CASE a.severity_code WHEN 10 THEN 'info' WHEN 20 THEN 'warning' WHEN 30 THEN 'error' WHEN 40 THEN 'critical' END AS severity,
    a.severity_code,
    CASE a.kind_code WHEN 0 THEN 'unspecified' WHEN 10 THEN 'first-failure' WHEN 20 THEN 'threshold-reached' WHEN 30 THEN 'final-failure' WHEN 40 THEN 'manual' WHEN 50 THEN 'recovery' END AS kind,
    a.kind_code,
    CASE a.delivery_status_code WHEN 10 THEN 'pending' WHEN 20 THEN 'retry-after' WHEN 30 THEN 'suppressed' WHEN 100 THEN 'delivered' WHEN 200 THEN 'failed' END AS delivery_status,
    a.delivery_status_code,
    a.title,
    a.message,
    a.channel_name,
    a.dedupe_key AS deduplication_key,
    a.dedupe_window_start_utc,
    a.occurrence_count,
    a.resolved_at_utc,
    a.retry_count,
    a.retry_after_utc,
    a.created_at_utc,
    a.modified_at_utc,
    a.version
FROM main.alerts AS a
JOIN main.namespaces AS ns ON ns.id = a.namespace_id
LEFT JOIN main.jobs AS j ON j.id = a.job_id
LEFT JOIN main.definitions AS d ON d.id = j.definition_id;

DROP VIEW IF EXISTS main.checkpoints_view;
CREATE VIEW main.checkpoints_view AS
SELECT
    c.job_id,
    j.job_ref,
    ns.name AS namespace,
    d.name AS job_name,
    c.name AS checkpoint_name,
    CASE c.kind_code WHEN 10 THEN 'variable' WHEN 20 THEN 'signal' WHEN 30 THEN 'timer' WHEN 40 THEN 'progress' WHEN 50 THEN 'child-latch' END AS kind,
    c.kind_code,
    CASE c.status_code WHEN 10 THEN 'pending' WHEN 20 THEN 'set' WHEN 100 THEN 'consumed' END AS state,
    c.status_code,
    c.due_at_utc,
    CASE c.value_format_id
        WHEN 0 /* JobPayloadFormat.None */ THEN 'none'
        WHEN 1 /* JobPayloadFormat.Json */ THEN 'json'
        WHEN 2 /* JobPayloadFormat.Bytes */ THEN 'bytes'
        WHEN 3 /* JobPayloadFormat.Text */ THEN 'text'
        ELSE 'custom-' || CAST(c.value_format_id AS TEXT)
    END AS value_format,
    CASE WHEN c.value_format_id IN (1 /* JobPayloadFormat.Json */, 3 /* JobPayloadFormat.Text */) THEN CAST(c.value AS TEXT) END
        AS value_text,
    c.created_at_utc,
    c.modified_at_utc,
    c.version
FROM main.checkpoints AS c
JOIN main.jobs AS j ON j.id = c.job_id
JOIN main.namespaces AS ns ON ns.id = j.namespace_id
JOIN main.definitions AS d ON d.id = j.definition_id;

DROP VIEW IF EXISTS main.definitions_view;
CREATE VIEW main.definitions_view AS
SELECT
    d.id AS definition_id,
    ns.name AS namespace,
    d.name AS job_name,
    CASE d.status_code WHEN 10 THEN 'active' WHEN 240 THEN 'retired' END AS status,
    d.status_code,
    d.definition_hash,
    d.manifest_generation_at_utc,
    d.input_type_name,
    d.input_format_name,
    d.output_type_name,
    d.output_format_name,
    CASE d.priority_code_effective WHEN 0 THEN 'bulk' WHEN 50 THEN 'normal' WHEN 70 THEN 'high' WHEN 85 THEN 'critical' WHEN 100 THEN 'realtime' END AS priority,
    d.priority_code_effective AS priority_code,
    d.priority_code AS priority_default_code,
    d.priority_code_override AS priority_override_code,
    d.max_attempts_effective AS max_attempts,
    d.max_attempts AS max_attempts_default,
    d.max_attempts_override,
    d.backoff_effective AS backoff,
    d.backoff AS backoff_default,
    d.backoff_override,
    d.execution_timeout_seconds_effective AS execution_timeout_seconds,
    d.execution_timeout_seconds AS execution_timeout_seconds_default,
    d.execution_timeout_seconds_override,
    d.deadline_seconds_effective AS deadline_seconds,
    d.deadline_seconds AS deadline_seconds_default,
    d.deadline_seconds_override,
    CASE d.deadline_behavior_code_effective WHEN 10 THEN 'strict' WHEN 20 THEN 'advisory' END AS deadline_behavior,
    d.deadline_behavior_code_effective AS deadline_behavior_code,
    d.deadline_behavior_code AS deadline_behavior_default_code,
    d.deadline_behavior_code_override AS deadline_behavior_override_code,
    d.retention_seconds_effective AS retention_seconds,
    d.retention_seconds AS retention_seconds_default,
    d.retention_seconds_override,
    CASE d.audit_level_code_effective WHEN 0 THEN 'off' WHEN 10 THEN 'failures' WHEN 20 THEN 'audit' END AS audit_level,
    d.audit_level_code_effective AS audit_level_code,
    d.audit_level_code AS audit_level_default_code,
    d.audit_level_code_override AS audit_level_override_code,
    CASE d.alert_profile_code_effective WHEN 0 THEN 'none' WHEN 10 THEN 'on-failure' WHEN 20 THEN 'info' WHEN 30 THEN 'on-terminal' WHEN 40 THEN 'sys-critical' END AS alert_profile,
    d.alert_profile_code_effective AS alert_profile_code,
    d.alert_profile_code AS alert_profile_default_code,
    d.alert_profile_code_override AS alert_profile_override_code,
    d.alert_channel_name_effective AS alert_channel_name,
    d.alert_channel_name AS alert_channel_name_default,
    d.alert_channel_name_override,
    d.runbook_url_effective AS runbook_url,
    d.runbook_url AS runbook_url_default,
    d.runbook_url_override,
    d.created_at_utc,
    d.modified_at_utc,
    d.version
FROM main.definitions AS d
JOIN main.namespaces AS ns ON ns.id = d.namespace_id;

DROP VIEW IF EXISTS main.jobs_view;
CREATE VIEW main.jobs_view AS
SELECT
    j.id AS job_id,
    j.job_ref,
    ns.name AS namespace,
    d.name AS job_name,
    CASE r.status_code WHEN 10 THEN 'ready' WHEN 20 THEN 'suspended' WHEN 30 THEN 'paused' WHEN 40 THEN 'dispatched' WHEN 50 THEN 'executing' WHEN 100 THEN 'succeeded' WHEN 200 THEN 'failed' WHEN 220 THEN 'cancelled' END AS status,
    r.status_code,
    j.deduplication_key,
    j.correlation_key,
    j.exclusive_key,
    j.parent_id,
    COALESCE(j.lineage_root_id, j.id) AS lineage_root_job_id,
    root.job_ref AS lineage_root_job_ref,
    j.tenant_id,
    t.tenant_key,
    CASE r.priority_code WHEN 0 THEN 'bulk' WHEN 50 THEN 'normal' WHEN 70 THEN 'high' WHEN 85 THEN 'critical' WHEN 100 THEN 'realtime' END AS priority,
    r.priority_code,
    CASE j.input_format_id
        WHEN 0 /* JobPayloadFormat.None */ THEN 'none'
        WHEN 1 /* JobPayloadFormat.Json */ THEN 'json'
        WHEN 2 /* JobPayloadFormat.Bytes */ THEN 'bytes'
        WHEN 3 /* JobPayloadFormat.Text */ THEN 'text'
        ELSE 'custom-' || CAST(j.input_format_id AS TEXT)
    END AS input_format,
    CASE WHEN j.input_format_id IN (1 /* JobPayloadFormat.Json */, 3 /* JobPayloadFormat.Text */) THEN CAST(j.input AS TEXT) END
        AS input_text,
    lr.execution_number AS last_result_execution_number,
    CASE lr.result_format_id
        WHEN 1 /* JobPayloadFormat.Json */ THEN 'json'
        WHEN 2 /* JobPayloadFormat.Bytes */ THEN 'bytes'
        WHEN 3 /* JobPayloadFormat.Text */ THEN 'text'
        ELSE CASE WHEN lr.result_format_id IS NULL THEN NULL ELSE 'custom-' || CAST(lr.result_format_id AS TEXT) END
    END AS last_result_format,
    CASE WHEN lr.result_format_id IN (1 /* JobPayloadFormat.Json */, 3 /* JobPayloadFormat.Text */) THEN CAST(lr.result AS TEXT) END
        AS last_result_text,
    lr.created_at_utc AS last_result_created_at_utc,
    r.next_run_at_utc,
    r.execution_number,
    r.failure_count,
    r.leased_by_worker_id,
    w.host AS leased_by_worker_host,
    r.lease_expires_at_utc,
    r.retention_until_utc,
    j.created_at_utc,
    r.modified_at_utc,
    r.version
FROM main.jobs AS j
JOIN main.runtimes AS r ON r.job_id = j.id
JOIN main.namespaces AS ns ON ns.id = j.namespace_id
JOIN main.definitions AS d ON d.id = j.definition_id
LEFT JOIN main.jobs AS root ON root.id = COALESCE(j.lineage_root_id, j.id)
LEFT JOIN main.tenants AS t ON t.id = j.tenant_id
LEFT JOIN main.workers AS w ON w.id = r.leased_by_worker_id
LEFT JOIN main.results AS lr
    ON
        lr.job_id = j.id
        AND lr.execution_number = (
            SELECT MAX(rr.execution_number) FROM main.results AS rr
            WHERE rr.job_id = j.id
        );

DROP VIEW IF EXISTS main.schedules_view;
CREATE VIEW main.schedules_view AS
SELECT
    s.id AS schedule_id,
    ns.name AS namespace,
    s.job_id,
    j.job_ref,
    s.definition_id,
    d.name AS job_name,
    s.name AS schedule_name,
    CASE s.origin_code WHEN 20 THEN 'operator' WHEN 40 THEN 'definition' END AS origin,
    s.origin_code,
    CASE s.status_code WHEN 10 THEN 'active' WHEN 30 THEN 'paused' WHEN 230 THEN 'orphaned' END AS status,
    s.status_code,
    s.expression_effective,
    s.expression,
    s.expression_override,
    s.time_zone_id_effective,
    s.time_zone_id,
    s.time_zone_id_override,
    CASE s.expression_kind_code WHEN 10 THEN 'cron' WHEN 20 THEN 'interval' END AS expression_kind,
    s.expression_kind_code,
    CASE s.misfire_strategy_code WHEN 10 THEN 'catch-up-once' WHEN 20 THEN 'skip' END AS misfire_strategy,
    s.misfire_strategy_code,
    s.next_run_at_utc,
    s.last_occurrence_at_utc,
    s.paused_until_utc,
    s.description,
    s.reason_message,
    s.created_at_utc,
    s.modified_at_utc,
    s.version
FROM main.schedules AS s
JOIN main.namespaces AS ns ON ns.id = s.namespace_id
JOIN main.jobs AS j ON j.id = s.job_id
JOIN main.definitions AS d ON d.id = s.definition_id;

DROP VIEW IF EXISTS main.steps_view;
CREATE VIEW main.steps_view AS
SELECT
    s.id AS step_id,
    s.job_id,
    j.job_ref,
    ns.name AS namespace,
    d.name AS job_name,
    s.name AS step_name,
    CASE s.status_code WHEN 10 THEN 'pending' WHEN 100 THEN 'succeeded' WHEN 200 THEN 'exhausted' WHEN 230 THEN 'interrupted' END AS state,
    s.status_code,
    s.attempt_number,
    s.next_retry_at_utc,
    CASE s.reason_code WHEN 0 THEN 'unspecified' WHEN 10 THEN 'job.unclassified' WHEN 20 THEN 'job.unhandled-exception' WHEN 21 THEN 'job.lease-expired' WHEN 22 THEN 'job.execution-timeout' WHEN 23 THEN 'job.non-retryable-exception' WHEN 24 THEN 'job.deadline-exceeded' WHEN 25 THEN 'job.attempt-aborted' WHEN 30 THEN 'job.schedules-exhausted' WHEN 40 THEN 'job.control-manual' WHEN 41 THEN 'job.parent-cancelled' WHEN 42 THEN 'job.definition-retired' WHEN 50 THEN 'job.handler-rescheduled' WHEN 51 THEN 'job.handler-suspended' WHEN 52 THEN 'job.handler-failed' WHEN 53 THEN 'job.handler-cancelled' WHEN 54 THEN 'job.handler-paused' WHEN 60 THEN 'job.signal-released' WHEN 61 THEN 'job.step-retry-scheduled' WHEN 62 THEN 'job.exclusive-key-held' WHEN 63 THEN 'job.step-interrupted' WHEN 64 THEN 'job.result-oversized' WHEN 100 THEN 'worker.clean-shutdown' WHEN 101 THEN 'worker.heartbeat-stale' END AS reason,
    s.reason_code,
    s.reason_message,
    CASE s.result_format_id
        WHEN 0 /* JobPayloadFormat.None */ THEN 'none'
        WHEN 1 /* JobPayloadFormat.Json */ THEN 'json'
        WHEN 2 /* JobPayloadFormat.Bytes */ THEN 'bytes'
        WHEN 3 /* JobPayloadFormat.Text */ THEN 'text'
        ELSE 'custom-' || CAST(s.result_format_id AS TEXT)
    END AS result_format,
    CASE WHEN s.result_format_id IN (1 /* JobPayloadFormat.Json */, 3 /* JobPayloadFormat.Text */) THEN CAST(s.result AS TEXT) END
        AS result_text,
    s.created_at_utc,
    s.modified_at_utc,
    s.version
FROM main.steps AS s
JOIN main.jobs AS j ON j.id = s.job_id
JOIN main.namespaces AS ns ON ns.id = j.namespace_id
JOIN main.definitions AS d ON d.id = j.definition_id;

DROP VIEW IF EXISTS main.workers_view;
CREATE VIEW main.workers_view AS
SELECT
    w.id AS worker_id,
    w.worker_ref,
    ns.name AS namespace,
    CASE w.status_code WHEN 10 THEN 'active' WHEN 80 THEN 'draining' WHEN 100 THEN 'stopped' WHEN 200 THEN 'dead' END AS status,
    w.status_code,
    w.deployment_version,
    w.host,
    w.engine_version,
    w.dotnet_version,
    w.process_id,
    w.max_concurrency,
    w.last_seen_at_utc,
    w.created_at_utc,
    w.modified_at_utc,
    w.version
FROM main.workers AS w
JOIN main.namespaces AS ns ON ns.id = w.namespace_id;

DROP VIEW IF EXISTS main.events_view;
CREATE VIEW main.events_view AS
SELECT
    e.id AS event_id,
    e.created_at_utc,
    ns.name AS namespace,
    e.job_id,
    e.job_ref,
    e.lineage_root_id AS lineage_root_job_id,
    root.job_ref AS lineage_root_job_ref,
    e.definition_id,
    d.name AS job_name,
    CASE e.event_code WHEN 0 THEN 'unspecified' WHEN 10 THEN 'tenant.suspended' WHEN 11 THEN 'tenant.resumed' WHEN 12 THEN 'tenant.updated' WHEN 20 THEN 'namespace.suspended' WHEN 21 THEN 'namespace.resumed' WHEN 22 THEN 'namespace.updated' WHEN 30 THEN 'definition.overrides-updated' WHEN 40 THEN 'job.execution-started' WHEN 41 THEN 'job.execution-finished' WHEN 50 THEN 'job.recurring-rolled-over' WHEN 60 THEN 'job.suspended' WHEN 61 THEN 'job.rescheduled' WHEN 70 THEN 'job.cancelled' WHEN 71 THEN 'job.paused' WHEN 72 THEN 'job.resumed' WHEN 73 THEN 'job.restarted' WHEN 74 THEN 'job.reprioritized' WHEN 75 THEN 'job.purged' WHEN 76 THEN 'job.input-amended' WHEN 80 THEN 'job.signal-raised' WHEN 81 THEN 'job.state-reset' WHEN 90 THEN 'job.note-recorded' WHEN 100 THEN 'schedule.paused' WHEN 101 THEN 'schedule.resumed' WHEN 102 THEN 'schedule.pause-expired' WHEN 103 THEN 'schedule.overrides-updated' WHEN 104 THEN 'schedule.triggered' WHEN 120 THEN 'worker.started' WHEN 121 THEN 'worker.stopped' WHEN 122 THEN 'worker.died' WHEN 140 THEN 'alert.acknowledged' WHEN 141 THEN 'alert.resolved' WHEN 160 THEN 'setting.updated' WHEN 180 THEN 'outbox.requeued' WHEN 181 THEN 'outbox.discarded' END AS event,
    e.event_code,
    CASE e.actor_code WHEN 10 THEN 'sys' WHEN 20 THEN 'operator' WHEN 50 THEN 'job' WHEN 70 THEN 'worker' END AS actor,
    e.actor_code,
    e.actor_key,
    CASE e.from_status_code WHEN 10 THEN 'ready' WHEN 20 THEN 'suspended' WHEN 30 THEN 'paused' WHEN 40 THEN 'dispatched' WHEN 50 THEN 'executing' WHEN 100 THEN 'succeeded' WHEN 200 THEN 'failed' WHEN 220 THEN 'cancelled' END AS from_status,
    e.from_status_code,
    CASE e.to_status_code WHEN 10 THEN 'ready' WHEN 20 THEN 'suspended' WHEN 30 THEN 'paused' WHEN 40 THEN 'dispatched' WHEN 50 THEN 'executing' WHEN 100 THEN 'succeeded' WHEN 200 THEN 'failed' WHEN 220 THEN 'cancelled' END AS to_status,
    e.to_status_code,
    CASE e.execution_status_code WHEN 50 THEN 'executing' WHEN 100 THEN 'succeeded' WHEN 150 THEN 'rescheduled' WHEN 151 THEN 'suspended' WHEN 152 THEN 'paused' WHEN 200 THEN 'failed' WHEN 220 THEN 'cancelled' WHEN 230 THEN 'orphaned' END AS execution_status,
    e.execution_status_code,
    CASE e.reason_code WHEN 0 THEN 'unspecified' WHEN 10 THEN 'job.unclassified' WHEN 20 THEN 'job.unhandled-exception' WHEN 21 THEN 'job.lease-expired' WHEN 22 THEN 'job.execution-timeout' WHEN 23 THEN 'job.non-retryable-exception' WHEN 24 THEN 'job.deadline-exceeded' WHEN 25 THEN 'job.attempt-aborted' WHEN 30 THEN 'job.schedules-exhausted' WHEN 40 THEN 'job.control-manual' WHEN 41 THEN 'job.parent-cancelled' WHEN 42 THEN 'job.definition-retired' WHEN 50 THEN 'job.handler-rescheduled' WHEN 51 THEN 'job.handler-suspended' WHEN 52 THEN 'job.handler-failed' WHEN 53 THEN 'job.handler-cancelled' WHEN 54 THEN 'job.handler-paused' WHEN 60 THEN 'job.signal-released' WHEN 61 THEN 'job.step-retry-scheduled' WHEN 62 THEN 'job.exclusive-key-held' WHEN 63 THEN 'job.step-interrupted' WHEN 64 THEN 'job.result-oversized' WHEN 100 THEN 'worker.clean-shutdown' WHEN 101 THEN 'worker.heartbeat-stale' END AS reason,
    e.reason_code,
    e.reason_message,
    CASE e.detail_format_id
        WHEN 0 /* JobPayloadFormat.None */ THEN 'none'
        WHEN 1 /* JobPayloadFormat.Json */ THEN 'json'
        WHEN 2 /* JobPayloadFormat.Bytes */ THEN 'bytes'
        WHEN 3 /* JobPayloadFormat.Text */ THEN 'text'
        ELSE 'custom-' || CAST(e.detail_format_id AS TEXT)
    END AS detail_format,
    CASE WHEN e.detail_format_id IN (1 /* JobPayloadFormat.Json */, 3 /* JobPayloadFormat.Text */) THEN CAST(e.detail AS TEXT) END
        AS detail_text,
    e.worker_id,
    wkr.worker_ref,
    e.execution_number,
    e.duration_ms,
    e.tenant_id
FROM main.events AS e
JOIN main.namespaces AS ns ON ns.id = e.namespace_id
LEFT JOIN main.definitions AS d ON d.id = e.definition_id
LEFT JOIN main.jobs AS root ON root.id = e.lineage_root_id
LEFT JOIN main.workers AS wkr ON wkr.id = e.worker_id;

DROP VIEW IF EXISTS main.tags_view;
CREATE VIEW main.tags_view AS
SELECT
    CASE t.scope_code WHEN 20 THEN 'tenant' WHEN 30 THEN 'namespace' WHEN 40 THEN 'definition' WHEN 50 THEN 'job' WHEN 60 THEN 'schedule' WHEN 70 THEN 'worker' WHEN 80 THEN 'alert' WHEN 90 THEN 'event' END AS scope,
    t.scope_code,
    t.scope_id,
    ns.name AS namespace,
    t.namespace_id,
    t.name AS tag_name,
    t.value AS tag_value,
    t.value_search AS tag_value_search
FROM main.tags AS t
LEFT JOIN main.namespaces AS ns ON ns.id = t.namespace_id;

COMMIT;

